
/*******************************************************************************

	Creating a drug-specific analysis figure for all three countries

	Author: Flo Martin

	Date: 02/12/2023

	Figure generated by this script
	
		- fixed_ma_primary.pdf for the main manuscript
		
		- mat_ma.pdf for the supplementary
		- pat_ma.pdf for the supplementary
		- sib_ma.pdf for the supplementary
		
*******************************************************************************/

* Start logging

	log using "$Logdir\meta analysis\3c_meta analysis fig all 3", name(meta_analysis_fig_all_3) replace
	
********************************************************************************

	cd "$Graphdir"
	set scheme tab2

* Make the maternal meta-analysis figure for supplementary material and generate the summary effect estimate for the primary figure

	use "$Graphdir\data\family analyses data_all3.dta", clear
	
	keep if model=="maternal"
	
	gen logor = log(or)
	gen loglci = log(lci)
	gen loguci = log(uci)
	
	metan logor loglci loguci, eform by(outcome) lcols(outcome total_exp total_unexp) saving(mat_ma, replace)
	
	* Use the data from metan to make a nicer forest plot
	
	use mat_ma, clear
	
	bys _BY _USE : egen grp_wt = sum(_WT)
	gen pct_grp_wt = 100 * _WT / grp_wt
	
	drop _WT
	rename pct_grp_wt _WT
	
	drop if _USE>=4 & _USE<6
	*drop if _BY==2 & _USE==3
	
	replace _LABELS = "Stillborn" if _LABELS=="a_stillborn"
	replace _LABELS = "Neonatal death" if _LABELS=="b_neonatal_death"
	replace _LABELS = "Preterm delivery" if _LABELS=="c_preterm"
	replace _LABELS = "Post-term delivery" if _LABELS=="d_postterm"
	replace _LABELS = "Small for gestational age" if _LABELS=="e_sga"
	replace _LABELS = "Large for gestational age" if _LABELS=="f_lga"
	replace _LABELS = "Apgar score < 7 at 5 minutes" if _LABELS=="g_apar5_bin"
	
	replace _LABELS = "UK" if _STUDY==1 | _STUDY==6 | _STUDY==9 | _STUDY==12 | _STUDY==15
	replace _LABELS = "Norway" if _STUDY==2 | _STUDY==4 | _STUDY==7 | _STUDY==10 | _STUDY==13 | _STUDY==16 | _STUDY==18
	replace _LABELS = "Sweden" if _STUDY==3 | _STUDY==5 | _STUDY==8 | _STUDY==11 | _STUDY==14 | _STUDY==17 | _STUDY==19
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf: Exposed n/N}"'"'
	label variable total_unexp `"`"{bf: Unexposed n/N}"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	format _ES %4.1fc
	format _WT %4.1fc
	
	*drop if _USE==1
	
	gen country=1 if _LABELS=="UK"
	replace country=2 if _LABELS=="Norway"
	replace country=3 if _LABELS=="Sweden"

	forestplot, eform lcols(total_exp total_unexp) effect("{bf}Odds ratio") null(1) olineopts(lcolor(none)) nlineopts(lcolor(cranberry) lpattern(dash)) xlabel(0.5(0.5)2.5) title("{bf}Primary maternal analysis", size(small)) ///
	plotid(country, list) point1opts(msymbol(triangle) msize(0.75)) point2opts(msymbol(circle) msize(0.75)) point4opts(msymbol(diamond) msize(0.75)) textsize(85) ///
	name(mat_ma, replace)
	
	cd "$Graphdir"
	graph export mat_ma.pdf, replace
	
	replace _LABELS = "UK" if _STUDY==1 | _STUDY==6 | _STUDY==9 | _STUDY==12 | _STUDY==15
	replace _LABELS = "Norway" if _STUDY==2 | _STUDY==4 | _STUDY==7 | _STUDY==10 | _STUDY==13 | _STUDY==16 | _STUDY==18
	replace _LABELS = "Sweden" if _STUDY==3 | _STUDY==5 | _STUDY==8 | _STUDY==11 | _STUDY==14 | _STUDY==17 | _STUDY==19
	
	egen seq=seq()
	drop if seq>39
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	replace _ES = exp(_ES)
	replace _LCI = exp(_LCI)
	replace _UCI = exp(_UCI) 
	
	replace _ES=10 if _ES==.
	replace _LCI=10 if _LCI==.
	replace _UCI=10 if _UCI==.
	
	
	forvalues x=2/39 {
		foreach y in _ES _LCI _UCI {
		
			sum `y' if seq==`x'
			local `y'_`x' = `r(mean)'
			local `y'_`x'_f : display %4.2fc ``y'_`x'' 
			
		}		
	}
	
	replace _ES=. if _ES==10
	replace _LCI=. if _LCI==10
	replace _UCI=. if _UCI==10
	
	forvalues x=2/39 {
	
		local total_exp_`x' = total_exp[`x']
		di "`total_exp_`x''"
		
	}
	
	forvalues x=2/39 {
	
		local total_unexp_`x' = total_unexp[`x']
		di "`total_unexp_`x''"
		
	}
	
	forvalues x=2/39 {
	
		local _LABELS`x' = _LABELS[`x']
		di "`_LABELS`x''"
		
	}
	
	replace _WT=10 if _WT==.
	
	forvalues x=2/39 {
	
		sum _WT if seq==`x'
		local WT_`x' = `r(mean)'
		local WT_`x'_f : display %4.1fc `WT_`x''
		disp "`WT_`x'_f'"
		
	}
	
	replace _WT=. if _WT==10
	
	* Macros to create the null line
	local t1=0
	local t2=40
	
	tw ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap _LCI _UCI seq, horizontal lcolor(black) mlw(thin) msize(*0.5)) ///
	(rcap _LCI _UCI seq if _USE==3, horizontal lcolor(cranberry) mlw(thin) msize(*0.5)) ///
	(scatter seq _ES if _LABELS=="UK", mcolor("85 119 135") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Norway", mcolor("217 142 98") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Sweden", mcolor("168 210 218") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _USE==3, mcolor(cranberry) ms(d) msize(small) mcolor(white) mlcolor(cranberry) mlw(thin)), ///
	yscale(range(-1.5 40) reverse noline) ylab("", angle(0) labsize(*0.6) notick nogrid nogextend) /// 
	legend(order(4 "UK" 5 "Norway" 6 "Sweden" 7 "Overall") col(1) region(lcolor(black)) pos(5) size(*0.75)) ///
	yline(-2) yline(0) yline(6, lcolor(gray) lpattern(dot)) yline(11, lcolor(gray) lpattern(dot)) yline(17, lcolor(gray) lpattern(dot)) yline(23, lcolor(gray) lpattern(dot)) yline(29, lcolor(gray) lpattern(dot)) yline(35, lcolor(gray) lpattern(dot)) ///
	xscale(range(0.1 5.7) log) xlab(0.4(0.2)2.9, labsize(*0.4) format(%3.1fc) angle(45))  ///
	graphregion(color(white) fcolor(white) ifcolor(white) lcolor(white)) plotregion(margin(1 1 0 1)) ///
	title("{bf}Fixed-effect meta-analysis of maternal antidepressant use" "{bf}during pregnancy and birth outcomes in the UK, Norway, & Sweden", size(*0.5)) ///
	text(-1 2.9 "{bf}aOR* (95% CI)", size(*0.35) justification(left) placement(e)) ///
	text(-1 4.4 "{bf}Weight (%)", size(*0.35) justification(left) placement(e)) ///
	text(-1 0.1 "{bf}Outcome" "	Country", size(*0.35) justification(left) placement(e)) ///
	text(-1 0.21 "{bf}Exposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(-1 0.39 "{bf}Unexposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(1 0.1 "{bf:Stillborn}", size(*0.35) justification(left) placement(e)) ///
		text(2 0.11 "`_LABELS2'", size(*0.35) justification(left) placement(e)) ///
	text(2 0.21 "`total_exp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 0.39 "`total_unexp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 2.9 "`_ES_2_f' (`_LCI_2_f' – `_UCI_2_f')", size(*0.35) justification(left) placement(e)) ///
	text(2 5.5 "`WT_2_f'", size(*0.35) justification(right) placement(w)) ///
		text(3 0.11 "`_LABELS3'", size(*0.35) justification(left) placement(e)) ///
	text(3 0.21 "`total_exp_3'", size(*0.35) justification(right) placement(w)) ///
	text(3 0.39 "`total_unexp_3'", size(*0.35) justification(right) placement(w)) ///
	text(3 2.9 "`_ES_3_f' (`_LCI_3_f' – `_UCI_3_f')", size(*0.35) justification(left) placement(e)) ///
	text(3 5.5 "`WT_3_f'", size(*0.35) justification(right) placement(w)) ///
		text(4 0.11 "`_LABELS4'", size(*0.35) justification(left) placement(e)) ///
	text(4 0.21 "`total_exp_4'", size(*0.35) justification(right) placement(w)) ///
	text(4 0.39 "`total_unexp_4'", size(*0.35) justification(right) placement(w)) ///
	text(4 2.9 "`_ES_4_f' (`_LCI_4_f' – `_UCI_4_f')", size(*0.35) justification(left) placement(e)) ///
	text(4 5.5 "`WT_4_f'", size(*0.35) justification(right) placement(w)) ///
		text(5 0.1 "`_LABELS5'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(5 2.9 "`_ES_5_f' (`_LCI_5_f' – `_UCI_5_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(5 5.5 "`WT_5_f'", size(*0.35) justification(right) placement(w)) ///
	text(7 0.1 "{bf:Neonatal death{sup:‡}}", size(*0.35) justification(left) placement(e)) ///
		text(8 0.11 "`_LABELS8'", size(*0.35) justification(left) placement(e)) ///
	text(8 0.21 "`total_exp_8'", size(*0.35) justification(right) placement(w)) ///
	text(8 0.39 "`total_unexp_8'", size(*0.35) justification(right) placement(w)) ///
	text(8 2.9 "`_ES_8_f' (`_LCI_8_f' – `_UCI_8_f')", size(*0.35) justification(left) placement(e)) ///
	text(8 5.5 "`WT_8_f'", size(*0.35) justification(right) placement(w)) ///
		text(9 0.11 "`_LABELS9'", size(*0.35) justification(left) placement(e)) ///
	text(9 0.21 "`total_exp_9'", size(*0.35) justification(right) placement(w)) ///
	text(9 0.39 "`total_unexp_9'", size(*0.35) justification(right) placement(w)) ///
	text(9 2.9 "`_ES_9_f' (`_LCI_9_f' – `_UCI_9_f')", size(*0.35) justification(left) placement(e)) ///
	text(9 5.5 "`WT_9_f'", size(*0.35) justification(right) placement(w)) ///
		text(10 0.1 "`_LABELS10'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(10 2.9 "`_ES_10_f' (`_LCI_10_f' – `_UCI_10_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(10 5.5 "`WT_10_f'", size(*0.35) justification(right) placement(w)) ///
	text(12 0.1 "{bf:Preterm delivery}", size(*0.35) justification(left) placement(e)) ///
		text(13 0.11 "`_LABELS13'", size(*0.35) justification(left) placement(e)) ///
	text(13 0.21 "`total_exp_13'", size(*0.35) justification(right) placement(w)) ///
	text(13 0.39 "`total_unexp_13'", size(*0.35) justification(right) placement(w)) ///
	text(13 2.9 "`_ES_13_f' (`_LCI_13_f' – `_UCI_13_f')", size(*0.35) justification(left) placement(e)) ///
	text(13 5.5 "`WT_13_f'", size(*0.35) justification(right) placement(w)) ///
		text(14 0.11 "`_LABELS14'", size(*0.35) justification(left) placement(e)) ///
	text(14 0.21 "`total_exp_14'", size(*0.35) justification(right) placement(w)) ///
	text(14 0.39 "`total_unexp_14'", size(*0.35) justification(right) placement(w)) ///
	text(14 2.9 "`_ES_14_f' (`_LCI_14_f' – `_UCI_14_f')", size(*0.35) justification(left) placement(e)) ///
	text(14 5.5 "`WT_14_f'", size(*0.35) justification(right) placement(w)) ///
		text(15 0.11 "`_LABELS15'", size(*0.35) justification(left) placement(e)) ///
	text(15 0.21 "`total_exp_15'", size(*0.35) justification(right) placement(w)) ///
	text(15 0.39 "`total_unexp_15'", size(*0.35) justification(right) placement(w)) ///
	text(15 2.9 "`_ES_15_f' (`_LCI_15_f' – `_UCI_15_f')", size(*0.35) justification(left) placement(e)) ///
	text(15 5.5 "`WT_15_f'", size(*0.35) justification(right) placement(w)) ///
		text(16 0.1 "`_LABELS16'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(16 2.9 "`_ES_16_f' (`_LCI_16_f' – `_UCI_16_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(16 5.5 "`WT_16_f'", size(*0.35) justification(right) placement(w)) ///
	text(18 0.1 "{bf:Post-term delivery}", size(*0.35) justification(left) placement(e)) ///
		text(19 0.11 "`_LABELS19'", size(*0.35) justification(left) placement(e)) ///
	text(19 0.21 "`total_exp_19'", size(*0.35) justification(right) placement(w)) ///
	text(19 0.39 "`total_unexp_19'", size(*0.35) justification(right) placement(w)) ///
	text(19 2.9 "`_ES_19_f' (`_LCI_19_f' – `_UCI_19_f')", size(*0.35) justification(left) placement(e)) ///
	text(19 5.5 "`WT_19_f'", size(*0.35) justification(right) placement(w)) ///
		text(20 0.11 "`_LABELS20'", size(*0.35) justification(left) placement(e)) ///
	text(20 0.21 "`total_exp_20'", size(*0.35) justification(right) placement(w)) ///
	text(20 0.39 "`total_unexp_20'", size(*0.35) justification(right) placement(w)) ///
	text(20 2.9 "`_ES_20_f' (`_LCI_20_f' – `_UCI_20_f')", size(*0.35) justification(left) placement(e)) ///
	text(20 5.5 "`WT_20_f'", size(*0.35) justification(right) placement(w)) ///
		text(21 0.11 "`_LABELS21'", size(*0.35) justification(left) placement(e)) ///
	text(21 0.21 "`total_exp_21'", size(*0.35) justification(right) placement(w)) ///
	text(21 0.39 "`total_unexp_21'", size(*0.35) justification(right) placement(w)) ///
	text(21 2.9 "`_ES_21_f' (`_LCI_21_f' – `_UCI_21_f')", size(*0.35) justification(left) placement(e)) ///
	text(21 5.5 "`WT_21_f'", size(*0.35) justification(right) placement(w)) ///
		text(22 0.1 "`_LABELS22'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(22 2.9 "`_ES_22_f' (`_LCI_22_f' – `_UCI_22_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(22 5.5 "`WT_22_f'", size(*0.35) justification(right) placement(w)) ///
	text(24 0.1 "{bf:Small for gestational age}", size(*0.35) justification(left) placement(e)) ///
		text(25 0.11 "`_LABELS25'", size(*0.35) justification(left) placement(e)) ///
	text(25 0.21 "`total_exp_25'", size(*0.35) justification(right) placement(w)) ///
	text(25 0.39 "`total_unexp_25'", size(*0.35) justification(right) placement(w)) ///
	text(25 5.5 "`WT_25_f'", size(*0.35) justification(right) placement(w)) ///
	text(25 2.9 "`_ES_25_f' (`_LCI_25_f' – `_UCI_25_f')", size(*0.35) justification(left) placement(e)) ///
		text(26 0.11 "`_LABELS26'", size(*0.35) justification(left) placement(e)) ///
	text(26 0.21 "`total_exp_26'", size(*0.35) justification(right) placement(w)) ///
	text(26 0.39 "`total_unexp_26'", size(*0.35) justification(right) placement(w)) ///
	text(26 2.9 "`_ES_26_f' (`_LCI_26_f' – `_UCI_26_f')", size(*0.35) justification(left) placement(e)) ///
	text(26 5.5 "`WT_26_f'", size(*0.35) justification(right) placement(w)) ///
		text(27 0.11 "`_LABELS27'", size(*0.35) justification(left) placement(e)) ///
	text(27 0.21 "`total_exp_27'", size(*0.35) justification(right) placement(w)) ///
	text(27 0.39 "`total_unexp_27'", size(*0.35) justification(right) placement(w)) ///
	text(27 2.9 "`_ES_27_f' (`_LCI_27_f' – `_UCI_27_f')", size(*0.35) justification(left) placement(e)) ///
	text(27 5.5 "`WT_27_f'", size(*0.35) justification(right) placement(w)) ///
		text(28 0.1 "`_LABELS28'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(28 2.9 "`_ES_28_f' (`_LCI_28_f' – `_UCI_28_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(28 5.5 "`WT_28_f'", size(*0.35) justification(right) placement(w)) ///
	text(30 0.1 "{bf:Large for gestational age}", size(*0.35) justification(left) placement(e)) ///
		text(31 0.11 "`_LABELS31'", size(*0.35) justification(left) placement(e)) ///
	text(31 0.21 "`total_exp_31'", size(*0.35) justification(right) placement(w)) ///
	text(31 0.39 "`total_unexp_31'", size(*0.35) justification(right) placement(w)) ///
	text(31 2.9 "`_ES_31_f' (`_LCI_31_f' – `_UCI_31_f')", size(*0.35) justification(left) placement(e)) ///
	text(31 5.5 "`WT_31_f'", size(*0.35) justification(right) placement(w)) ///
		text(32 0.11 "`_LABELS32'", size(*0.35) justification(left) placement(e)) ///
	text(32 0.21 "`total_exp_32'", size(*0.35) justification(right) placement(w)) ///
	text(32 0.39 "`total_unexp_32'", size(*0.35) justification(right) placement(w)) ///
	text(32 2.9 "`_ES_32_f' (`_LCI_32_f' – `_UCI_32_f')", size(*0.35) justification(left) placement(e)) ///
	text(32 5.5 "`WT_32_f'", size(*0.35) justification(right) placement(w)) ///
		text(33 0.11 "`_LABELS33'", size(*0.35) justification(left) placement(e)) ///
	text(33 0.21 "`total_exp_33'", size(*0.35) justification(right) placement(w)) ///
	text(33 0.39 "`total_unexp_33'", size(*0.35) justification(right) placement(w)) ///
	text(33 2.9 "`_ES_33_f' (`_LCI_33_f' – `_UCI_33_f')", size(*0.35) justification(left) placement(e)) ///
	text(33 5.5 "`WT_33_f'", size(*0.35) justification(right) placement(w)) ///
	text(34 0.1 "`_LABELS34'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(34 2.9 "`_ES_34_f' (`_LCI_34_f' – `_UCI_34_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(34 5.5 "`WT_34_f'", size(*0.35) justification(right) placement(w)) ///
	text(36 0.1 "{bf:Low Apgar score{sup:‡}}", size(*0.35) justification(left) placement(e)) ///
		text(37 0.11 "`_LABELS37'", size(*0.35) justification(left) placement(e)) ///
	text(37 0.21 "`total_exp_37'", size(*0.35) justification(right) placement(w)) ///
	text(37 0.39 "`total_unexp_37'", size(*0.35) justification(right) placement(w)) ///
	text(37 2.9 "`_ES_37_f' (`_LCI_37_f' – `_UCI_37_f')", size(*0.35) justification(left) placement(e)) ///
	text(37 5.5 "`WT_37_f'", size(*0.35) justification(right) placement(w)) ///
		text(38 0.11 "`_LABELS38'", size(*0.35) justification(left) placement(e)) ///
	text(38 0.21 "`total_exp_38'", size(*0.35) justification(right) placement(w)) ///
	text(38 0.39 "`total_unexp_38'", size(*0.35) justification(right) placement(w)) ///
	text(38 2.9 "`_ES_38_f' (`_LCI_38_f' – `_UCI_38_f')", size(*0.35) justification(left) placement(e)) ///
	text(38 5.5 "`WT_38_f'", size(*0.35) justification(right) placement(w)) ///
		text(39 0.1 "`_LABELS39'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(39 2.9 "`_ES_39_f' (`_LCI_39_f' – `_UCI_39_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(39 5.5 "`WT_39_f'", size(*0.35) justification(right) placement(w)) ///
	text(44 1.2 "{bf:Odds ratio* (95% confidence interval)}" "from logistic regression", size(*0.45)) ///
	text(45.5 1.2 "from fixed effects meta-analysis", size(*0.45) color(cranberry)) ///
	text(44 0.1 "*Adjusted for year of birth, maternal age," "previous stillbirth, parity, antipsychotic and" "anti-seizure medication use before pregnancy," "depression, anxiety, practice-level IMD and" "ethnicity (UK), maternal educational attainment" "and country of birth (Norway and Sweden)," "household disposable income (Sweden)," "smoking during pregnancy (UK and Sweden)," "maternal BMI (Sweden), number of primary care" "consultations before pregnancy (UK and Norway)", size(*0.35) justification(left) placement(e)) ///
	text(48 0.1 "{sup:‡}Norway and Sweden only", size(*0.35) justification(left) placement(e)) ///
	xsize(90) ysize(100) name(mat, replace)
	
	* Save graph
	
	graph export "C:\Users\ti19522\OneDrive - University of Bristol\Flo Martin Supervisory Team\Year 4\6_Birth outcomes\supplementary figures\mat_ma.pdf", replace

********************************************************************************/

* Make the sibling meta-analysis figure for supplementary material and generate the summary effect estimate for the primary figure
	
	use "$Graphdir\data\family analyses data_all3.dta", clear
	
	keep if model=="sibling"
	
	gen logor = log(or)
	gen loglci = log(lci)
	gen loguci = log(uci)
	
	metan logor loglci loguci, eform by(outcome) lcols(outcome total_exp total_unexp) saving(sib_ma, replace)
	
	* Use the data from metan to make a nicer forest plot
	
	use sib_ma, clear
	
	bys _BY _USE : egen grp_wt = sum(_WT)
	gen pct_grp_wt = 100 * _WT / grp_wt
	
	drop _WT
	rename pct_grp_wt _WT
	
	drop if _USE>=4 & _USE<6
	*drop if _BY==2 & _USE==3
	
	replace _LABELS = "Stillborn" if _LABELS=="a_stillborn"
	replace _LABELS = "Neonatal death" if _LABELS=="b_neonatal_death"
	replace _LABELS = "Preterm delivery" if _LABELS=="c_preterm"
	replace _LABELS = "Post-term delivery" if _LABELS=="d_postterm"
	replace _LABELS = "Small for gestational age" if _LABELS=="e_sga"
	replace _LABELS = "Large for gestational age" if _LABELS=="f_lga"
	replace _LABELS = "Apgar score < 7 at 5 minutes" if _LABELS=="g_apar5_bin"
	
	replace _LABELS = "UK" if _STUDY==1 | _STUDY==6 | _STUDY==9 | _STUDY==12 | _STUDY==15
	replace _LABELS = "Norway" if _STUDY==2 | _STUDY==4 | _STUDY==7 | _STUDY==10 | _STUDY==13 | _STUDY==16 | _STUDY==18
	replace _LABELS = "Sweden" if _STUDY==3 | _STUDY==5 | _STUDY==8 | _STUDY==11 | _STUDY==14 | _STUDY==17 | _STUDY==19
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf: Exposed n/N}"'"'
	label variable total_unexp `"`"{bf: Unexposed n/N}"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	format _ES %4.2fc
	format _WT %4.1fc
	
	gen country=1 if _LABELS=="UK"
	replace country=2 if _LABELS=="Norway"
	replace country=3 if _LABELS=="Sweden"

	forestplot, eform effect("{bf}Odds ratio") lcols(total_exp total_unexp) null(1) olineopts(lcolor(none)) nlineopts(lcolor(cranberry) lpattern(dash)) xlabel(0.5(0.5)2.5) title("{bf}Discordant sibling analysis", size(small)) ///
	plotid(country, list) point1opts(msymbol(triangle) msize(0.75)) point2opts(msymbol(circle) msize(0.75)) point4opts(msymbol(diamond) msize(0.75)) textsize(85) ///
	name(sib_ma, replace)
	
	cd "$Graphdir"
	graph export sib_ma.pdf, replace
	
	replace _LABELS = "UK" if _STUDY==1 | _STUDY==6 | _STUDY==9 | _STUDY==12 | _STUDY==15
	replace _LABELS = "Norway" if _STUDY==2 | _STUDY==4 | _STUDY==7 | _STUDY==10 | _STUDY==13 | _STUDY==16 | _STUDY==18
	replace _LABELS = "Sweden" if _STUDY==3 | _STUDY==5 | _STUDY==8 | _STUDY==11 | _STUDY==14 | _STUDY==17 | _STUDY==19
	
	egen seq=seq()
	drop if seq>39
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	replace _ES = exp(_ES)
	replace _LCI = exp(_LCI)
	replace _UCI = exp(_UCI) 
	
	replace _ES=10 if _ES==.
	replace _LCI=10 if _LCI==.
	replace _UCI=10 if _UCI==.
	
	
	forvalues x=2/39 {
		foreach y in _ES _LCI _UCI {
		
			sum `y' if seq==`x'
			local `y'_`x' = `r(mean)'
			local `y'_`x'_f : display %4.2fc ``y'_`x'' 
			
		}		
	}
	
	replace _ES=. if _ES==10
	replace _LCI=. if _LCI==10
	replace _UCI=. if _UCI==10
	
	forvalues x=2/39 {
	
		local total_exp_`x' = total_exp[`x']
		di "`total_exp_`x''"
		
	}
	
	forvalues x=2/39 {
	
		local total_unexp_`x' = total_unexp[`x']
		di "`total_unexp_`x''"
		
	}
	
	forvalues x=2/39 {
	
		local _LABELS`x' = _LABELS[`x']
		di "`_LABELS`x''"
		
	}
	
	replace _WT=10 if _WT==.
	
	forvalues x=2/39 {
	
		sum _WT if seq==`x'
		local WT_`x' = `r(mean)'
		local WT_`x'_f : display %4.1fc `WT_`x''
		disp "`WT_`x'_f'"
		
	}
	
	replace _WT=. if _WT==10
	
	* Macros to create the null line
	local t1=0
	local t2=40
	
	tw ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap _LCI _UCI seq, horizontal lcolor(black) mlw(thin) msize(*0.5)) ///
	(rcap _LCI _UCI seq if _USE==3, horizontal lcolor(cranberry) mlw(thin) msize(*0.5)) ///
	(scatter seq _ES if _LABELS=="UK", mcolor("85 119 135") ms(t) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Norway", mcolor("217 142 98") ms(t) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Sweden", mcolor("168 210 218") ms(t) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _USE==3, mcolor(cranberry) ms(d) msize(small) mcolor(white) mlcolor(cranberry) mlw(thin)), ///
	yscale(range(-1.5 40) reverse noline) ylab("", angle(0) labsize(*0.6) notick nogrid nogextend) /// 
	legend(order(4 "UK" 5 "Norway" 6 "Sweden" 7 "Overall") col(1) region(lcolor(black)) pos(5) size(*0.75)) ///
	yline(-2) yline(0) yline(6, lcolor(gray) lpattern(dot)) yline(11, lcolor(gray) lpattern(dot)) yline(17, lcolor(gray) lpattern(dot)) yline(23, lcolor(gray) lpattern(dot)) yline(29, lcolor(gray) lpattern(dot)) yline(35, lcolor(gray) lpattern(dot)) ///
	xscale(range(0.1 5.7) log) xlab(0.4(0.2)2.9, labsize(*0.4) format(%3.1fc) angle(45))  ///
	graphregion(color(white) fcolor(white) ifcolor(white) lcolor(white)) plotregion(margin(1 1 0 1)) ///
	title("{bf}Fixed-effect meta-analysis of maternal antidepressant use during pregnancy" "{bf}among discordant siblings and birth outcomes in the UK, Norway, & Sweden", size(*0.5)) ///
	text(-1 2.9 "{bf}aOR* (95% CI)", size(*0.35) justification(left) placement(e)) ///
	text(-1 4.4 "{bf}Weight (%)", size(*0.35) justification(left) placement(e)) ///
	text(-1 0.1 "{bf}Outcome" "	Country", size(*0.35) justification(left) placement(e)) ///
	text(-1 0.21 "{bf}Exposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(-1 0.39 "{bf}Unexposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(1 0.1 "{bf:Stillborn}", size(*0.35) justification(left) placement(e)) ///
		text(2 0.11 "`_LABELS2'", size(*0.35) justification(left) placement(e)) ///
	text(2 0.21 "`total_exp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 0.39 "`total_unexp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 2.9 "`_ES_2_f' (`_LCI_2_f' – `_UCI_2_f')", size(*0.35) justification(left) placement(e)) ///
	text(2 5.5 "`WT_2_f'", size(*0.35) justification(right) placement(w)) ///
		text(3 0.11 "`_LABELS3'", size(*0.35) justification(left) placement(e)) ///
	text(3 0.21 "`total_exp_3'", size(*0.35) justification(right) placement(w)) ///
	text(3 0.39 "`total_unexp_3'", size(*0.35) justification(right) placement(w)) ///
	text(3 2.9 "`_ES_3_f' (`_LCI_3_f' – `_UCI_3_f')", size(*0.35) justification(left) placement(e)) ///
	text(3 5.5 "`WT_3_f'", size(*0.35) justification(right) placement(w)) ///
		text(4 0.11 "`_LABELS4'", size(*0.35) justification(left) placement(e)) ///
	text(4 0.21 "`total_exp_4'", size(*0.35) justification(right) placement(w)) ///
	text(4 0.39 "`total_unexp_4'", size(*0.35) justification(right) placement(w)) ///
	text(4 2.9 "`_ES_4_f' (`_LCI_4_f' – `_UCI_4_f')", size(*0.35) justification(left) placement(e)) ///
	text(4 5.5 "`WT_4_f'", size(*0.35) justification(right) placement(w)) ///
		text(5 0.1 "`_LABELS5'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(5 2.9 "`_ES_5_f' (`_LCI_5_f' – `_UCI_5_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(5 5.5 "`WT_5_f'", size(*0.35) justification(right) placement(w)) ///
	text(7 0.1 "{bf:Neonatal death{sup:‡}}", size(*0.35) justification(left) placement(e)) ///
		text(8 0.11 "`_LABELS8'", size(*0.35) justification(left) placement(e)) ///
	text(8 0.21 "`total_exp_8'", size(*0.35) justification(right) placement(w)) ///
	text(8 0.39 "`total_unexp_8'", size(*0.35) justification(right) placement(w)) ///
	text(8 2.9 "`_ES_8_f' (`_LCI_8_f' – `_UCI_8_f')", size(*0.35) justification(left) placement(e)) ///
	text(8 5.5 "`WT_8_f'", size(*0.35) justification(right) placement(w)) ///
		text(9 0.11 "`_LABELS9'", size(*0.35) justification(left) placement(e)) ///
	text(9 0.21 "`total_exp_9'", size(*0.35) justification(right) placement(w)) ///
	text(9 0.39 "`total_unexp_9'", size(*0.35) justification(right) placement(w)) ///
	text(9 2.9 "`_ES_9_f' (`_LCI_9_f' – `_UCI_9_f')", size(*0.35) justification(left) placement(e)) ///
	text(9 5.5 "`WT_9_f'", size(*0.35) justification(right) placement(w)) ///
		text(10 0.1 "`_LABELS10'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(10 2.9 "`_ES_10_f' (`_LCI_10_f' – `_UCI_10_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(10 5.5 "`WT_10_f'", size(*0.35) justification(right) placement(w)) ///
	text(12 0.1 "{bf:Preterm delivery}", size(*0.35) justification(left) placement(e)) ///
		text(13 0.11 "`_LABELS13'", size(*0.35) justification(left) placement(e)) ///
	text(13 0.21 "`total_exp_13'", size(*0.35) justification(right) placement(w)) ///
	text(13 0.39 "`total_unexp_13'", size(*0.35) justification(right) placement(w)) ///
	text(13 2.9 "`_ES_13_f' (`_LCI_13_f' – `_UCI_13_f')", size(*0.35) justification(left) placement(e)) ///
	text(13 5.5 "`WT_13_f'", size(*0.35) justification(right) placement(w)) ///
		text(14 0.11 "`_LABELS14'", size(*0.35) justification(left) placement(e)) ///
	text(14 0.21 "`total_exp_14'", size(*0.35) justification(right) placement(w)) ///
	text(14 0.39 "`total_unexp_14'", size(*0.35) justification(right) placement(w)) ///
	text(14 2.9 "`_ES_14_f' (`_LCI_14_f' – `_UCI_14_f')", size(*0.35) justification(left) placement(e)) ///
	text(14 5.5 "`WT_14_f'", size(*0.35) justification(right) placement(w)) ///
		text(15 0.11 "`_LABELS15'", size(*0.35) justification(left) placement(e)) ///
	text(15 0.21 "`total_exp_15'", size(*0.35) justification(right) placement(w)) ///
	text(15 0.39 "`total_unexp_15'", size(*0.35) justification(right) placement(w)) ///
	text(15 2.9 "`_ES_15_f' (`_LCI_15_f' – `_UCI_15_f')", size(*0.35) justification(left) placement(e)) ///
	text(15 5.5 "`WT_15_f'", size(*0.35) justification(right) placement(w)) ///
		text(16 0.1 "`_LABELS16'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(16 2.9 "`_ES_16_f' (`_LCI_16_f' – `_UCI_16_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(16 5.5 "`WT_16_f'", size(*0.35) justification(right) placement(w)) ///
	text(18 0.1 "{bf:Post-term delivery}", size(*0.35) justification(left) placement(e)) ///
		text(19 0.11 "`_LABELS19'", size(*0.35) justification(left) placement(e)) ///
	text(19 0.21 "`total_exp_19'", size(*0.35) justification(right) placement(w)) ///
	text(19 0.39 "`total_unexp_19'", size(*0.35) justification(right) placement(w)) ///
	text(19 2.9 "`_ES_19_f' (`_LCI_19_f' – `_UCI_19_f')", size(*0.35) justification(left) placement(e)) ///
	text(19 5.5 "`WT_19_f'", size(*0.35) justification(right) placement(w)) ///
		text(20 0.11 "`_LABELS20'", size(*0.35) justification(left) placement(e)) ///
	text(20 0.21 "`total_exp_20'", size(*0.35) justification(right) placement(w)) ///
	text(20 0.39 "`total_unexp_20'", size(*0.35) justification(right) placement(w)) ///
	text(20 2.9 "`_ES_20_f' (`_LCI_20_f' – `_UCI_20_f')", size(*0.35) justification(left) placement(e)) ///
	text(20 5.5 "`WT_20_f'", size(*0.35) justification(right) placement(w)) ///
		text(21 0.11 "`_LABELS21'", size(*0.35) justification(left) placement(e)) ///
	text(21 0.21 "`total_exp_21'", size(*0.35) justification(right) placement(w)) ///
	text(21 0.39 "`total_unexp_21'", size(*0.35) justification(right) placement(w)) ///
	text(21 2.9 "`_ES_21_f' (`_LCI_21_f' – `_UCI_21_f')", size(*0.35) justification(left) placement(e)) ///
	text(21 5.5 "`WT_21_f'", size(*0.35) justification(right) placement(w)) ///
		text(22 0.1 "`_LABELS22'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(22 2.9 "`_ES_22_f' (`_LCI_22_f' – `_UCI_22_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(22 5.5 "`WT_22_f'", size(*0.35) justification(right) placement(w)) ///
	text(24 0.1 "{bf:Small for gestational age}", size(*0.35) justification(left) placement(e)) ///
		text(25 0.11 "`_LABELS25'", size(*0.35) justification(left) placement(e)) ///
	text(25 0.21 "`total_exp_25'", size(*0.35) justification(right) placement(w)) ///
	text(25 0.39 "`total_unexp_25'", size(*0.35) justification(right) placement(w)) ///
	text(25 5.5 "`WT_25_f'", size(*0.35) justification(right) placement(w)) ///
	text(25 2.9 "`_ES_25_f' (`_LCI_25_f' – `_UCI_25_f')", size(*0.35) justification(left) placement(e)) ///
		text(26 0.11 "`_LABELS26'", size(*0.35) justification(left) placement(e)) ///
	text(26 0.21 "`total_exp_26'", size(*0.35) justification(right) placement(w)) ///
	text(26 0.39 "`total_unexp_26'", size(*0.35) justification(right) placement(w)) ///
	text(26 2.9 "`_ES_26_f' (`_LCI_26_f' – `_UCI_26_f')", size(*0.35) justification(left) placement(e)) ///
	text(26 5.5 "`WT_26_f'", size(*0.35) justification(right) placement(w)) ///
		text(27 0.11 "`_LABELS27'", size(*0.35) justification(left) placement(e)) ///
	text(27 0.21 "`total_exp_27'", size(*0.35) justification(right) placement(w)) ///
	text(27 0.39 "`total_unexp_27'", size(*0.35) justification(right) placement(w)) ///
	text(27 2.9 "`_ES_27_f' (`_LCI_27_f' – `_UCI_27_f')", size(*0.35) justification(left) placement(e)) ///
	text(27 5.5 "`WT_27_f'", size(*0.35) justification(right) placement(w)) ///
		text(28 0.1 "`_LABELS28'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(28 2.9 "`_ES_28_f' (`_LCI_28_f' – `_UCI_28_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(28 5.5 "`WT_28_f'", size(*0.35) justification(right) placement(w)) ///
	text(30 0.1 "{bf:Large for gestational age}", size(*0.35) justification(left) placement(e)) ///
		text(31 0.11 "`_LABELS31'", size(*0.35) justification(left) placement(e)) ///
	text(31 0.21 "`total_exp_31'", size(*0.35) justification(right) placement(w)) ///
	text(31 0.39 "`total_unexp_31'", size(*0.35) justification(right) placement(w)) ///
	text(31 2.9 "`_ES_31_f' (`_LCI_31_f' – `_UCI_31_f')", size(*0.35) justification(left) placement(e)) ///
	text(31 5.5 "`WT_31_f'", size(*0.35) justification(right) placement(w)) ///
		text(32 0.11 "`_LABELS32'", size(*0.35) justification(left) placement(e)) ///
	text(32 0.21 "`total_exp_32'", size(*0.35) justification(right) placement(w)) ///
	text(32 0.39 "`total_unexp_32'", size(*0.35) justification(right) placement(w)) ///
	text(32 2.9 "`_ES_32_f' (`_LCI_32_f' – `_UCI_32_f')", size(*0.35) justification(left) placement(e)) ///
	text(32 5.5 "`WT_32_f'", size(*0.35) justification(right) placement(w)) ///
		text(33 0.11 "`_LABELS33'", size(*0.35) justification(left) placement(e)) ///
	text(33 0.21 "`total_exp_33'", size(*0.35) justification(right) placement(w)) ///
	text(33 0.39 "`total_unexp_33'", size(*0.35) justification(right) placement(w)) ///
	text(33 2.9 "`_ES_33_f' (`_LCI_33_f' – `_UCI_33_f')", size(*0.35) justification(left) placement(e)) ///
	text(33 5.5 "`WT_33_f'", size(*0.35) justification(right) placement(w)) ///
	text(34 0.1 "`_LABELS34'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(34 2.9 "`_ES_34_f' (`_LCI_34_f' – `_UCI_34_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(34 5.5 "`WT_34_f'", size(*0.35) justification(right) placement(w)) ///
	text(36 0.1 "{bf:Low Apgar score{sup:‡}}", size(*0.35) justification(left) placement(e)) ///
		text(37 0.11 "`_LABELS37'", size(*0.35) justification(left) placement(e)) ///
	text(37 0.21 "`total_exp_37'", size(*0.35) justification(right) placement(w)) ///
	text(37 0.39 "`total_unexp_37'", size(*0.35) justification(right) placement(w)) ///
	text(37 2.9 "`_ES_37_f' (`_LCI_37_f' – `_UCI_37_f')", size(*0.35) justification(left) placement(e)) ///
	text(37 5.5 "`WT_37_f'", size(*0.35) justification(right) placement(w)) ///
		text(38 0.11 "`_LABELS38'", size(*0.35) justification(left) placement(e)) ///
	text(38 0.21 "`total_exp_38'", size(*0.35) justification(right) placement(w)) ///
	text(38 0.39 "`total_unexp_38'", size(*0.35) justification(right) placement(w)) ///
	text(38 2.9 "`_ES_38_f' (`_LCI_38_f' – `_UCI_38_f')", size(*0.35) justification(left) placement(e)) ///
	text(38 5.5 "`WT_38_f'", size(*0.35) justification(right) placement(w)) ///
		text(39 0.1 "`_LABELS39'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(39 2.9 "`_ES_39_f' (`_LCI_39_f' – `_UCI_39_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(39 5.5 "`WT_39_f'", size(*0.35) justification(right) placement(w)) ///
	text(44 1.2 "{bf:Odds ratio* (95% confidence interval)}" "from logistic regression", size(*0.45)) ///
	text(45.5 1.2 "from fixed effects meta-analysis", size(*0.45) color(cranberry)) ///
	text(44 0.1 "*Adjusted for birth year, depression, anxiety," "primary healthcare utilisation in the 12 months" "before pregnancy (UK and Norway), antipsychotic" "and anti-seizure medication in the 12 months prior" "to pregnancy (family average minus each siblings" "value to account for non-shared confounding between" "siblings), maternal age, maternal educational" "attainment (Norway and Sweden), house disposable" "income at the start of pregnancy (Sweden), parity," "smoking around the start of pregnancy (UK and Sweden)", size(*0.35) justification(left) placement(e)) ///
	text(48 0.1 "{sup:‡}Norway and Sweden only", size(*0.35) justification(left) placement(e)) ///
	xsize(90) ysize(100) name(sib, replace)
	
	* Save graph
	
	graph export "C:\Users\ti19522\OneDrive - University of Bristol\Flo Martin Supervisory Team\Year 4\6_Birth outcomes\supplementary figures\sib_ma.pdf", replace

********************************************************************************

* Make the paternal meta-analysis figure for supplementary material and generate the summary effect estimate for the primary figure	
	
	use "$Graphdir\data\family analyses data_all3.dta", clear
	
	keep if model=="paternal"
	
	gen logor = log(or)
		gen loglci = log(lci)
		gen loguci = log(uci)
		
		metan logor loglci loguci, eform by(outcome) lcols(outcome total_exp total_unexp) saving(pat_ma, replace)
		
		* Use the data from metan to make a nicer forest plot
		
		use pat_ma, clear
		
		bys _BY _USE : egen grp_wt = sum(_WT)
		gen pct_grp_wt = 100 * _WT / grp_wt
		
		drop _WT
		rename pct_grp_wt _WT
		
		drop if _USE>=4 & _USE<6
		*drop if _BY==2 & _USE==3
		
		replace _LABELS = "Stillborn" if _LABELS=="a_stillborn"
		replace _LABELS = "Neonatal death" if _LABELS=="b_neonatal_death"
		replace _LABELS = "Preterm delivery" if _LABELS=="c_preterm"
		replace _LABELS = "Post-term delivery" if _LABELS=="d_postterm"
		replace _LABELS = "Small for gestational age" if _LABELS=="e_sga"
		replace _LABELS = "Large for gestational age" if _LABELS=="f_lga"
		replace _LABELS = "Apgar score < 7 at 5 minutes" if _LABELS=="g_apar5_bin"
		
		replace _LABELS = "Norway" if _STUDY==1 | _STUDY==3 | _STUDY==5 | _STUDY==7 | _STUDY==9 | _STUDY==11 | _STUDY==13
		replace _LABELS = "Sweden" if _STUDY==2 | _STUDY==4 | _STUDY==6 | _STUDY==8 | _STUDY==10 | _STUDY==12 | _STUDY==14
		
		replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
		label variable _LABELS `"`"{bf: Birth outcomes}"'"'
		label variable total_exp `"`"{bf: Exposed n/N}"'"'
		label variable total_unexp `"`"{bf: Unexposed n/N}"'"'
		label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
		
		format _ES %4.1fc
		format _WT %4.1fc
		
		*drop if _USE==1
		drop if _USE==3 & _BY==1
		
		gen country=1 if _LABELS=="UK"
		replace country=2 if _LABELS=="Norway"
		replace country=3 if _LABELS=="Sweden"

	forestplot, eform effect("{bf}Odds ratio") lcols(total_exp total_unexp) null(1) olineopts(lcolor(none)) nlineopts(lcolor(cranberry) lpattern(dash)) xlabel(0.5(0.5)2.5) title("{bf}Paternal negative control analysis", size(small)) ///
	plotid(country, list) point1opts(msymbol(circle) msize(0.75)) point2opts(msymbol(diamond) msize(0.75)) textsize(95) ///
	name(pat_ma, replace)
	
	cd "$Graphdir"
	graph export pat_ma.pdf, replace
	
	egen seq=seq()
	drop if seq>32
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	replace _ES = exp(_ES)
	replace _LCI = exp(_LCI)
	replace _UCI = exp(_UCI) 
	
	replace _ES=10 if _ES==.
	replace _LCI=10 if _LCI==.
	replace _UCI=10 if _UCI==.
	
	
	forvalues x=2/32 {
		foreach y in _ES _LCI _UCI {
		
			sum `y' if seq==`x'
			local `y'_`x' = `r(mean)'
			local `y'_`x'_f : display %4.2fc ``y'_`x'' 
			
		}		
	}
	
	replace _ES=. if _ES==10
	replace _LCI=. if _LCI==10
	replace _UCI=. if _UCI==10
	
	forvalues x=2/32 {
	
		local total_exp_`x' = total_exp[`x']
		di "`total_exp_`x''"
		
	}
	
	forvalues x=2/32 {
	
		local total_unexp_`x' = total_unexp[`x']
		di "`total_unexp_`x''"
		
	}
	
	forvalues x=2/32 {
	
		local _LABELS`x' = _LABELS[`x']
		di "`_LABELS`x''"
		
	}
	
	replace _WT=10 if _WT==.
	
	forvalues x=2/32 {
	
		sum _WT if seq==`x'
		local WT_`x' = `r(mean)'
		local WT_`x'_f : display %4.1fc `WT_`x''
		disp "`WT_`x'_f'"
		
	}
	
	replace _WT=. if _WT==10
	
	* Macros to create the null line
	local t1=0
	local t2=33
	
	tw ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap _LCI _UCI seq, horizontal lcolor(black) mlw(thin) msize(*0.5)) ///
	(rcap _LCI _UCI seq if _USE==3, horizontal lcolor(cranberry) mlw(thin) msize(*0.5)) ///
	(scatter seq _ES if _LABELS=="Norway", mcolor("217 142 98") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Sweden", mcolor("168 210 218") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _USE==3, mcolor(cranberry) ms(d) msize(small) mcolor(white) mlcolor(cranberry) mlw(thin)), ///
	yscale(range(-1.5 33) reverse noline) ylab("", angle(0) labsize(*0.6) notick nogrid nogextend) /// 
	legend(order(4 "Norway" 5 "Sweden" 6 "Overall") col(1) region(lcolor(black)) pos(5) size(*0.75)) ///
	yline(-2) yline(0) yline(3, lcolor(gray) lpattern(dot)) yline(8, lcolor(gray) lpattern(dot)) yline(13, lcolor(gray) lpattern(dot)) yline(18, lcolor(gray) lpattern(dot)) yline(23, lcolor(gray) lpattern(dot)) yline(28, lcolor(gray) lpattern(dot)) ///
	xscale(range(0.1 5.7) log) xlab(0.4(0.2)2.9, labsize(*0.4) format(%3.1fc) angle(45))  ///
	graphregion(color(white) fcolor(white) ifcolor(white) lcolor(white)) plotregion(margin(1 1 0 1)) ///
	title("{bf}Fixed-effect meta-analysis of paternal antidepressant use" "{bf}during pregnancy and birth outcomes in the Norway & Sweden", size(*0.5)) ///
	text(-1 2.9 "{bf}aOR* (95% CI)", size(*0.35) justification(left) placement(e)) ///
	text(-1 4.4 "{bf}Weight (%)", size(*0.35) justification(left) placement(e)) ///
	text(-1 0.1 "{bf}Outcome" "	Country", size(*0.35) justification(left) placement(e)) ///
	text(-1 0.21 "{bf}Exposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(-1 0.39 "{bf}Unexposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(1 0.1 "{bf:Stillborn}", size(*0.35) justification(left) placement(e)) ///
		text(2 0.11 "`_LABELS2'", size(*0.35) justification(left) placement(e)) ///
	text(2 0.21 "`total_exp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 0.39 "`total_unexp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 2.9 "`_ES_2_f' (`_LCI_2_f' – `_UCI_2_f')", size(*0.35) justification(left) placement(e)) ///
	text(2 5.5 "`WT_2_f'", size(*0.35) justification(right) placement(w)) ///
	text(4 0.1 "{bf:Neonatal death}", size(*0.35) justification(left) placement(e)) ///
		text(5 0.11 "`_LABELS5'", size(*0.35) justification(left) placement(e)) ///
	text(5 0.21 "`total_exp_5'", size(*0.35) justification(right) placement(w)) ///
	text(5 0.39 "`total_unexp_5'", size(*0.35) justification(right) placement(w)) ///
	text(5 2.9 "`_ES_5_f' (`_LCI_5_f' – `_UCI_5_f')", size(*0.35) justification(left) placement(e)) ///
	text(5 5.5 "`WT_5_f'", size(*0.35) justification(right) placement(w)) ///
		text(6 0.11 "`_LABELS6'", size(*0.35) justification(left) placement(e)) ///
	text(6 0.21 "`total_exp_6'", size(*0.35) justification(right) placement(w)) ///
	text(6 0.39 "`total_unexp_6'", size(*0.35) justification(right) placement(w)) ///
	text(6 2.9 "`_ES_6_f' (`_LCI_6_f' – `_UCI_6_f')", size(*0.35) justification(left) placement(e)) ///
	text(6 5.5 "`WT_6_f'", size(*0.35) justification(right) placement(w)) ///
		text(7 0.1 "`_LABELS7'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(7 2.9 "`_ES_7_f' (`_LCI_7_f' – `_UCI_7_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(7 5.5 "`WT_7_f'", size(*0.35) justification(right) placement(w)) ///
	text(9 0.1 "{bf:Preterm delivery}", size(*0.35) justification(left) placement(e)) ///
		text(10 0.11 "`_LABELS10'", size(*0.35) justification(left) placement(e)) ///
	text(10 0.21 "`total_exp_10'", size(*0.35) justification(right) placement(w)) ///
	text(10 0.39 "`total_unexp_10'", size(*0.35) justification(right) placement(w)) ///
	text(10 2.9 "`_ES_10_f' (`_LCI_10_f' – `_UCI_10_f')", size(*0.35) justification(left) placement(e)) ///
	text(10 5.5 "`WT_10_f'", size(*0.35) justification(right) placement(w)) ///
		text(11 0.11 "`_LABELS11'", size(*0.35) justification(left) placement(e)) ///
	text(11 0.21 "`total_exp_11'", size(*0.35) justification(right) placement(w)) ///
	text(11 0.39 "`total_unexp_11'", size(*0.35) justification(right) placement(w)) ///
	text(11 2.9 "`_ES_11_f' (`_LCI_11_f' – `_UCI_11_f')", size(*0.35) justification(left) placement(e)) ///
	text(11 5.5 "`WT_11_f'", size(*0.35) justification(right) placement(w)) ///
		text(12 0.1 "`_LABELS12'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(12 2.9 "`_ES_12_f' (`_LCI_12_f' – `_UCI_12_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(12 5.5 "`WT_12_f'", size(*0.35) justification(right) placement(w)) ///
	text(14 0.1 "{bf:Post-term delivery}", size(*0.35) justification(left) placement(e)) ///
		text(15 0.11 "`_LABELS15'", size(*0.35) justification(left) placement(e)) ///
	text(15 0.21 "`total_exp_15'", size(*0.35) justification(right) placement(w)) ///
	text(15 0.39 "`total_unexp_15'", size(*0.35) justification(right) placement(w)) ///
	text(15 2.9 "`_ES_15_f' (`_LCI_15_f' – `_UCI_15_f')", size(*0.35) justification(left) placement(e)) ///
	text(15 5.5 "`WT_15_f'", size(*0.35) justification(right) placement(w)) ///
		text(16 0.11 "`_LABELS16'", size(*0.35) justification(left) placement(e)) ///
	text(16 0.21 "`total_exp_16'", size(*0.35) justification(right) placement(w)) ///
	text(16 0.39 "`total_unexp_16'", size(*0.35) justification(right) placement(w)) ///
	text(16 2.9 "`_ES_16_f' (`_LCI_16_f' – `_UCI_16_f')", size(*0.35) justification(left) placement(e)) ///
	text(16 5.5 "`WT_16_f'", size(*0.35) justification(right) placement(w)) ///
		text(17 0.1 "`_LABELS17'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(17 2.9 "`_ES_17_f' (`_LCI_17_f' – `_UCI_17_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(17 5.5 "`WT_17_f'", size(*0.35) justification(right) placement(w)) ///
	text(19 0.1 "{bf:Small for gestational age}", size(*0.35) justification(left) placement(e)) ///
		text(20 0.11 "`_LABELS20'", size(*0.35) justification(left) placement(e)) ///
	text(20 0.21 "`total_exp_20'", size(*0.35) justification(right) placement(w)) ///
	text(20 0.39 "`total_unexp_20'", size(*0.35) justification(right) placement(w)) ///
	text(20 5.5 "`WT_20_f'", size(*0.35) justification(right) placement(w)) ///
	text(20 2.9 "`_ES_20_f' (`_LCI_20_f' – `_UCI_20_f')", size(*0.35) justification(left) placement(e)) ///
		text(21 0.11 "`_LABEL21'", size(*0.35) justification(left) placement(e)) ///
	text(21 0.21 "`total_exp_21'", size(*0.35) justification(right) placement(w)) ///
	text(21 0.39 "`total_unexp_21'", size(*0.35) justification(right) placement(w)) ///
	text(21 2.9 "`_ES_21_f' (`_LCI_21_f' – `_UCI_21_f')", size(*0.35) justification(left) placement(e)) ///
	text(21 5.5 "`WT_21_f'", size(*0.35) justification(right) placement(w)) ///
		text(22 0.1 "`_LABELS22'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(22 2.9 "`_ES_22_f' (`_LCI_19_f' – `_UCI_19_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(22 5.5 "`WT_22_f'", size(*0.35) justification(right) placement(w)) ///
	text(24 0.1 "{bf:Large for gestational age}", size(*0.35) justification(left) placement(e)) ///
		text(25 0.11 "`_LABELS25'", size(*0.35) justification(left) placement(e)) ///
	text(25 0.21 "`total_exp_25'", size(*0.35) justification(right) placement(w)) ///
	text(25 0.39 "`total_unexp_25'", size(*0.35) justification(right) placement(w)) ///
	text(25 2.9 "`_ES_25_f' (`_LCI_25_f' – `_UCI_25_f')", size(*0.35) justification(left) placement(e)) ///
	text(25 5.5 "`WT_25_f'", size(*0.35) justification(right) placement(w)) ///
		text(26 0.11 "`_LABELS26'", size(*0.35) justification(left) placement(e)) ///
	text(26 0.21 "`total_exp_26'", size(*0.35) justification(right) placement(w)) ///
	text(26 0.39 "`total_unexp_26'", size(*0.35) justification(right) placement(w)) ///
	text(26 2.9 "`_ES_26_f' (`_LCI_26_f' – `_UCI_26_f')", size(*0.35) justification(left) placement(e)) ///
	text(26 5.5 "`WT_26_f'", size(*0.35) justification(right) placement(w)) ///
		text(27 0.1 "`_LABELS27'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(27 2.9 "`_ES_27_f' (`_LCI_27_f' – `_UCI_27_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(27 5.5 "`WT_27_f'", size(*0.35) justification(right) placement(w)) ///
	text(29 0.1 "{bf:Low Apgar score}", size(*0.35) justification(left) placement(e)) ///
		text(30 0.11 "`_LABELS30'", size(*0.35) justification(left) placement(e)) ///
	text(30 0.21 "`total_exp_30'", size(*0.35) justification(right) placement(w)) ///
	text(30 0.39 "`total_unexp_30'", size(*0.35) justification(right) placement(w)) ///
	text(30 2.9 "`_ES_30_f' (`_LCI_30_f' – `_UCI_30_f')", size(*0.35) justification(left) placement(e)) ///
	text(30 5.5 "`WT_30_f'", size(*0.35) justification(right) placement(w)) ///
		text(31 0.11 "`_LABELS31'", size(*0.35) justification(left) placement(e)) ///
	text(31 0.21 "`total_exp_31'", size(*0.35) justification(right) placement(w)) ///
	text(31 0.39 "`total_unexp_31'", size(*0.35) justification(right) placement(w)) ///
	text(31 2.9 "`_ES_31_f' (`_LCI_31_f' – `_UCI_31_f')", size(*0.35) justification(left) placement(e)) ///
	text(31 5.5 "`WT_31_f'", size(*0.35) justification(right) placement(w)) ///
		text(32 0.1 "`_LABELS32'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(32 2.9 "`_ES_32_f' (`_LCI_32_f' – `_UCI_32_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(32 5.5 "`WT_32_f'", size(*0.35) justification(right) placement(w)) ///
	text(36 1.2 "{bf:Odds ratio* (95% confidence interval)}" "from logistic regression", size(*0.45)) ///
	text(37.15 1.2 "from fixed effects meta-analysis", size(*0.45) color(cranberry)) ///
	text(36.5 0.1 "*Adjusted for year of birth, maternal age," "previous stillbirth, parity, antipsychotic and" "anti-seizure medication use before pregnancy," "maternal and paternal depression, maternal and" "paternal anxiety, maternal and paternal educational" "attainment, country of birth, household disposable" "income (Sweden), smoking during pregnancy" "(Sweden), maternal BMI (Sweden), number of" "primary care consultations before pregnancy" "(Norway)", size(*0.35) justification(left) placement(e)) ///
	xsize(90) ysize(100) name(pat, replace)
	
	* Save graph
	
	graph export "C:\Users\ti19522\OneDrive - University of Bristol\Flo Martin Supervisory Team\Year 4\6_Birth outcomes\supplementary figures\pat_ma.pdf", replace
	
********************************************************************************

* Use the summary effect estimates from metan to make the primary figure		
	
	use mat_ma, clear
	
	gen or_mat=exp(_ES)
	gen lci_mat=exp(_LCI)
	gen uci_mat=exp(_UCI)
	
	keep _BY _USE _STUDY *_mat
	
	merge 1:1 _BY _USE _STUDY using sib_ma, nogen
	
	gen or_sib=exp(_ES)
	gen lci_sib=exp(_LCI)
	gen uci_sib=exp(_UCI)
	
	keep _BY _USE _STUDY *_mat *_sib
	
	merge 1:1 _BY _USE _STUDY using pat_ma, nogen
	
	gen or_pat=exp(_ES)
	gen lci_pat=exp(_LCI)
	gen uci_pat=exp(_UCI)
	
	keep if _USE==3 
	keep _BY _USE _STUDY *_mat *_sib *_pat
	
	*egen row_sib = seq()
	*gen row_mat = row_sib-0.3
	*gen row_pat = row_sib+0.3
	
	gen x=2.2
	gen y=0
	
	replace or_pat=. if _BY==1
	replace lci_pat=. if _BY==1
	replace uci_pat=. if _BY==1
	
	gen outcome=""
	replace outcome="stillborn" if _BY==1
	replace outcome="neonatal_death" if _BY==2
	replace outcome="preterm" if _BY==3
	replace outcome="postterm" if _BY==4
	replace outcome="sga" if _BY==5
	replace outcome="lga" if _BY==6
	replace outcome="apgar5_bin" if _BY==7
	
	cd "$Graphdir"
	save primary_fig_data, replace
	
	use primary_fig_data, clear
	
	* Macros for the OR text
	foreach country in mat sib pat {
		foreach outcome in neonatal_death preterm postterm sga lga apgar5_bin {
			
			sum or_`country' if outcome=="`outcome'"
			local `outcome'_`country'_or = `r(mean)'
			sum uci_`country' if outcome=="`outcome'"
			local `outcome'_`country'_uci = `r(mean)'
			
			local `outcome'_`country'_or_fmt: display %3.2f ``outcome'_`country'_or'
			
			if ``outcome'_`country'_uci'<1.15 & ``outcome'_`country'_uci'>=0.95 {
			
				local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.12
			
			}
			
			else if ``outcome'_`country'_uci'<0.95 {
			
				local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.09
			
			}
		
			else {
		
			local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.18
			
			}
			
		}
	}
	
	foreach country in mat sib {
		foreach outcome in stillborn {
			
			sum or_`country' if outcome=="`outcome'"
			local `outcome'_`country'_or = `r(mean)'
			sum uci_`country' if outcome=="`outcome'"
			local `outcome'_`country'_uci = `r(mean)'
			
			local `outcome'_`country'_or_fmt: display %3.2f ``outcome'_`country'_or'
			
			if ``outcome'_`country'_uci'<1.15 {
			
				local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.1
			
			}
			
			else if ``outcome'_`country'_uci'>2 {
			
				local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.2
			
			}
		
			else {
		
			local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.15
			
			}
			
		}
	}
	
	egen row_mat=seq()
	egen row_sib=seq()
	egen row_pat=seq()
	
	* Macros to create the null line
	local t1=0.5
	local t2=7.5
	
	twoway ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap lci_mat uci_mat row_mat, horiz lcolor(black)) ///
	(scatter row_mat or_mat, msymbol(S) mfcolor("85 119 135") mlwidth(medthin)), ///
	xlabel(0.5(0.25)2.5, labsize(vsmall) format(%3.1f) nogrid) ///
	yline(1, lwidth(13) lc(gs12*0.5)) yline(3, lwidth(13) lc(gs12*0.5)) yline(5, lwidth(13) lc(gs12*0.5)) yline(7, lwidth(13) lc(gs12*0.5)) /// grey banding
	yscale(reverse range(0.5 7.5)) ylabel(1 "{bf:Stillbirth}" 2 `" "{bf:Neonatal death}" "(Norway and Sweden only)" "' 3 "{bf}Preterm delivery" 4 "{bf}Post-term delivery" 5 "{bf}Small for gestational age" 6 "{bf}Large for gestational age" 7 `" "{bf:Apgar < 7 at 5 mins}" "(Norway and Sweden only)" "', angle(0) notick labsize(vsmall) nogrid nogextend) ytitle("") ///
	xscale(log range(0.5 2.6)) xtitle("{bf:Adjusted pooled odds ratio (95% CI)}", size(vsmall) color(black)) ///
	legend(row(3) order(3 "Summary effect estimate") pos(6) size(vsmall)) || /// legend
	scatter y x, msymbol(i) yaxis(2) xaxis(2) ///
	yscale(range(0.5 7.5)) ylab(, axis(2) notick nolab) xlab(, axis(2) notick nolab) ytitle("", axis(2)) xtitle("", axis(2)) /// box around plot
	graphregion(color(white)) plotregion(margin(zero)) title("{bf}Maternal antidepressant use" "{bf}during pregnancy", size(vsmall)) ///
	text(1 `stillborn_mat_pos' "{bf}`stillborn_mat_or_fmt'", size(vsmall)) /// OR text for stillbirth
	text(2 `neonatal_death_mat_pos' "{bf}`neonatal_death_mat_or_fmt'", size(vsmall)) /// OR text for neonatal death
	text(3 `preterm_mat_pos' "{bf}`preterm_mat_or_fmt'", size(vsmall)) /// OR text for preterm delivery
	text(4 `postterm_mat_pos' "{bf}`postterm_mat_or_fmt'", size(vsmall)) /// OR text for postterm delivery
	text(5 `sga_mat_pos' "{bf}`sga_mat_or_fmt'", size(vsmall)) /// OR text for SGA
	text(6 `lga_mat_pos' "{bf}`lga_mat_or_fmt'", size(vsmall)) /// OR text for LGA
	text(7 `apgar5_bin_mat_pos' "{bf}`apgar5_bin_mat_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	fxsize(125) fysize(100) name(mat_ma, replace)
	
	twoway ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap lci_sib uci_sib row_sib, horiz lcolor(black)) ///
	(scatter row_sib or_sib, msymbol(S) mfcolor("217 142 98") mlwidth(medthin)), ///
	xlabel(0.5(0.25)2.5, labsize(vsmall) format(%3.1f) nogrid) ///
	yline(1, lwidth(13) lc(gs12*0.5)) yline(3, lwidth(13) lc(gs12*0.5)) yline(5, lwidth(13) lc(gs12*0.5)) yline(7, lwidth(13) lc(gs12*0.5)) /// grey banding
	yscale(reverse range(0.5 7.5)) ylabel(1 "" 7 "", angle(0) notick nogrid nogextend labcolor(white)) ytitle("") ///
	xscale(log range(0.5 2.6)) xtitle("{bf:Adjusted pooled odds ratio (95% CI)}", size(vsmall) color(black)) ///
	legend(row(3) order(3 "Summary effect estimate") pos(6) size(vsmall)) || /// legend
	scatter y x, msymbol(i) yaxis(2) xaxis(2) ///
	yscale(range(0.5 7.5)) ylab(, axis(2) notick nolab) xlab(, axis(2) notick nolab) ytitle("", axis(2)) xtitle("", axis(2)) /// box around plot
	graphregion(color(white)) plotregion(margin(zero)) title("{bf}Maternal antidepressant use during pregnancy" "{bf}among discordant siblings", size(vsmall)) ///
	text(1 `stillborn_sib_pos' "{bf}`stillborn_sib_or_fmt'", size(vsmall)) /// OR text for stillbirth
	text(2 `neonatal_death_sib_pos' "{bf}`neonatal_death_sib_or_fmt'", size(vsmall)) /// OR text for neonatal death
	text(3 `preterm_sib_pos' "{bf}`preterm_sib_or_fmt'", size(vsmall)) /// OR text for preterm delivery
	text(4 `postterm_sib_pos' "{bf}`postterm_sib_or_fmt'", size(vsmall)) /// OR text for postterm delivery
	text(5 `sga_sib_pos' "{bf}`sga_sib_or_fmt'", size(vsmall)) /// OR text for SGA
	text(6 `lga_sib_pos' "{bf}`lga_sib_or_fmt'", size(vsmall)) /// OR text for LGA
	text(7 `apgar5_bin_sib_pos' "{bf}`apgar5_bin_sib_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	fxsize(85) fysize(100) name(sib_ma, replace)
	
	twoway ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap lci_pat uci_pat row_pat, horiz lcolor(black)) ///
	(scatter row_pat or_pat, msymbol(S) mfcolor("168 210 218") mlwidth(medthin)), ///
	xlabel(0.5(0.25)2.5, labsize(vsmall) format(%3.1f) nogrid) ///
	yline(1, lwidth(13) lc(gs12*0.5)) yline(3, lwidth(13) lc(gs12*0.5)) yline(5, lwidth(13) lc(gs12*0.5)) yline(7, lwidth(13) lc(gs12*0.5)) /// grey banding
	yscale(reverse range(0.5 7.5)) ylabel(1 "" 7 "", angle(0) notick nogrid nogextend labcolor(white)) ytitle("") ///
	xscale(log range(0.5 2.6)) xtitle("{bf:Adjusted pooled odds ratio (95% CI)}", size(vsmall) color(black)) ///
	legend(row(3) order(3 "Summary effect estimate (Norway & Sweden)") pos(6) size(vsmall)) || /// legend
	scatter y x, msymbol(i) yaxis(2) xaxis(2) ///
	yscale(range(0.5 7.5)) ylab(, axis(2) notick nolab) xlab(, axis(2) notick nolab) ytitle("", axis(2)) xtitle("", axis(2)) /// box around plot
	graphregion(color(white)) plotregion(margin(zero)) title("{bf}Paternal antidepressant use" "{bf}during pregnancy", size(vsmall)) ///
	text(2 `neonatal_death_pat_pos' "{bf}`neonatal_death_pat_or_fmt'", size(vsmall)) /// OR text for neonatal death
	text(3 `preterm_pat_pos' "{bf}`preterm_pat_or_fmt'", size(vsmall)) /// OR text for preterm delivery
	text(4 `postterm_pat_pos' "{bf}`postterm_pat_or_fmt'", size(vsmall)) /// OR text for postterm delivery
	text(5 `sga_pat_pos' "{bf}`sga_pat_or_fmt'", size(vsmall)) /// OR text for SGA
	text(6 `lga_pat_pos' "{bf}`lga_pat_or_fmt'", size(vsmall)) /// OR text for LGA
	text(7 `apgar5_bin_pat_pos' "{bf}`apgar5_bin_pat_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	fxsize(85) fysize(100) name(pat_ma, replace)
	
	graph combine mat_ma sib_ma pat_ma, title("{bf}Meta-analysis of each triangulation method in UK, Norway, & Sweden", size(small)) col(3) name(fixed_ma_primary, replace)
	
	cd "$Graphdir"
	graph export primary_ma_mydesign.pdf, replace
	
********************************************************************************

* OR

	use mat_ma, clear
	gen model=1
	drop if _USE==0 | _USE==6
	
	append using sib_ma
	replace model=2 if model==.
	drop if _USE==0 | _USE==6
	
	append using pat_ma
	replace model=3 if model==.
	
	label define model_lb 1"maternal" 2"sibling" 3"paternal"
	label values model model_lb
	
	split total_exp, parse(" /") gen(exp_y)
	rename exp_y1 exp_y
	rename exp_y2 exp_total
	
	split total_unexp, parse(" /") gen(unexp_y)
	rename unexp_y1 unexp_y
	rename unexp_y2 unexp_total
	
	foreach x in exp_y exp_total unexp_y unexp_total {
	
		replace `x' = subinstr(`x', ",", "", .)
		gen `x'_num=real(`x')
		drop `x'
		rename `x'_num `x'
	
	}
	
	foreach x in exp_y exp_total unexp_y unexp_total {
	
		bysort _BY model: egen sum_`x'=total(`x')
		format sum_`x' %9.0fc
		
	}
	
	forvalues x=1/7 {
		forvalues y=1/3 {
		
			sum sum_exp_y if _BY==`x' & model==`y'
			local sum_exp_y = `r(max)'
			local sum_exp_y_fc : display %6.0fc `sum_exp_y'
			
			sum sum_exp_total if _BY==`x' & model==`y'
			local sum_exp_total = `r(max)'
			local sum_exp_total_fc : display %7.0fc `sum_exp_total'
			
			sum sum_unexp_y if _BY==`x' & model==`y'
			local sum_unexp_y = `r(max)'
			local sum_unexp_y_fc : display %7.0fc `sum_unexp_y'
			
			sum sum_unexp_total if _BY==`x' & model==`y'
			local sum_unexp_total = `r(max)'
			local sum_unexp_total_fc : display %9.0fc `sum_unexp_total'
			
			replace total_exp = "`sum_exp_y_fc' / `sum_exp_total_fc'" if _BY==`x' & _USE==3  & model==`y'
			replace total_unexp = "`sum_unexp_y_fc' / `sum_unexp_total_fc'" if _BY==`x' & _USE==3  & model==`y'
		
		}
	}
	
	replace total_exp = subinstr(total_exp, " ", "", .)
	replace total_unexp = subinstr(total_unexp, " ", "", .)
	
	replace total_exp = subinstr(total_exp, "/", " / ", .)
	replace total_unexp = subinstr(total_unexp, "/", " / ", .)
	
	keep if _USE!=1 & _USE!=4 & _USE!=5
	drop _STUDY
	sort _BY _USE model
	
	bys _BY _USE: egen grp_wt = sum(_WT)
	gen pct_grp_wt = 100 * _WT / grp_wt
		
	drop _WT
	rename pct_grp_wt _WT
	format _WT %4.2fc
	
	replace _LABELS="Maternal analysis" if model==1 & _USE==3
	replace _LABELS="Discordant sibling analysis" if model==2 & _USE==3
	replace _LABELS="Paternal negative control analysis" if model==3 & _USE==3
	
	replace _LABELS = "Stillborn" if _LABELS=="a_stillborn"
	replace _LABELS = "Neonatal death" if _LABELS=="b_neonatal_death"
	replace _LABELS = "Preterm delivery" if _LABELS=="c_preterm"
	replace _LABELS = "Post-term delivery" if _LABELS=="d_postterm"
	replace _LABELS = "Small for gestational age" if _LABELS=="e_sga"
	replace _LABELS = "Large for gestational age" if _LABELS=="f_lga"
	replace _LABELS = "Apgar score < 7 at 5 minutes" if _LABELS=="g_apar5_bin"
	
	drop if _BY==1 & model==3 & _ES!=.
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	label variable total_unexp `"`"{bf:Pooled}"' `"{bf}unexposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	forestplot, eform lcols(total_exp total_unexp) nowt effect("{bf}Odds ratio") null(1) olineopts(lcolor(none)) nlineopts(lcolor(cranberry) lpattern(dash)) xlabel(0.6(0.2)2, format(%3.1fc)) title("{bf}Maternal analysis, discordant sibling analysis & paternal negative control analysis", size(small)) spacing(2) noadjust ///
		name(primary_ma, replace)
		
	cd "$Graphdir"
	graph export primary_ma_forestdesign.pdf, replace 
	
* Combination - thesis figure

	use mat_ma, clear
	gen model=1
	drop if _USE==0 | _USE==6
	
	append using sib_ma
	replace model=2 if model==.
	drop if _USE==0 | _USE==6
	
	append using pat_ma
	replace model=3 if model==.
	
	label define model_lb 1"maternal" 2"sibling" 3"paternal"
	label values model model_lb
	
	split total_exp, parse(" /") gen(exp_y)
	rename exp_y1 exp_y
	rename exp_y2 exp_total
	
	split total_unexp, parse(" /") gen(unexp_y)
	rename unexp_y1 unexp_y
	rename unexp_y2 unexp_total
	
	foreach x in exp_y exp_total unexp_y unexp_total {
	
		replace `x' = subinstr(`x', ",", "", .)
		gen `x'_num=real(`x')
		drop `x'
		rename `x'_num `x'
	
	}
	
	foreach x in exp_y exp_total unexp_y unexp_total {
	
		bysort _BY model: egen sum_`x'=total(`x')
		format sum_`x' %9.0fc
		
	}
	
	forvalues x=1/7 {
		forvalues y=1/3 {
		
			sum sum_exp_y if _BY==`x' & model==`y'
			local sum_exp_y = `r(max)'
			local sum_exp_y_fc : display %6.0fc `sum_exp_y'
			
			sum sum_exp_total if _BY==`x' & model==`y'
			local sum_exp_total = `r(max)'
			local sum_exp_total_fc : display %7.0fc `sum_exp_total'
			
			sum sum_unexp_y if _BY==`x' & model==`y'
			local sum_unexp_y = `r(max)'
			local sum_unexp_y_fc : display %7.0fc `sum_unexp_y'
			
			sum sum_unexp_total if _BY==`x' & model==`y'
			local sum_unexp_total = `r(max)'
			local sum_unexp_total_fc : display %9.0fc `sum_unexp_total'
			
			replace total_exp = "`sum_exp_y_fc' / `sum_exp_total_fc'" if _BY==`x' & _USE==3  & model==`y'
			replace total_unexp = "`sum_unexp_y_fc' / `sum_unexp_total_fc'" if _BY==`x' & _USE==3  & model==`y'
		
		}
	}
	
	replace total_exp = subinstr(total_exp, " ", "", .)
	replace total_unexp = subinstr(total_unexp, " ", "", .)
	
	replace total_exp = subinstr(total_exp, "/", " / ", .)
	replace total_unexp = subinstr(total_unexp, "/", " / ", .)
	
	keep if _USE!=1 & _USE!=4 & _USE!=5
	drop _STUDY
	sort _BY _USE model
	
	bys _BY _USE: egen grp_wt = sum(_WT)
	gen pct_grp_wt = 100 * _WT / grp_wt
		
	drop _WT
	rename pct_grp_wt _WT
	format _WT %4.2fc
	
	replace _LABELS="Maternal analysis" if model==1 & _USE==3
	replace _LABELS="Discordant sibling analysis" if model==2 & _USE==3
	replace _LABELS="Paternal negative control analysis" if model==3 & _USE==3
	
	replace _LABELS = "Stillborn" if _LABELS=="a_stillborn"
	replace _LABELS = "Neonatal death" if _LABELS=="b_neonatal_death"
	replace _LABELS = "Preterm delivery" if _LABELS=="c_preterm"
	replace _LABELS = "Post-term delivery" if _LABELS=="d_postterm"
	replace _LABELS = "Small for gestational age" if _LABELS=="e_sga"
	replace _LABELS = "Large for gestational age" if _LABELS=="f_lga"
	replace _LABELS = "Apgar score < 7 at 5 minutes" if _LABELS=="g_apar5_bin"
	
	drop if _BY==1 & model==3 & _ES!=.
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	label variable total_unexp `"`"{bf:Pooled}"' `"{bf}unexposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	replace _ES = exp(_ES)
	replace _LCI = exp(_LCI)
	replace _UCI = exp(_UCI)
	
	replace _ES=10 if _ES==.
	replace _LCI=10 if _LCI==.
	replace _UCI=10 if _UCI==.
	
	egen seq=seq()
	
	forvalues x=2/33 {
		foreach y in _ES _LCI _UCI {
		
			sum `y' if seq==`x'
			local `y'_`x' = `r(mean)'
			local `y'_`x'_f : display %4.2fc ``y'_`x'' 
			
		}		
	}
	
	replace _ES=. if _ES==10
	replace _LCI=. if _LCI==10
	replace _UCI=. if _UCI==10
	
	forvalues x=2/33 {
	
		local total_exp_`x' = total_exp[`x']
		di "`total_exp_`x''"
		
		local total_unexp_`x' = total_unexp[`x']
		di "`total_unexp_`x''"
		
	}
	
	* Macros to create the null line
	local t1=0
	local t2=34

	twoway ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap _LCI _UCI seq, horizontal lcolor(black) msize(*0.5)) /// code for NO 95% CI
	(scatter seq _ES if _LABELS=="Maternal analysis", mcolor("114 24 23") ms(d) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Discordant sibling analysis", mcolor("250 159 66") ms(d) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Paternal negative control analysis", mcolor("43 65 98") ms(d) msize(small) mlcolor(black) mlw(thin)), yscale(reverse) yscale(range(-2.5 34)) ///
	ylab("", angle(0) labsize(*0.6) notick nogrid nogextend) ///
	yline(-3) yline(0) yline(4, lcolor(gray) lpattern(dot)) yline(9, lcolor(gray) lpattern(dot)) yline(14, lcolor(gray) lpattern(dot)) yline(19, lcolor(gray) lpattern(dot)) yline(24, lcolor(gray) lpattern(dot)) yline(29, lcolor(gray) lpattern(dot)) ///
	title("{bf}Pooled odds ratios for antidepressant use during pregnancy" "{bf}and birth outcomes in the UK, Norway, & Sweden", size(*0.5)) ///
	text(-1.5 2.9 "{bf}aOR (95% CI)", size(*0.45) justification(left) placement(e)) ///
	text(-1.5 0.025 "{bf}Birth outcome" "Analytical approach", size(*0.45) justification(left) placement(e)) ///
	text(-1.5 0.16 "{bf}Pooled" "{bf:exposed} n / N", size(*0.45) justification(right) placement(w)) ///
	text(-1.5 0.39 "{bf}Pooled" "{bf:unexposed} n / N", size(*0.45) justification(right) placement(w)) ///
	text(36.75 0.025 "*Adjusted for year of birth, maternal age, previous stillbirth, parity," "antipsychotic and anti-seizure medication use before pregnancy," "depression, anxiety, practice-level IMD and ethnicity (UK), maternal" "educational attainment and country of birth (Norway and Sweden)," "household disposable income (Sweden), smoking during pregnancy" "(UK and Sweden), maternal BMI (Sweden), number of primary care" "consultations before pregnancy (UK and Norway)", size(*0.35) justification(left) placement(e)) ///
	text(40.16 0.025 "{sup:†}Adjusted for the same as the maternal analysis*, except history of" "stillbirth, as family averages minus each sibling's value to account for" "non-shared confounding between siblings", size(*0.35) justification(left) placement(e)) ///
	text(41.75 0.025 "{sup:‡}Norway and Sweden only", size(*0.35) justification(left) placement(e)) /// 
	text(43 0.025 "{sup:§}Adjusted for the same as the maternal analysis* plus paternal education," "depression, and anxiety", size(*0.35) justification(left) placement(e)) ///
	text(37 1 "{bf:Pooled aOR (95% CI)}" "from fixed effects meta-analysis", size(*0.4)) ///
		text(1 0.025 "{bf:Stillborn}", size(*0.45) justification(left) placement(e)) ///
		text(2 0.025 "Maternal analysis*", size(*0.45) justification(left) placement(e)) ///
	text(2 0.16 "`total_exp_2'", size(*0.45) justification(right) placement(w)) ///
	text(2 0.39 "`total_unexp_2'", size(*0.45) justification(right) placement(w)) ///
	text(2 2.9 "`_ES_2_f' (`_LCI_2_f' – `_UCI_2_f')", size(*0.45) justification(left) placement(e)) ///
		text(3 0.025 "Discordant sibling analysis{sup:†}", size(*0.45) justification(left) placement(e)) ///
	text(3 0.16 "`total_exp_3'", size(*0.45) justification(right) placement(w)) ///
	text(3 0.39 "`total_unexp_3'", size(*0.45) justification(right) placement(w)) ///
	text(3 2.9 "`_ES_3_f' (`_LCI_3_f' – `_UCI_3_f')", size(*0.45) justification(left) placement(e)) ///
		text(5 0.025 "{bf:Neonatal death{sup:‡}}", size(*0.45) justification(left) placement(e)) ///
		text(6 0.025 "Maternal analysis*", size(*0.45) justification(left) placement(e)) ///
	text(6 0.16 "`total_exp_6'", size(*0.45) justification(right) placement(w)) ///
	text(6 0.39 "`total_unexp_6'", size(*0.45) justification(right) placement(w)) ///
	text(6 2.9 "`_ES_6_f' (`_LCI_6_f' – `_UCI_6_f')", size(*0.45) justification(left) placement(e)) ///
		text(7 0.025 "Discordant sibling analysis{sup:†}", size(*0.45) justification(left) placement(e)) ///
	text(7 0.16 "`total_exp_7'", size(*0.45) justification(right) placement(w)) ///
	text(7 0.39 "`total_unexp_7'", size(*0.45) justification(right) placement(w)) ///
	text(7 2.9 "`_ES_7_f' (`_LCI_7_f' – `_UCI_7_f')", size(*0.45) justification(left) placement(e)) ///
		text(8 0.025 "Paternal analysis{sup:§}", size(*0.45) justification(left) placement(e)) ///
	text(8 0.16 "`total_exp_8'", size(*0.45) justification(right) placement(w)) ///
	text(8 0.39 "`total_unexp_8'", size(*0.45) justification(right) placement(w)) ///
	text(8 2.9 "`_ES_8_f' (`_LCI_8_f' – `_UCI_8_f')", size(*0.45) justification(left) placement(e)) ///
		text(10 0.025 "{bf:Preterm delivery}", size(*0.45) justification(left) placement(e)) ///
		text(11 0.025 "Maternal analysis*", size(*0.45) justification(left) placement(e)) ///
	text(11 0.16 "`total_exp_11'", size(*0.45) justification(right) placement(w)) ///
	text(11 0.39 "`total_unexp_11'", size(*0.45) justification(right) placement(w)) ///
	text(11 2.9 "`_ES_11_f' (`_LCI_11_f' – `_UCI_11_f')", size(*0.45) justification(left) placement(e)) ///
		text(12 0.025 "Discordant sibling analysis{sup:†}", size(*0.45) justification(left) placement(e)) ///
	text(12 0.16 "`total_exp_12'", size(*0.45) justification(right) placement(w)) ///
	text(12 0.39 "`total_unexp_12'", size(*0.45) justification(right) placement(w)) ///
	text(12 2.9 "`_ES_12_f' (`_LCI_12_f' – `_UCI_12_f')", size(*0.45) justification(left) placement(e)) ///
		text(13 0.025 "Paternal analysis{sup:‡,§}", size(*0.45) justification(left) placement(e)) ///
	text(13 0.16 "`total_exp_13'", size(*0.45) justification(right) placement(w)) ///
	text(13 0.39 "`total_unexp_13'", size(*0.45) justification(right) placement(w)) ///
	text(13 2.9 "`_ES_13_f' (`_LCI_13_f' – `_UCI_13_f')", size(*0.45) justification(left) placement(e)) ///
		text(15 0.025 "{bf:Post-term delivery}", size(*0.45) justification(left) placement(e)) ///
		text(16 0.025 "Maternal analysis*", size(*0.45) justification(left) placement(e)) ///
	text(16 0.16 "`total_exp_16'", size(*0.45) justification(right) placement(w)) ///
	text(16 0.39 "`total_unexp_16'", size(*0.45) justification(right) placement(w)) ///
	text(16 2.9 "`_ES_16_f' (`_LCI_16_f' – `_UCI_16_f')", size(*0.45) justification(left) placement(e)) ///
		text(17 0.025 "Discordant sibling analysis{sup:†}", size(*0.45) justification(left) placement(e)) ///
	text(17 0.16 "`total_exp_17'", size(*0.45) justification(right) placement(w)) ///
	text(17 0.39 "`total_unexp_17'", size(*0.45) justification(right) placement(w)) ///
	text(17 2.9 "`_ES_17_f' (`_LCI_17_f' – `_UCI_17_f')", size(*0.45) justification(left) placement(e)) ///
		text(18 0.025 "Paternal analysis{sup:‡,§}", size(*0.45) justification(left) placement(e)) ///
	text(18 0.16 "`total_exp_18'", size(*0.45) justification(right) placement(w)) ///
	text(18 0.39 "`total_unexp_18'", size(*0.45) justification(right) placement(w)) ///
	text(18 2.9 "`_ES_18_f' (`_LCI_18_f' – `_UCI_18_f')", size(*0.45) justification(left) placement(e)) ///
		text(20 0.025 "{bf:Small for gestational age}", size(*0.45) justification(left) placement(e)) ///
		text(21 0.025 "Maternal analysis*", size(*0.45) justification(left) placement(e)) ///
	text(21 0.16 "`total_exp_21'", size(*0.45) justification(right) placement(w)) ///
	text(21 0.39 "`total_unexp_21'", size(*0.45) justification(right) placement(w)) ///
	text(21 2.9 "`_ES_21_f' (`_LCI_21_f' – `_UCI_21_f')", size(*0.45) justification(left) placement(e)) ///
		text(22 0.025 "Discordant sibling analysis{sup:†}", size(*0.45) justification(left) placement(e)) ///
	text(22 0.16 "`total_exp_22'", size(*0.45) justification(right) placement(w)) ///
	text(22 0.39 "`total_unexp_22'", size(*0.45) justification(right) placement(w)) ///
	text(22 2.9 "`_ES_22_f' (`_LCI_22_f' – `_UCI_22_f')", size(*0.45) justification(left) placement(e)) ///
		text(23 0.025 "Paternal analysis{sup:‡,§}", size(*0.45) justification(left) placement(e)) ///
	text(23 0.16 "`total_exp_23'", size(*0.45) justification(right) placement(w)) ///
	text(23 0.39 "`total_unexp_23'", size(*0.45) justification(right) placement(w)) ///
	text(23 2.9 "`_ES_23_f' (`_LCI_23_f' – `_UCI_23_f')", size(*0.45) justification(left) placement(e)) ///
		text(25 0.025 "{bf:Large for gestational age}", size(*0.45) justification(left) placement(e)) ///
		text(26 0.025 "Maternal analysis*", size(*0.45) justification(left) placement(e)) ///
	text(26 0.16 "`total_exp_26'", size(*0.45) justification(right) placement(w)) ///
	text(26 0.39 "`total_unexp_26'", size(*0.45) justification(right) placement(w)) ///
	text(26 2.9 "`_ES_26_f' (`_LCI_26_f' – `_UCI_26_f')", size(*0.45) justification(left) placement(e)) ///
		text(27 0.025 "Discordant sibling analysis{sup:†}", size(*0.45) justification(left) placement(e)) ///
	text(27 0.16 "`total_exp_27'", size(*0.45) justification(right) placement(w)) ///
	text(27 0.39 "`total_unexp_27'", size(*0.45) justification(right) placement(w)) ///
	text(27 2.9 "`_ES_27_f' (`_LCI_27_f' – `_UCI_27_f')", size(*0.45) justification(left) placement(e)) ///
		text(28 0.025 "Paternal analysis{sup:‡,§}", size(*0.45) justification(left) placement(e)) ///
	text(28 0.16 "`total_exp_28'", size(*0.45) justification(right) placement(w)) ///
	text(28 0.39 "`total_unexp_28'", size(*0.45) justification(right) placement(w)) ///
	text(28 2.9 "`_ES_28_f' (`_LCI_28_f' – `_UCI_28_f')", size(*0.45) justification(left) placement(e)) ///
		text(30 0.025 "{bf:Low Apgar score{sup:‡}}", size(*0.45) justification(left) placement(e)) ///
		text(31 0.025 "Maternal analysis*", size(*0.45) justification(left) placement(e)) ///
	text(31 0.16 "`total_exp_31'", size(*0.45) justification(right) placement(w)) ///
	text(31 0.39 "`total_unexp_31'", size(*0.45) justification(right) placement(w)) ///
	text(31 2.9 "`_ES_31_f' (`_LCI_31_f' – `_UCI_31_f')", size(*0.45) justification(left) placement(e)) ///
		text(32 0.025 "Discordant sibling analysis{sup:†}", size(*0.45) justification(left) placement(e)) ///
	text(32 0.16 "`total_exp_32'", size(*0.45) justification(right) placement(w)) ///
	text(32 0.39 "`total_unexp_32'", size(*0.45) justification(right) placement(w)) ///
	text(32 2.9 "`_ES_32_f' (`_LCI_32_f' – `_UCI_32_f')", size(*0.45) justification(left) placement(e)) ///
		text(33 0.025 "Paternal analysis{sup:§}", size(*0.45) justification(left) placement(e)) ///
	text(33 0.16 "`total_exp_33'", size(*0.45) justification(right) placement(w)) ///
	text(33 0.39 "`total_unexp_33'", size(*0.45) justification(right) placement(w)) ///
	text(33 2.9 "`_ES_33_f' (`_LCI_33_f' – `_UCI_33_f')", size(*0.45) justification(left) placement(e)) ///
	xscale(range(0.025 6.2) log) xlab(0.4(0.2)2.8, labsize(*0.4) format(%3.1fc) angle(45)) xscale(range(0.05 3.8)) plotregion(margin(1 1 0 1)) yscale(noline) xsize(90) ysize(100) ///
	legend(order(3 "Maternal" 4 "Sibling" 5 "Paternal") size(*0.75) pos(5) col(1) region(lcolor(black))) ///
	graphregion(color(white) fcolor(white) ifcolor(white) lcolor(white)) name(prim, replace) 
	
	graph export "$Graphdir\ch6_family_based_fig.pdf", replace
	
********************************************************************************

* Erase unnecessary datasets

	erase "$Graphdir\mat_ma.dta"
	erase "$Graphdir\pat_ma.dta"
	erase "$Graphdir\sib_ma.dta"
	erase "$Graphdir\primary_fig_data.dta"

* Stop logging, translate .smcl into .pdf and erase .smcl

	log close meta_analysis_fig_all_3
	
	translate "$Logdir\meta analysis\3c_meta analysis fig all 3.smcl" "$Logdir\meta analysis\3c_meta analysis fig all 3.pdf", replace
	
	erase "$Logdir\meta analysis\3c_meta analysis fig all 3.smcl"
	
********************************************************************************/
