
/*******************************************************************************

	Creating a drug-specific analysis figure for all three countries

	Author: Flo Martin

	Date: 02/12/2023

	Figure generated by this script
	
		- drug_specific_all3.pdf for the main manuscript
		
		- preterm_drug_ma.pdf for the supplementary
		- sga_drug_ma.pdf for the supplementary
		- apgar_drug_ma.pdf for the supplementary
		
*******************************************************************************/

/* Start logging

	log using "$Logdir\3_figures\4c_meta analysis drug fig all 3", name(meta_analysis_drug_fig_all_3) replace
	
********************************************************************************/

* Load in the data

	cd "$Graphdir"
	use "$Graphdir\data\drug analyses data_all3.dta", clear
	
	* Preterm by drug meta-analysis
	
	keep if outcome=="preterm"
	
	gen drug_str=""
	replace drug_str= "a_unexposed" if drug==0
	replace drug_str= "b_sertraline" if drug==1
	replace drug_str= "c_citalopram" if drug==2
	replace drug_str= "d_fluoxetine" if drug==3
	replace drug_str= "e_escitalopram" if drug==4
	replace drug_str= "f_venlafaxine" if drug==5
	replace drug_str= "g_mirtazapine" if drug==6
	replace drug_str= "h_amitriptyline" if drug==7
	replace drug_str= "i_paroxetine" if drug==8
	replace drug_str= "j_duloxetine" if drug==9
	replace drug_str= "k_other" if drug==10
	replace drug_str= "l_Polytherapy" if drug==11
	
	gen logor = log(or)
	gen loglci = log(lci)
	gen loguci = log(uci)
	
	metan logor loglci loguci, eform by(drug_str) lcols(country total_exp) saving(preterm_ma, replace)
	
	* Use the data from metan to make a nice forest plot
	
	use preterm_ma, clear
	
	bys _BY _USE : egen grp_wt = sum(_WT)
	gen pct_grp_wt = 100 * _WT / grp_wt
	
	drop _WT
	rename pct_grp_wt _WT
	
	drop if _USE>=4 & _USE<6
	*drop if _BY==2 & _USE==3
	
	replace _LABELS = "Sertraline" if _LABELS=="b_sertraline"
	replace _LABELS = "Citalopram" if _LABELS=="c_citalopram"
	replace _LABELS = "Fluoxetine" if _LABELS=="d_fluoxetine"
	replace _LABELS = "Escitalopram" if _LABELS=="e_escitalopram"
	replace _LABELS = "Venlafaxine" if _LABELS=="f_venlafaxine"
	replace _LABELS = "Mirtazapine" if _LABELS=="g_mirtazapine"
	replace _LABELS = "Amitriptyline" if _LABELS=="h_amitriptyline"
	replace _LABELS = "Paroxetine" if _LABELS=="i_paroxetine"
	replace _LABELS = "Duloxetine" if _LABELS=="j_duloxetine"
	replace _LABELS = "Other" if _LABELS=="k_other"
	replace _LABELS = "Polypharmacy" if _LABELS=="l_Polytherapy"
	
	replace _LABELS = "UK" if _LABELS=="uk" 
	replace _LABELS = "Norway" if _LABELS=="no"
	replace _LABELS = "Sweden" if _LABELS=="se"
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf:Drug prescribed / dispensed during pregnancy}"'"'
	label variable total_exp `"`"{bf: n/N}"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	format _ES %4.1fc
	format _WT %4.1fc
	
	*drop if _USE==1
	
	gen country=1 if _LABELS=="UK"
	replace country=2 if _LABELS=="Norway"
	replace country=3 if _LABELS=="Sweden"
	
	set scheme tab2

	forestplot, eform effect("{bf}Odds ratio") null(1) olineopts(lcolor(none)) lcols(total_exp) nlineopts(lcolor(cranberry) lpattern(dash)) xlabel(0.5(0.5)3.5) title("{bf}Drug-specific preterm delivery analysis", size(small)) ///
	plotid(country, list) point1opts(msymbol(triangle) msize(0.75)) point2opts(msymbol(circle) msize(0.75)) point4opts(msymbol(diamond) msize(0.75)) textsize(105) ///
	text(6 6 "*Adjusted for year of birth, maternal age, previous stillbirth, parity, antipsychotic and anti-seizure medication" "use before pregnancy, depression, anxiety, practice-level IMD and ethnicity (UK), maternal educational attainment" "and country of birth (Norway and Sweden), household disposable income (Sweden), smoking during pregnancy" "(UK and Sweden), maternal BMI (Sweden), number of primary care consultations before pregnancy (UK and Norway)", size(*0.4) justification(left) placement(e)) ///
	noadjust name(preterm_ma, replace)
	
	egen seq=seq()
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	replace _ES = exp(_ES)
	replace _LCI = exp(_LCI)
	replace _UCI = exp(_UCI) 
	
	replace _ES=10 if _ES==.
	replace _LCI=10 if _LCI==.
	replace _UCI=10 if _UCI==.
	
	
	forvalues x=2/65 {
		foreach y in _ES _LCI _UCI {
		
			sum `y' if seq==`x'
			local `y'_`x' = `r(mean)'
			local `y'_`x'_f : display %4.2fc ``y'_`x'' 
			
		}		
	}
	
	replace _ES=. if _ES==10
	replace _LCI=. if _LCI==10
	replace _UCI=. if _UCI==10
	
	forvalues x=2/65 {
	
		local total_exp_`x' = total_exp[`x']
		di "`total_exp_`x''"
		
	}
	
	forvalues x=2/65 {
	
		local _LABELS`x' = _LABELS[`x']
		di "`_LABELS`x''"
		
	}
	
	replace _WT=10 if _WT==.
	
	forvalues x=2/65 {
	
		sum _WT if seq==`x'
		local WT_`x' = `r(mean)'
		local WT_`x'_f : display %4.1fc `WT_`x''
		disp "`WT_`x'_f'"
		
	}
	
	replace _WT=. if _WT==10
	
	* Macros to create the null line
	local t1=0
	local t2=66
	
	tw ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap _LCI _UCI seq if _USE==1, horizontal lcolor(black) mlw(thin) msize(*0.5)) /// code for NO 95% CI
	(rcap _LCI _UCI seq if _USE==3, horizontal mlcolor(cranberry) lcolor(cranberry) mlw(thin) msize(*0.5)) ///
	(scatter seq _ES if _LABELS=="UK", mcolor("85 119 135") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Norway", mcolor("217 142 98") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Sweden", mcolor("168 210 218") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _USE==3, mcolor(cranberry) ms(d) msize(small) mcolor(white) mlcolor(cranberry) mlw(thin)), ///
	yscale(range(-2.15 66) reverse noline) ylab("", angle(0) labsize(*0.6) notick nogrid nogextend) /// 
	legend(order(4 "UK" 5 "Norway" 6 "Sweden" 7 "Overall") region(lcolor(black)) pos(5) size(*0.75)) ///
	yline(-3, lwidth(*1.2)) yline(0, lwidth(*1)) yline(6, lcolor(gray) lpattern(dot)) yline(12, lcolor(gray) lpattern(dot)) yline(18, lcolor(gray) lpattern(dot)) yline(24, lcolor(gray) lpattern(dot)) yline(30, lcolor(gray) lpattern(dot)) yline(36, lcolor(gray) lpattern(dot)) yline(42, lcolor(gray) lpattern(dot)) yline(48, lcolor(gray) lpattern(dot)) yline(54, lcolor(gray) lpattern(dot)) yline(60, lcolor(gray) lpattern(dot)) ///
	
	xscale(range(0.21 5.5) log) xlab(0.4(0.2)3.8, labsize(*0.55) format(%3.1fc) angle(45))  ///
	graphregion(color(white) fcolor(white) ifcolor(white) lcolor(white)) plotregion(margin(1 1 0 1)) ///
	title("{bf}Antidepressant use during pregnancy and preterm delivery in the UK, Norway, & Sweden", size(small)) ///
	text(-1.5 3.9 "{bf}aOR* (95% CI)", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 4.8 "{bf}Weight (%)", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 0.21 "{bf}Antidepressant" "Country", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 0.39 "{bf}Preterm / Total exposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(1 0.21 "{bf:Sertraline}", size(*0.35) justification(left) placement(e)) ///
		text(2 0.22 "`_LABELS2'", size(*0.35) justification(left) placement(e)) ///
	text(2 0.39 "`total_exp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 3.9 "`_ES_2_f' (`_LCI_2_f' – `_UCI_2_f')", size(*0.35) justification(left) placement(e)) ///
	text(2 5.4 "`WT_2_f'", size(*0.35) justification(right) placement(w)) ///
		text(3 0.22 "`_LABELS3'", size(*0.35) justification(left) placement(e)) ///
	text(3 0.39 "`total_exp_3'", size(*0.35) justification(right) placement(w)) ///
	text(3 3.9 "`_ES_3_f' (`_LCI_3_f' – `_UCI_3_f')", size(*0.35) justification(left) placement(e)) ///
	text(3 5.4 "`WT_3_f'", size(*0.35) justification(right) placement(w)) ///
		text(4 0.22 "`_LABELS4'", size(*0.35) justification(left) placement(e)) ///
	text(4 0.39 "`total_exp_4'", size(*0.35) justification(right) placement(w)) ///
	text(4 3.9 "`_ES_4_f' (`_LCI_4_f' – `_UCI_4_f')", size(*0.35) justification(left) placement(e)) ///
	text(4 5.4 "`WT_4_f'", size(*0.35) justification(right) placement(w)) ///
	text(5 0.21 "`_LABELS5'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(5 3.9 "`_ES_5_f' (`_LCI_5_f' – `_UCI_5_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(5 5.4 "`WT_5_f'", size(*0.35) justification(right) placement(w)) ///
	text(7 0.21 "{bf:Citalopram}", size(*0.35) justification(left) placement(e)) ///
		text(8 0.22 "`_LABELS8'", size(*0.35) justification(left) placement(e)) ///
	text(8 0.39 "`total_exp_8'", size(*0.35) justification(right) placement(w)) ///
	text(8 3.9 "`_ES_8_f' (`_LCI_8_f' – `_UCI_8_f')", size(*0.35) justification(left) placement(e)) ///
	text(8 5.4 "`WT_8_f'", size(*0.35) justification(right) placement(w)) ///
		text(9 0.22 "`_LABELS9'", size(*0.35) justification(left) placement(e)) ///
	text(9 0.39 "`total_exp_9'", size(*0.35) justification(right) placement(w)) ///
	text(9 3.9 "`_ES_9_f' (`_LCI_9_f' – `_UCI_9_f')", size(*0.35) justification(left) placement(e)) ///
	text(9 5.4 "`WT_9_f'", size(*0.35) justification(right) placement(w)) ///
		text(10 0.22 "`_LABELS10'", size(*0.35) justification(left) placement(e)) ///
	text(10 0.39 "`total_exp_10'", size(*0.35) justification(right) placement(w)) ///
	text(10 3.9 "`_ES_10_f' (`_LCI_10_f' – `_UCI_10_f')", size(*0.35) justification(left) placement(e)) ///
	text(10 5.4 "`WT_10_f'", size(*0.35) justification(right) placement(w)) ///
	text(11 0.21 "`_LABELS11'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(11 3.9 "`_ES_11_f' (`_LCI_11_f' – `_UCI_11_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(11 5.4 "`WT_11_f'", size(*0.35) justification(right) placement(w)) ///
	text(13 0.21 "{bf:Fluoxetine}", size(*0.35) justification(left) placement(e)) ///
		text(14 0.22 "`_LABELS14'", size(*0.35) justification(left) placement(e)) ///
	text(14 0.39 "`total_exp_14'", size(*0.35) justification(right) placement(w)) ///
	text(14 3.9 "`_ES_14_f' (`_LCI_14_f' – `_UCI_14_f')", size(*0.35) justification(left) placement(e)) ///
	text(14 5.4 "`WT_14_f'", size(*0.35) justification(right) placement(w)) ///
		text(15 0.22 "`_LABELS15'", size(*0.35) justification(left) placement(e)) ///
	text(15 0.39 "`total_exp_15'", size(*0.35) justification(right) placement(w)) ///
	text(15 3.9 "`_ES_15_f' (`_LCI_15_f' – `_UCI_15_f')", size(*0.35) justification(left) placement(e)) ///
	text(15 5.4 "`WT_15_f'", size(*0.35) justification(right) placement(w)) ///
		text(16 0.22 "`_LABELS16'", size(*0.35) justification(left) placement(e)) ///
	text(16 0.39 "`total_exp_16'", size(*0.35) justification(right) placement(w)) ///
	text(16 3.9 "`_ES_16_f' (`_LCI_16_f' – `_UCI_16_f')", size(*0.35) justification(left) placement(e)) ///
	text(16 5.4 "`WT_16_f'", size(*0.35) justification(right) placement(w)) ///
	text(17 0.21 "`_LABELS17'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(17 3.9 "`_ES_17_f' (`_LCI_17_f' – `_UCI_17_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(17 5.4 "`WT_17_f'", size(*0.35) justification(right) placement(w)) ///
	text(19 0.21 "{bf:Escitalopram}", size(*0.35) justification(left) placement(e)) ///
		text(20 0.22 "`_LABELS20'", size(*0.35) justification(left) placement(e)) ///
	text(20 0.39 "`total_exp_20'", size(*0.35) justification(right) placement(w)) ///
	text(20 3.9 "`_ES_20_f' (`_LCI_20_f' – `_UCI_20_f')", size(*0.35) justification(left) placement(e)) ///
	text(20 5.4 "`WT_20_f'", size(*0.35) justification(right) placement(w)) ///
		text(21 0.22 "`_LABELS21'", size(*0.35) justification(left) placement(e)) ///
	text(21 0.39 "`total_exp_21'", size(*0.35) justification(right) placement(w)) ///
	text(21 3.9 "`_ES_21_f' (`_LCI_21_f' – `_UCI_21_f')", size(*0.35) justification(left) placement(e)) ///
	text(21 5.4 "`WT_21_f'", size(*0.35) justification(right) placement(w)) ///
		text(22 0.22 "`_LABELS22'", size(*0.35) justification(left) placement(e)) ///
	text(22 0.39 "`total_exp_22'", size(*0.35) justification(right) placement(w)) ///
	text(22 3.9 "`_ES_22_f' (`_LCI_22_f' – `_UCI_22_f')", size(*0.35) justification(left) placement(e)) ///
	text(22 5.4 "`WT_22_f'", size(*0.35) justification(right) placement(w)) ///
	text(23 0.21 "`_LABELS23'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(23 3.9 "`_ES_23_f' (`_LCI_23_f' – `_UCI_23_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(23 5.4 "`WT_23_f'", size(*0.35) justification(right) placement(w)) ///
	text(25 0.21 "{bf:Venlafaxine}", size(*0.35) justification(left) placement(e)) ///
		text(26 0.22 "`_LABELS26'", size(*0.35) justification(left) placement(e)) ///
	text(26 0.39 "`total_exp_26'", size(*0.35) justification(right) placement(w)) ///
	text(26 5.4 "`WT_26_f'", size(*0.35) justification(right) placement(w)) ///
	text(26 3.9 "`_ES_26_f' (`_LCI_26_f' – `_UCI_26_f')", size(*0.35) justification(left) placement(e)) ///
		text(27 0.22 "`_LABELS27'", size(*0.35) justification(left) placement(e)) ///
	text(27 0.39 "`total_exp_27'", size(*0.35) justification(right) placement(w)) ///
	text(27 3.9 "`_ES_27_f' (`_LCI_27_f' – `_UCI_27_f')", size(*0.35) justification(left) placement(e)) ///
	text(27 5.4 "`WT_27_f'", size(*0.35) justification(right) placement(w)) ///
		text(28 0.22 "`_LABELS28'", size(*0.35) justification(left) placement(e)) ///
	text(28 0.39 "`total_exp_28'", size(*0.35) justification(right) placement(w)) ///
	text(28 3.9 "`_ES_28_f' (`_LCI_28_f' – `_UCI_28_f')", size(*0.35) justification(left) placement(e)) ///
	text(28 5.4 "`WT_28_f'", size(*0.35) justification(right) placement(w)) ///
	text(29 0.21 "`_LABELS29'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(29 3.9 "`_ES_29_f' (`_LCI_29_f' – `_UCI_29_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(29 5.4 "`WT_29_f'", size(*0.35) justification(right) placement(w)) ///
	text(31 0.21 "{bf:Mirtazapine}", size(*0.35) justification(left) placement(e)) ///
		text(32 0.22 "`_LABELS32'", size(*0.35) justification(left) placement(e)) ///
	text(32 0.39 "`total_exp_32'", size(*0.35) justification(right) placement(w)) ///
	text(32 3.9 "`_ES_32_f' (`_LCI_32_f' – `_UCI_32_f')", size(*0.35) justification(left) placement(e)) ///
	text(32 5.4 "`WT_32_f'", size(*0.35) justification(right) placement(w)) ///
		text(33 0.22 "`_LABELS33'", size(*0.35) justification(left) placement(e)) ///
	text(33 0.39 "`total_exp_33'", size(*0.35) justification(right) placement(w)) ///
	text(33 3.9 "`_ES_33_f' (`_LCI_33_f' – `_UCI_33_f')", size(*0.35) justification(left) placement(e)) ///
	text(33 5.4 "`WT_33_f'", size(*0.35) justification(right) placement(w)) ///
		text(34 0.22 "`_LABELS34'", size(*0.35) justification(left) placement(e)) ///
	text(34 0.39 "`total_exp_34'", size(*0.35) justification(right) placement(w)) ///
	text(34 3.9 "`_ES_34_f' (`_LCI_34_f' – `_UCI_34_f')", size(*0.35) justification(left) placement(e)) ///
	text(34 5.4 "`WT_34_f'", size(*0.35) justification(right) placement(w)) ///
	text(35 0.21 "`_LABELS35'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(35 3.9 "`_ES_35_f' (`_LCI_35_f' – `_UCI_35_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(35 5.4 "`WT_35_f'", size(*0.35) justification(right) placement(w)) ///
	text(37 0.21 "{bf:Amitriptyline}", size(*0.35) justification(left) placement(e)) ///
		text(38 0.22 "`_LABELS38'", size(*0.35) justification(left) placement(e)) ///
	text(38 0.39 "`total_exp_38'", size(*0.35) justification(right) placement(w)) ///
	text(38 3.9 "`_ES_38_f' (`_LCI_38_f' – `_UCI_38_f')", size(*0.35) justification(left) placement(e)) ///
	text(38 5.4 "`WT_38_f'", size(*0.35) justification(right) placement(w)) ///
		text(39 0.22 "`_LABELS39'", size(*0.35) justification(left) placement(e)) ///
	text(39 0.39 "`total_exp_39'", size(*0.35) justification(right) placement(w)) ///
	text(39 3.9 "`_ES_39_f' (`_LCI_39_f' – `_UCI_39_f')", size(*0.35) justification(left) placement(e)) ///
	text(39 5.4 "`WT_39_f'", size(*0.35) justification(right) placement(w)) ///
		text(40 0.22 "`_LABELS40'", size(*0.35) justification(left) placement(e)) ///
	text(40 0.39 "`total_exp_40'", size(*0.35) justification(right) placement(w)) ///
	text(40 5.4 "`WT_40_f'", size(*0.35) justification(right) placement(w)) ///
	text(40 3.9 "`_ES_40_f' (`_LCI_40_f' – `_UCI_40_f')", size(*0.35) justification(left) placement(e)) ///
	text(41 0.21 "`_LABELS41'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(41 3.9 "`_ES_41_f' (`_LCI_41_f' – `_UCI_41_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(41 5.4 "`WT_41_f'", size(*0.35) justification(right) placement(w)) ///
	text(43 0.21 "{bf:Paroxetine}", size(*0.35) justification(left) placement(e)) ///
		text(44 0.22 "`_LABELS44'", size(*0.35) justification(left) placement(e)) ///
	text(44 0.39 "`total_exp_44'", size(*0.35) justification(right) placement(w)) ///
	text(44 3.9 "`_ES_44_f' (`_LCI_44_f' – `_UCI_44_f')", size(*0.35) justification(left) placement(e)) ///
	text(44 5.4 "`WT_44_f'", size(*0.35) justification(right) placement(w)) ///
		text(45 0.22 "`_LABELS45'", size(*0.35) justification(left) placement(e)) ///
	text(45 0.39 "`total_exp_45'", size(*0.35) justification(right) placement(w)) ///
	text(45 3.9 "`_ES_45_f' (`_LCI_45_f' – `_UCI_45_f')", size(*0.35) justification(left) placement(e)) ///
	text(45 5.4 "`WT_45_f'", size(*0.35) justification(right) placement(w)) ///
		text(46 0.22 "`_LABELS46'", size(*0.35) justification(left) placement(e)) ///
	text(46 0.39 "`total_exp_46'", size(*0.35) justification(right) placement(w)) ///
	text(46 3.9 "`_ES_46_f' (`_LCI_46_f' – `_UCI_46_f')", size(*0.35) justification(left) placement(e)) ///
	text(46 5.4 "`WT_46_f'", size(*0.35) justification(right) placement(w)) ///
	text(47 0.21 "`_LABELS47'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(47 3.9 "`_ES_47_f' (`_LCI_47_f' – `_UCI_47_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(47 5.4 "`WT_47_f'", size(*0.35) justification(right) placement(w)) ///
	text(49 0.21 "{bf:Duloxetine}", size(*0.35) justification(left) placement(e)) ///
		text(50 0.22 "`_LABELS50'", size(*0.35) justification(left) placement(e)) ///
	text(50 0.39 "`total_exp_50'", size(*0.35) justification(right) placement(w)) ///
	text(50 3.9 "`_ES_50_f' (`_LCI_50_f' – `_UCI_50_f')", size(*0.35) justification(left) placement(e)) ///
	text(50 5.4 "`WT_50_f'", size(*0.35) justification(right) placement(w)) ///
		text(51 0.22 "`_LABELS51'", size(*0.35) justification(left) placement(e)) ///
	text(51 0.39 "`total_exp_51'", size(*0.35) justification(right) placement(w)) ///
	text(51 3.9 "`_ES_51_f' (`_LCI_51_f' – `_UCI_51_f')", size(*0.35) justification(left) placement(e)) ///
	text(51 5.4 "`WT_51_f'", size(*0.35) justification(right) placement(w)) ///
		text(52 0.22 "`_LABELS52'", size(*0.35) justification(left) placement(e)) ///
	text(52 0.39 "`total_exp_52'", size(*0.35) justification(right) placement(w)) ///
	text(52 3.9 "`_ES_52_f' (`_LCI_52_f' – `_UCI_52_f')", size(*0.35) justification(left) placement(e)) ///
	text(52 5.4 "`WT_52_f'", size(*0.35) justification(right) placement(w)) ///
	text(53 0.21 "`_LABELS53'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(53 3.9 "`_ES_53_f' (`_LCI_53_f' – `_UCI_53_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(53 5.4 "`WT_53_f'", size(*0.35) justification(right) placement(w)) ///
	text(55 0.21 "{bf:Other}", size(*0.35) justification(left) placement(e)) ///
		text(56 0.22 "`_LABELS56'", size(*0.35) justification(left) placement(e)) ///
	text(56 0.39 "`total_exp_56'", size(*0.35) justification(right) placement(w)) ///
	text(56 3.9 "`_ES_56_f' (`_LCI_56_f' – `_UCI_56_f')", size(*0.35) justification(left) placement(e)) ///
	text(56 5.4 "`WT_56_f'", size(*0.35) justification(right) placement(w)) ///
		text(57 0.22 "`_LABELS57'", size(*0.35) justification(left) placement(e)) ///
	text(57 0.39 "`total_exp_57'", size(*0.35) justification(right) placement(w)) ///
	text(57 3.9 "`_ES_57_f' (`_LCI_57_f' – `_UCI_57_f')", size(*0.35) justification(left) placement(e)) ///
	text(57 5.4 "`WT_57_f'", size(*0.35) justification(right) placement(w)) ///
		text(58 0.22 "`_LABELS58'", size(*0.35) justification(left) placement(e)) ///
	text(58 0.39 "`total_exp_58'", size(*0.35) justification(right) placement(w)) ///
	text(58 3.9 "`_ES_58_f' (`_LCI_58_f' – `_UCI_58_f')", size(*0.35) justification(left) placement(e)) ///
	text(58 5.4 "`WT_58_f'", size(*0.35) justification(right) placement(w)) ///
	text(59 0.21 "`_LABELS59'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(59 3.9 "`_ES_59_f' (`_LCI_59_f' – `_UCI_59_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(59 5.4 "`WT_59_f'", size(*0.35) justification(right) placement(w)) ///
	text(61 0.21 "{bf:Polytherapy}", size(*0.35) justification(left) placement(e)) ///
		text(62 0.22 "`_LABELS62'", size(*0.35) justification(left) placement(e)) ///
	text(62 0.39 "`total_exp_62'", size(*0.35) justification(right) placement(w)) ///
	text(62 3.9 "`_ES_62_f' (`_LCI_62_f' – `_UCI_62_f')", size(*0.35) justification(left) placement(e)) ///
	text(62 5.4 "`WT_62_f'", size(*0.35) justification(right) placement(w)) ///
		text(63 0.22 "`_LABELS63'", size(*0.35) justification(left) placement(e)) ///
	text(63 0.39 "`total_exp_63'", size(*0.35) justification(right) placement(w)) ///
	text(63 3.9 "`_ES_63_f' (`_LCI_63_f' – `_UCI_63_f')", size(*0.35) justification(left) placement(e)) ///
	text(63 5.4 "`WT_63_f'", size(*0.35) justification(right) placement(w)) ///
		text(64 0.22 "`_LABELS64'", size(*0.35) justification(left) placement(e)) ///
	text(64 0.39 "`total_exp_64'", size(*0.35) justification(right) placement(w)) ///
	text(64 3.9 "`_ES_64_f' (`_LCI_64_f' – `_UCI_64_f')", size(*0.35) justification(left) placement(e)) ///
	text(64 5.4 "`WT_64_f'", size(*0.35) justification(right) placement(w)) ///
	text(65 0.21 "`_LABELS65'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(65 3.9 "`_ES_65_f' (`_LCI_65_f' – `_UCI_65_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(65 5.4 "`WT_65_f'", size(*0.35) justification(right) placement(w)) ///
	text(72 1 "{bf:Odds ratio* (95% confidence interval)}" "from logistic regression", size(*0.45)) ///
	text(74.1 1 "from fixed effects meta-analysis", size(*0.45) color(cranberry)) ///
	text(74 0.21 "*Adjusted for year of birth, maternal age, previous stillbirth, parity," "antipsychotic and anti-seizure medication use before pregnancy, depression," "anxiety, practice-level IMD and ethnicity (UK), maternal educational attainment" "and country of birth (Norway and Sweden), household disposable income" "(Sweden), smoking during pregnancy (UK and Sweden), maternal BMI" "(Sweden), number of primary care consultations before pregnancy (UK and" "Norway)", size(*0.35) justification(left) placement(e)) ///
	name(preterm, replace)
	
	/* Save graph
	
	graph export "C:\Users\ti19522\OneDrive - University of Bristol\Flo Martin Supervisory Team\Year 4\6_Birth outcomes\supplementary figures\preterm_drug_ma.pdf", replace 
	
********************************************************************************

* Load in the data
	
	use "$Graphdir\data\drug analyses data_all3.dta", clear
	
	keep if outcome=="sga"
	
	gen drug_str=""
	replace drug_str= "a_unexposed" if drug==0
	replace drug_str= "b_sertraline" if drug==1
	replace drug_str= "c_citalopram" if drug==2
	replace drug_str= "d_fluoxetine" if drug==3
	replace drug_str= "e_escitalopram" if drug==4
	replace drug_str= "f_venlafaxine" if drug==5
	replace drug_str= "g_mirtazapine" if drug==6
	replace drug_str= "h_amitriptyline" if drug==7
	replace drug_str= "i_paroxetine" if drug==8
	replace drug_str= "j_duloxetine" if drug==9
	replace drug_str= "k_other" if drug==10
	replace drug_str= "l_Polytherapy" if drug==11
	
	gen logor = log(or)
	gen loglci = log(lci)
	gen loguci = log(uci)
	
	metan logor loglci loguci, eform by(drug_str) lcols(country total_exp) saving(sga_ma, replace)
	
	use sga_ma, clear
	
	bys _BY _USE : egen grp_wt = sum(_WT)
	gen pct_grp_wt = 100 * _WT / grp_wt
	
	drop _WT
	rename pct_grp_wt _WT
	
	drop if _USE>=4 & _USE<6
	*drop if _BY==2 & _USE==3
	
	replace _LABELS = "Sertraline" if _LABELS=="b_sertraline"
	replace _LABELS = "Citalopram" if _LABELS=="c_citalopram"
	replace _LABELS = "Fluoxetine" if _LABELS=="d_fluoxetine"
	replace _LABELS = "Escitalopram" if _LABELS=="e_escitalopram"
	replace _LABELS = "Venlafaxine" if _LABELS=="f_venlafaxine"
	replace _LABELS = "Mirtazapine" if _LABELS=="g_mirtazapine"
	replace _LABELS = "Amitriptyline" if _LABELS=="h_amitriptyline"
	replace _LABELS = "Paroxetine" if _LABELS=="i_paroxetine"
	replace _LABELS = "Duloxetine" if _LABELS=="j_duloxetine"
	replace _LABELS = "Other" if _LABELS=="k_other"
	replace _LABELS = "Polypharmacy" if _LABELS=="l_Polytherapy"
	
	replace _LABELS = "UK" if _LABELS=="uk"
	replace _LABELS = "Norway" if _LABELS=="no"
	replace _LABELS = "Sweden" if _LABELS=="se"
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf:Drug prescribed / dispensed during pregnancy}"'"'
	label variable total_exp `"`"{bf: n/N}"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	format _ES %4.1fc
	format _WT %4.1fc
	
	*drop if _USE==1
	
	gen country=1 if _LABELS=="UK"
	replace country=2 if _LABELS=="Norway"
	replace country=3 if _LABELS=="Sweden"

	forestplot, eform effect("{bf}Odds ratio") null(1) olineopts(lcolor(none)) lcols(total_exp) nlineopts(lcolor(cranberry) lpattern(dash)) xlabel(0.25 0.5(0.5)2.5) cirange(0.25 3) title("{bf}Drug-specific analysis for SGA", size(small)) ///
	plotid(country, list) point1opts(msymbol(triangle) msize(0.75)) point2opts(msymbol(circle) msize(0.75)) point4opts(msymbol(diamond) msize(0.75)) textsize(105) ///
	name(sga_ma, replace)
	
	* Save graph
	
	cd "$Graphdir"
	graph export sga_drug_ma.pdf, replace
	
	egen seq=seq()
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	replace _ES = exp(_ES)
	replace _LCI = exp(_LCI)
	replace _UCI = exp(_UCI) 
	
	replace _ES=10 if _ES==.
	replace _LCI=10 if _LCI==.
	replace _UCI=10 if _UCI==.
	
	
	forvalues x=2/65 {
		foreach y in _ES _LCI _UCI {
		
			sum `y' if seq==`x'
			local `y'_`x' = `r(mean)'
			local `y'_`x'_f : display %4.2fc ``y'_`x'' 
			
		}		
	}
	
	replace _ES=. if _ES==10
	replace _LCI=. if _LCI==10
	replace _UCI=. if _UCI==10
	
	forvalues x=2/65 {
	
		local total_exp_`x' = total_exp[`x']
		di "`total_exp_`x''"
		
	}
	
	forvalues x=2/65 {
	
		local _LABELS`x' = _LABELS[`x']
		di "`_LABELS`x''"
		
	}
	
	replace _WT=10 if _WT==.
	
	forvalues x=2/65 {
	
		sum _WT if seq==`x'
		local WT_`x' = `r(mean)'
		local WT_`x'_f : display %4.1fc `WT_`x''
		disp "`WT_`x'_f'"
		
	}
	
	replace _WT=. if _WT==10
	
	* Macros to create the null line
	local t1=0
	local t2=66
	
	* Capped CI
	
	gen cap=50 if seq==50
	gen lci=0.4 if seq==50
	gen lci_cap=`_UCI_50' if seq==50
	gen uci_cap=`_UCI_50' if seq==50 
	
	tw ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap _LCI _UCI seq if _USE==1 & seq!=50, horizontal lcolor(black) mlw(thin) msize(*0.5)) /// code for NO 95% CI
	(rcap _LCI _UCI seq if _USE==3, horizontal mlcolor(cranberry) lcolor(cranberry) mlw(thin) msize(*0.5)) ///
	(rcap lci_cap uci_cap seq, horizontal lcolor(black) mlw(thin) msize(*0.5)) ///
	(pcarrow cap _UCI cap lci if seq==50, lcolor(black) mcolor(black) msize(*0.5)) ///
	(scatter seq _ES if _LABELS=="UK", mcolor("85 119 135") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Norway", mcolor("217 142 98") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Sweden", mcolor("168 210 218") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _USE==3, mcolor(cranberry) ms(d) msize(small) mcolor(white) mlcolor(cranberry) mlw(thin)), ///
	yscale(range(-2.15 66) reverse noline) ylab("", angle(0) labsize(*0.6) notick nogrid nogextend) /// 
	legend(order(6 "UK" 7 "Norway" 8 "Sweden" 9 "Overall") region(lcolor(black)) pos(5) size(*0.75)) ///
	yline(-3, lwidth(*1.2)) yline(0) yline(6, lcolor(gray) lpattern(dot)) yline(12, lcolor(gray) lpattern(dot)) yline(18, lcolor(gray) lpattern(dot)) yline(24, lcolor(gray) lpattern(dot)) yline(30, lcolor(gray) lpattern(dot)) yline(36, lcolor(gray) lpattern(dot)) yline(42, lcolor(gray) lpattern(dot)) yline(48, lcolor(gray) lpattern(dot)) yline(54, lcolor(gray) lpattern(dot)) yline(60, lcolor(gray) lpattern(dot)) ///
	xscale(range(0.21 5.5) log) xlab(0.4(0.2)3.8, labsize(*0.55) format(%3.1fc) angle(45))  ///
	graphregion(color(white) fcolor(white) ifcolor(white) lcolor(white)) plotregion(margin(1 1 0 1)) ///
	title("{bf}Antidepressant use during pregnancy and SGA in the UK, Norway, & Sweden", size(small)) ///
	text(-1.5 3.9 "{bf}aOR* (95% CI)", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 4.8 "{bf}Weight (%)", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 0.21 "{bf}Antidepressant" "Country", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 0.39 "{bf}SGA / Total exposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(1 0.21 "{bf:Sertraline}", size(*0.35) justification(left) placement(e)) ///
		text(2 0.22 "`_LABELS2'", size(*0.35) justification(left) placement(e)) ///
	text(2 0.39 "`total_exp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 3.9 "`_ES_2_f' (`_LCI_2_f' – `_UCI_2_f')", size(*0.35) justification(left) placement(e)) ///
	text(2 5.4 "`WT_2_f'", size(*0.35) justification(right) placement(w)) ///
		text(3 0.22 "`_LABELS3'", size(*0.35) justification(left) placement(e)) ///
	text(3 0.39 "`total_exp_3'", size(*0.35) justification(right) placement(w)) ///
	text(3 3.9 "`_ES_3_f' (`_LCI_3_f' – `_UCI_3_f')", size(*0.35) justification(left) placement(e)) ///
	text(3 5.4 "`WT_3_f'", size(*0.35) justification(right) placement(w)) ///
		text(4 0.22 "`_LABELS4'", size(*0.35) justification(left) placement(e)) ///
	text(4 0.39 "`total_exp_4'", size(*0.35) justification(right) placement(w)) ///
	text(4 3.9 "`_ES_4_f' (`_LCI_4_f' – `_UCI_4_f')", size(*0.35) justification(left) placement(e)) ///
	text(4 5.4 "`WT_4_f'", size(*0.35) justification(right) placement(w)) ///
	text(5 0.21 "`_LABELS5'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(5 3.9 "`_ES_5_f' (`_LCI_5_f' – `_UCI_5_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(5 5.4 "`WT_5_f'", size(*0.35) justification(right) placement(w)) ///
	text(7 0.21 "{bf:Citalopram}", size(*0.35) justification(left) placement(e)) ///
		text(8 0.22 "`_LABELS8'", size(*0.35) justification(left) placement(e)) ///
	text(8 0.39 "`total_exp_8'", size(*0.35) justification(right) placement(w)) ///
	text(8 3.9 "`_ES_8_f' (`_LCI_8_f' – `_UCI_8_f')", size(*0.35) justification(left) placement(e)) ///
	text(8 5.4 "`WT_8_f'", size(*0.35) justification(right) placement(w)) ///
		text(9 0.22 "`_LABELS9'", size(*0.35) justification(left) placement(e)) ///
	text(9 0.39 "`total_exp_9'", size(*0.35) justification(right) placement(w)) ///
	text(9 3.9 "`_ES_9_f' (`_LCI_9_f' – `_UCI_9_f')", size(*0.35) justification(left) placement(e)) ///
	text(9 5.4 "`WT_9_f'", size(*0.35) justification(right) placement(w)) ///
		text(10 0.22 "`_LABELS10'", size(*0.35) justification(left) placement(e)) ///
	text(10 0.39 "`total_exp_10'", size(*0.35) justification(right) placement(w)) ///
	text(10 3.9 "`_ES_10_f' (`_LCI_10_f' – `_UCI_10_f')", size(*0.35) justification(left) placement(e)) ///
	text(10 5.4 "`WT_10_f'", size(*0.35) justification(right) placement(w)) ///
	text(11 0.21 "`_LABELS11'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(11 3.9 "`_ES_11_f' (`_LCI_11_f' – `_UCI_11_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(11 5.4 "`WT_11_f'", size(*0.35) justification(right) placement(w)) ///
	text(13 0.21 "{bf:Fluoxetine}", size(*0.35) justification(left) placement(e)) ///
		text(14 0.22 "`_LABELS14'", size(*0.35) justification(left) placement(e)) ///
	text(14 0.39 "`total_exp_14'", size(*0.35) justification(right) placement(w)) ///
	text(14 3.9 "`_ES_14_f' (`_LCI_14_f' – `_UCI_14_f')", size(*0.35) justification(left) placement(e)) ///
	text(14 5.4 "`WT_14_f'", size(*0.35) justification(right) placement(w)) ///
		text(15 0.22 "`_LABELS15'", size(*0.35) justification(left) placement(e)) ///
	text(15 0.39 "`total_exp_15'", size(*0.35) justification(right) placement(w)) ///
	text(15 3.9 "`_ES_15_f' (`_LCI_15_f' – `_UCI_15_f')", size(*0.35) justification(left) placement(e)) ///
	text(15 5.4 "`WT_15_f'", size(*0.35) justification(right) placement(w)) ///
		text(16 0.22 "`_LABELS16'", size(*0.35) justification(left) placement(e)) ///
	text(16 0.39 "`total_exp_16'", size(*0.35) justification(right) placement(w)) ///
	text(16 3.9 "`_ES_16_f' (`_LCI_16_f' – `_UCI_16_f')", size(*0.35) justification(left) placement(e)) ///
	text(16 5.4 "`WT_16_f'", size(*0.35) justification(right) placement(w)) ///
	text(17 0.21 "`_LABELS17'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(17 3.9 "`_ES_17_f' (`_LCI_17_f' – `_UCI_17_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(17 5.4 "`WT_17_f'", size(*0.35) justification(right) placement(w)) ///
	text(19 0.21 "{bf:Escitalopram}", size(*0.35) justification(left) placement(e)) ///
		text(20 0.22 "`_LABELS20'", size(*0.35) justification(left) placement(e)) ///
	text(20 0.39 "`total_exp_20'", size(*0.35) justification(right) placement(w)) ///
	text(20 3.9 "`_ES_20_f' (`_LCI_20_f' – `_UCI_20_f')", size(*0.35) justification(left) placement(e)) ///
	text(20 5.4 "`WT_20_f'", size(*0.35) justification(right) placement(w)) ///
		text(21 0.22 "`_LABELS21'", size(*0.35) justification(left) placement(e)) ///
	text(21 0.39 "`total_exp_21'", size(*0.35) justification(right) placement(w)) ///
	text(21 3.9 "`_ES_21_f' (`_LCI_21_f' – `_UCI_21_f')", size(*0.35) justification(left) placement(e)) ///
	text(21 5.4 "`WT_21_f'", size(*0.35) justification(right) placement(w)) ///
		text(22 0.22 "`_LABELS22'", size(*0.35) justification(left) placement(e)) ///
	text(22 0.39 "`total_exp_22'", size(*0.35) justification(right) placement(w)) ///
	text(22 3.9 "`_ES_22_f' (`_LCI_22_f' – `_UCI_22_f')", size(*0.35) justification(left) placement(e)) ///
	text(22 5.4 "`WT_22_f'", size(*0.35) justification(right) placement(w)) ///
	text(23 0.21 "`_LABELS23'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(23 3.9 "`_ES_23_f' (`_LCI_23_f' – `_UCI_23_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(23 5.4 "`WT_23_f'", size(*0.35) justification(right) placement(w)) ///
	text(25 0.21 "{bf:Venlafaxine}", size(*0.35) justification(left) placement(e)) ///
		text(26 0.22 "`_LABELS26'", size(*0.35) justification(left) placement(e)) ///
	text(26 0.39 "`total_exp_26'", size(*0.35) justification(right) placement(w)) ///
	text(26 5.4 "`WT_26_f'", size(*0.35) justification(right) placement(w)) ///
	text(26 3.9 "`_ES_26_f' (`_LCI_26_f' – `_UCI_26_f')", size(*0.35) justification(left) placement(e)) ///
		text(27 0.22 "`_LABELS27'", size(*0.35) justification(left) placement(e)) ///
	text(27 0.39 "`total_exp_27'", size(*0.35) justification(right) placement(w)) ///
	text(27 3.9 "`_ES_27_f' (`_LCI_27_f' – `_UCI_27_f')", size(*0.35) justification(left) placement(e)) ///
	text(27 5.4 "`WT_27_f'", size(*0.35) justification(right) placement(w)) ///
		text(28 0.22 "`_LABELS28'", size(*0.35) justification(left) placement(e)) ///
	text(28 0.39 "`total_exp_28'", size(*0.35) justification(right) placement(w)) ///
	text(28 3.9 "`_ES_28_f' (`_LCI_28_f' – `_UCI_28_f')", size(*0.35) justification(left) placement(e)) ///
	text(28 5.4 "`WT_28_f'", size(*0.35) justification(right) placement(w)) ///
	text(29 0.21 "`_LABELS29'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(29 3.9 "`_ES_29_f' (`_LCI_29_f' – `_UCI_29_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(29 5.4 "`WT_29_f'", size(*0.35) justification(right) placement(w)) ///
	text(31 0.21 "{bf:Mirtazapine}", size(*0.35) justification(left) placement(e)) ///
		text(32 0.22 "`_LABELS32'", size(*0.35) justification(left) placement(e)) ///
	text(32 0.39 "`total_exp_32'", size(*0.35) justification(right) placement(w)) ///
	text(32 3.9 "`_ES_32_f' (`_LCI_32_f' – `_UCI_32_f')", size(*0.35) justification(left) placement(e)) ///
	text(32 5.4 "`WT_32_f'", size(*0.35) justification(right) placement(w)) ///
		text(33 0.22 "`_LABELS33'", size(*0.35) justification(left) placement(e)) ///
	text(33 0.39 "`total_exp_33'", size(*0.35) justification(right) placement(w)) ///
	text(33 3.9 "`_ES_33_f' (`_LCI_33_f' – `_UCI_33_f')", size(*0.35) justification(left) placement(e)) ///
	text(33 5.4 "`WT_33_f'", size(*0.35) justification(right) placement(w)) ///
		text(34 0.22 "`_LABELS34'", size(*0.35) justification(left) placement(e)) ///
	text(34 0.39 "`total_exp_34'", size(*0.35) justification(right) placement(w)) ///
	text(34 3.9 "`_ES_34_f' (`_LCI_34_f' – `_UCI_34_f')", size(*0.35) justification(left) placement(e)) ///
	text(34 5.4 "`WT_34_f'", size(*0.35) justification(right) placement(w)) ///
	text(35 0.21 "`_LABELS35'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(35 3.9 "`_ES_35_f' (`_LCI_35_f' – `_UCI_35_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(35 5.4 "`WT_35_f'", size(*0.35) justification(right) placement(w)) ///
	text(37 0.21 "{bf:Amitriptyline}", size(*0.35) justification(left) placement(e)) ///
		text(38 0.22 "`_LABELS38'", size(*0.35) justification(left) placement(e)) ///
	text(38 0.39 "`total_exp_38'", size(*0.35) justification(right) placement(w)) ///
	text(38 3.9 "`_ES_38_f' (`_LCI_38_f' – `_UCI_38_f')", size(*0.35) justification(left) placement(e)) ///
	text(38 5.4 "`WT_38_f'", size(*0.35) justification(right) placement(w)) ///
		text(39 0.22 "`_LABELS39'", size(*0.35) justification(left) placement(e)) ///
	text(39 0.39 "`total_exp_39'", size(*0.35) justification(right) placement(w)) ///
	text(39 3.9 "`_ES_39_f' (`_LCI_39_f' – `_UCI_39_f')", size(*0.35) justification(left) placement(e)) ///
	text(39 5.4 "`WT_39_f'", size(*0.35) justification(right) placement(w)) ///
		text(40 0.22 "`_LABELS40'", size(*0.35) justification(left) placement(e)) ///
	text(40 0.39 "`total_exp_40'", size(*0.35) justification(right) placement(w)) ///
	text(40 5.4 "`WT_40_f'", size(*0.35) justification(right) placement(w)) ///
	text(40 3.9 "`_ES_40_f' (`_LCI_40_f' – `_UCI_40_f')", size(*0.35) justification(left) placement(e)) ///
	text(41 0.21 "`_LABELS41'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(41 3.9 "`_ES_41_f' (`_LCI_41_f' – `_UCI_41_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(41 5.4 "`WT_41_f'", size(*0.35) justification(right) placement(w)) ///
	text(43 0.21 "{bf:Paroxetine}", size(*0.35) justification(left) placement(e)) ///
		text(44 0.22 "`_LABELS44'", size(*0.35) justification(left) placement(e)) ///
	text(44 0.39 "`total_exp_44'", size(*0.35) justification(right) placement(w)) ///
	text(44 3.9 "`_ES_44_f' (`_LCI_44_f' – `_UCI_44_f')", size(*0.35) justification(left) placement(e)) ///
	text(44 5.4 "`WT_44_f'", size(*0.35) justification(right) placement(w)) ///
		text(45 0.22 "`_LABELS45'", size(*0.35) justification(left) placement(e)) ///
	text(45 0.39 "`total_exp_45'", size(*0.35) justification(right) placement(w)) ///
	text(45 3.9 "`_ES_45_f' (`_LCI_45_f' – `_UCI_45_f')", size(*0.35) justification(left) placement(e)) ///
	text(45 5.4 "`WT_45_f'", size(*0.35) justification(right) placement(w)) ///
		text(46 0.22 "`_LABELS46'", size(*0.35) justification(left) placement(e)) ///
	text(46 0.39 "`total_exp_46'", size(*0.35) justification(right) placement(w)) ///
	text(46 3.9 "`_ES_46_f' (`_LCI_46_f' – `_UCI_46_f')", size(*0.35) justification(left) placement(e)) ///
	text(46 5.4 "`WT_46_f'", size(*0.35) justification(right) placement(w)) ///
	text(47 0.21 "`_LABELS47'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(47 3.9 "`_ES_47_f' (`_LCI_47_f' – `_UCI_47_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(47 5.4 "`WT_47_f'", size(*0.35) justification(right) placement(w)) ///
	text(49 0.21 "{bf:Duloxetine}", size(*0.35) justification(left) placement(e)) ///
		text(50 0.22 "`_LABELS50'", size(*0.35) justification(left) placement(e)) ///
	text(50 0.39 "`total_exp_50'", size(*0.35) justification(right) placement(w)) ///
	text(50 3.9 "`_ES_50_f' (`_LCI_50_f' – `_UCI_50_f')", size(*0.35) justification(left) placement(e)) ///
	text(50 5.4 "`WT_50_f'", size(*0.35) justification(right) placement(w)) ///
		text(51 0.22 "`_LABELS51'", size(*0.35) justification(left) placement(e)) ///
	text(51 0.39 "`total_exp_51'", size(*0.35) justification(right) placement(w)) ///
	text(51 3.9 "`_ES_51_f' (`_LCI_51_f' – `_UCI_51_f')", size(*0.35) justification(left) placement(e)) ///
	text(51 5.4 "`WT_51_f'", size(*0.35) justification(right) placement(w)) ///
		text(52 0.22 "`_LABELS52'", size(*0.35) justification(left) placement(e)) ///
	text(52 0.39 "`total_exp_52'", size(*0.35) justification(right) placement(w)) ///
	text(52 3.9 "`_ES_52_f' (`_LCI_52_f' – `_UCI_52_f')", size(*0.35) justification(left) placement(e)) ///
	text(52 5.4 "`WT_52_f'", size(*0.35) justification(right) placement(w)) ///
	text(53 0.21 "`_LABELS53'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(53 3.9 "`_ES_53_f' (`_LCI_53_f' – `_UCI_53_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(53 5.4 "`WT_53_f'", size(*0.35) justification(right) placement(w)) ///
	text(55 0.21 "{bf:Other}", size(*0.35) justification(left) placement(e)) ///
		text(56 0.22 "`_LABELS56'", size(*0.35) justification(left) placement(e)) ///
	text(56 0.39 "`total_exp_56'", size(*0.35) justification(right) placement(w)) ///
	text(56 3.9 "`_ES_56_f' (`_LCI_56_f' – `_UCI_56_f')", size(*0.35) justification(left) placement(e)) ///
	text(56 5.4 "`WT_56_f'", size(*0.35) justification(right) placement(w)) ///
		text(57 0.22 "`_LABELS57'", size(*0.35) justification(left) placement(e)) ///
	text(57 0.39 "`total_exp_57'", size(*0.35) justification(right) placement(w)) ///
	text(57 3.9 "`_ES_57_f' (`_LCI_57_f' – `_UCI_57_f')", size(*0.35) justification(left) placement(e)) ///
	text(57 5.4 "`WT_57_f'", size(*0.35) justification(right) placement(w)) ///
		text(58 0.22 "`_LABELS58'", size(*0.35) justification(left) placement(e)) ///
	text(58 0.39 "`total_exp_58'", size(*0.35) justification(right) placement(w)) ///
	text(58 3.9 "`_ES_58_f' (`_LCI_58_f' – `_UCI_58_f')", size(*0.35) justification(left) placement(e)) ///
	text(58 5.4 "`WT_58_f'", size(*0.35) justification(right) placement(w)) ///
	text(59 0.21 "`_LABELS59'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(59 3.9 "`_ES_59_f' (`_LCI_59_f' – `_UCI_59_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(59 5.4 "`WT_59_f'", size(*0.35) justification(right) placement(w)) ///
	text(61 0.21 "{bf:Polytherapy}", size(*0.35) justification(left) placement(e)) ///
		text(62 0.22 "`_LABELS62'", size(*0.35) justification(left) placement(e)) ///
	text(62 0.39 "`total_exp_62'", size(*0.35) justification(right) placement(w)) ///
	text(62 3.9 "`_ES_62_f' (`_LCI_62_f' – `_UCI_62_f')", size(*0.35) justification(left) placement(e)) ///
	text(62 5.4 "`WT_62_f'", size(*0.35) justification(right) placement(w)) ///
		text(63 0.22 "`_LABELS63'", size(*0.35) justification(left) placement(e)) ///
	text(63 0.39 "`total_exp_63'", size(*0.35) justification(right) placement(w)) ///
	text(63 3.9 "`_ES_63_f' (`_LCI_63_f' – `_UCI_63_f')", size(*0.35) justification(left) placement(e)) ///
	text(63 5.4 "`WT_63_f'", size(*0.35) justification(right) placement(w)) ///
		text(64 0.22 "`_LABELS64'", size(*0.35) justification(left) placement(e)) ///
	text(64 0.39 "`total_exp_64'", size(*0.35) justification(right) placement(w)) ///
	text(64 3.9 "`_ES_64_f' (`_LCI_64_f' – `_UCI_64_f')", size(*0.35) justification(left) placement(e)) ///
	text(64 5.4 "`WT_64_f'", size(*0.35) justification(right) placement(w)) ///
	text(65 0.21 "`_LABELS65'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(65 3.9 "`_ES_65_f' (`_LCI_65_f' – `_UCI_65_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(65 5.4 "`WT_65_f'", size(*0.35) justification(right) placement(w)) ///
	text(72 0.9 "{bf:Odds ratio* (95% confidence interval)}" "from logistic regression", size(*0.45)) ///
	text(74.1 0.9 "from fixed effects meta-analysis", size(*0.45) color(cranberry)) ///
	text(74 0.21 "*Adjusted for year of birth, maternal age, previous stillbirth, parity," "antipsychotic and anti-seizure medication use before pregnancy, depression," "anxiety, practice-level IMD and ethnicity (UK), maternal educational attainment" "and country of birth (Norway and Sweden), household disposable income" "(Sweden), smoking during pregnancy (UK and Sweden), maternal BMI" "(Sweden), number of primary care consultations before pregnancy (UK and" "Norway)", size(*0.35) justification(left) placement(e)) ///
	name(sga, replace)
	
	* Save graph
	
	graph export "C:\Users\ti19522\OneDrive - University of Bristol\Flo Martin Supervisory Team\Year 4\6_Birth outcomes\supplementary figures\sga_drug_ma.pdf", replace
	
********************************************************************************

* Load in the data
	
	use "$Graphdir\data\drug analyses data_all3.dta", clear
	
	keep if outcome=="apgar5_bin"
	
	gen drug_str=""
	replace drug_str= "a_unexposed" if drug==0
	replace drug_str= "b_sertraline" if drug==1
	replace drug_str= "c_citalopram" if drug==2
	replace drug_str= "d_fluoxetine" if drug==3
	replace drug_str= "e_escitalopram" if drug==4
	replace drug_str= "f_venlafaxine" if drug==5
	replace drug_str= "g_mirtazapine" if drug==6
	replace drug_str= "h_amitriptyline" if drug==7
	replace drug_str= "i_paroxetine" if drug==8
	replace drug_str= "j_duloxetine" if drug==9
	replace drug_str= "k_other" if drug==10
	replace drug_str= "l_Polytherapy" if drug==11
	
	gen logor = log(or)
	gen loglci = log(lci)
	gen loguci = log(uci)
	
	metan logor loglci loguci, eform by(drug_str) lcols(country total_exp) xlabel(0.5(0.5)2.5) saving(apgar_ma, replace)
	
	use apgar_ma, clear
	
	bys _BY _USE : egen grp_wt = sum(_WT)
	gen pct_grp_wt = 100 * _WT / grp_wt
	
	drop _WT
	rename pct_grp_wt _WT
	
	drop if _USE>=4 & _USE<6
	*drop if _BY==2 & _USE==3
	
	replace _LABELS = "Sertraline" if _LABELS=="b_sertraline"
	replace _LABELS = "Citalopram" if _LABELS=="c_citalopram"
	replace _LABELS = "Fluoxetine" if _LABELS=="d_fluoxetine"
	replace _LABELS = "Escitalopram" if _LABELS=="e_escitalopram"
	replace _LABELS = "Venlafaxine" if _LABELS=="f_venlafaxine"
	replace _LABELS = "Mirtazapine" if _LABELS=="g_mirtazapine"
	replace _LABELS = "Amitriptyline" if _LABELS=="h_amitriptyline"
	replace _LABELS = "Paroxetine" if _LABELS=="i_paroxetine"
	replace _LABELS = "Duloxetine" if _LABELS=="j_duloxetine"
	replace _LABELS = "Other" if _LABELS=="k_other"
	replace _LABELS = "Polypharmacy" if _LABELS=="l_Polytherapy"
	
	replace _LABELS = "Norway" if _LABELS=="no"
	replace _LABELS = "Sweden" if _LABELS=="se" 
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf:Drug prescribed / dispensed during pregnancy}"'"'
	label variable total_exp `"`"{bf: n/N}"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	format _ES %4.1fc
	format _WT %4.1fc
	
	*drop if _USE==1
	
	gen country=1 if _LABELS=="UK"
	replace country=2 if _LABELS=="Norway"
	replace country=3 if _LABELS=="Sweden"

	forestplot, eform effect("{bf}Odds ratio") null(1) olineopts(lcolor(none)) lcols(total_exp) nlineopts(lcolor(cranberry) lpattern(dash)) xlabel(0.5(0.5)4.5) title("{bf}Drug-specific analysis for low Apgar score", size(small)) ///
	plotid(country, list) point1opts(msymbol(circle) msize(0.75)) point2opts(msymbol(diamond) msize(0.75)) ///
	textsize(105) cirange(0.5 4) name(apgar_ma, replace)
	
	* Save graph
	
	cd "$Graphdir"
	graph export apgar_drug_ma.pdf, replace 
	
	egen seq=seq()
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	replace _ES = exp(_ES)
	replace _LCI = exp(_LCI)
	replace _UCI = exp(_UCI) 
	
	replace _ES=10 if _ES==.
	replace _LCI=10 if _LCI==.
	replace _UCI=10 if _UCI==.
	
	
	forvalues x=2/55 {
		foreach y in _ES _LCI _UCI {
		
			sum `y' if seq==`x'
			local `y'_`x' = `r(mean)'
			local `y'_`x'_f : display %4.2fc ``y'_`x'' 
			
		}		
	}
	
	replace _ES=. if _ES==10
	replace _LCI=. if _LCI==10
	replace _UCI=. if _UCI==10
	
	forvalues x=2/55 {
	
		local total_exp_`x' = total_exp[`x']
		di "`total_exp_`x''"
		
	}
	
	forvalues x=2/55 {
	
		local _LABELS`x' = _LABELS[`x']
		di "`_LABELS`x''"
		
	}
	
	replace _WT=10 if _WT==.
	
	forvalues x=2/55 {
	
		sum _WT if seq==`x'
		local WT_`x' = `r(mean)'
		local WT_`x'_f : display %4.1fc `WT_`x''
		disp "`WT_`x'_f'"
		
	}
	
	replace _WT=. if _WT==10
	
	* Macros to create the null line
	local t1=0
	local t2=55
	
	* Capped CI
	
	gen cap=27 if seq==27
	replace cap=37 if seq==37
	replace cap=42 if seq==42
	
	gen lci=0.4 if seq==27 | seq==37 
	gen uci=3.8 if seq==42
	
	foreach x in 27 37 {
		
		gen lci_cap_`x'=`_UCI_`x'' if seq==`x'
		gen uci_cap_`x'=`_UCI_`x'' if seq==`x'
		
	}
	
	gen lci_cap_42=`_LCI_42' if seq==42
	gen uci_cap_42=`_LCI_42' if seq==42 
	
	tw ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap _LCI _UCI seq if _USE==1 & seq!=27 & seq!=37 & seq!=42, horizontal lcolor(black) mlw(thin) msize(*0.5)) /// code for NO 95% CI
	(rcap _LCI _UCI seq if _USE==3, horizontal mlcolor(cranberry) lcolor(cranberry) mlw(thin) msize(*0.5)) ///
	(rcap lci_cap_27 uci_cap_27 seq, horizontal lcolor(black) mlw(thin) msize(*0.5)) ///
	(pcarrow cap _UCI cap lci if seq==27, lcolor(black) mcolor(black) msize(*0.5)) ///
	(rcap lci_cap_37 uci_cap_37 seq, horizontal lcolor(black) mlw(thin) msize(*0.5)) ///
	(pcarrow cap _UCI cap lci if seq==37, lcolor(black) mcolor(black) msize(*0.5)) ///
	(rcap lci_cap_42 uci_cap_42 seq, horizontal lcolor(black) mlw(thin) msize(*0.5)) ///
	(pcarrow cap _LCI cap uci if seq==42, lcolor(black) mcolor(black) msize(*0.5)) ///
	(scatter seq _ES if _LABELS=="Norway", mcolor("217 142 98") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Sweden", mcolor("168 210 218") ms(o) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _USE==3, mcolor(cranberry) ms(d) msize(small) mcolor(white) mlcolor(cranberry) mlw(thin)), ///
	yscale(range(-2.2 55) reverse noline) ylab("", angle(0) labsize(*0.6) notick nogrid nogextend) /// 
	legend(order(10 "Norway" 11 "Sweden" 12 "Overall") region(lcolor(black)) pos(5) size(*0.75)) ///
	yline(-3) yline(0) yline(5, lcolor(gray) lpattern(dot)) yline(10, lcolor(gray) lpattern(dot)) yline(15, lcolor(gray) lpattern(dot)) yline(20, lcolor(gray) lpattern(dot)) yline(25, lcolor(gray) lpattern(dot)) yline(30, lcolor(gray) lpattern(dot)) yline(35, lcolor(gray) lpattern(dot)) yline(40, lcolor(gray) lpattern(dot)) yline(45, lcolor(gray) lpattern(dot)) yline(50, lcolor(gray) lpattern(dot)) ///
	xscale(range(0.21 5.5) log) xlab(0.4(0.2)3.8, labsize(*0.55) format(%3.1fc) angle(45))  ///
	graphregion(color(white) fcolor(white) ifcolor(white) lcolor(white)) plotregion(margin(1 1 0 1)) ///
	title("{bf}Antidepressant use during pregnancy and low Apgar score (<7) in Norway & Sweden", size(small)) ///
	text(-1.5 3.9 "{bf}aOR* (95% CI)", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 4.8 "{bf}Weight (%)", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 0.21 "{bf}Antidepressant" "Country", size(*0.35) justification(left) placement(e)) ///
	text(-1.5 0.39 "{bf}Low Apgar / Total exposed" "{it:n} / N", size(*0.35) justification(right) placement(w)) ///
	text(1 0.21 "{bf:Sertraline}", size(*0.35) justification(left) placement(e)) ///
		text(2 0.22 "`_LABELS2'", size(*0.35) justification(left) placement(e)) ///
	text(2 0.39 "`total_exp_2'", size(*0.35) justification(right) placement(w)) ///
	text(2 3.9 "`_ES_2_f' (`_LCI_2_f' – `_UCI_2_f')", size(*0.35) justification(left) placement(e)) ///
	text(2 5.4 "`WT_2_f'", size(*0.35) justification(right) placement(w)) ///
		text(3 0.22 "`_LABELS3'", size(*0.35) justification(left) placement(e)) ///
	text(3 0.39 "`total_exp_3'", size(*0.35) justification(right) placement(w)) ///
	text(3 3.9 "`_ES_3_f' (`_LCI_3_f' – `_UCI_3_f')", size(*0.35) justification(left) placement(e)) ///
	text(3 5.4 "`WT_3_f'", size(*0.35) justification(right) placement(w)) ///
	text(4 0.21 "`_LABELS4'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(4 3.9 "`_ES_4_f' (`_LCI_4_f' – `_UCI_4_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(4 5.4 "`WT_4_f'", size(*0.35) justification(right) placement(w)) ///
	text(6 0.21 "{bf:Citalopram}", size(*0.35) justification(left) placement(e)) ///
		text(7 0.22 "`_LABELS7'", size(*0.35) justification(left) placement(e)) ///
	text(7 0.39 "`total_exp_7'", size(*0.35) justification(right) placement(w)) ///
	text(7 3.9 "`_ES_7_f' (`_LCI_7_f' – `_UCI_7_f')", size(*0.35) justification(left) placement(e)) ///
	text(7 5.4 "`WT_7_f'", size(*0.35) justification(right) placement(w)) ///
		text(8 0.22 "`_LABELS8'", size(*0.35) justification(left) placement(e)) ///
	text(8 0.39 "`total_exp_8'", size(*0.35) justification(right) placement(w)) ///
	text(8 3.9 "`_ES_8_f' (`_LCI_8_f' – `_UCI_8_f')", size(*0.35) justification(left) placement(e)) ///
	text(8 5.4 "`WT_8_f'", size(*0.35) justification(right) placement(w)) ///
		text(9 0.21 "`_LABELS9'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(9 3.9 "`_ES_9_f' (`_LCI_9_f' – `_UCI_9_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(9 5.4 "`WT_9_f'", size(*0.35) justification(right) placement(w)) ///
	text(11 0.21 "{bf:Fluoxetine}", size(*0.35) justification(left) placement(e)) ///
		text(12 0.22 "`_LABELS12'", size(*0.35) justification(left) placement(e)) ///
	text(12 0.39 "`total_exp_12'", size(*0.35) justification(right) placement(w)) ///
	text(12 3.9 "`_ES_12_f' (`_LCI_12_f' – `_UCI_12_f')", size(*0.35) justification(left) placement(e)) ///
	text(12 5.4 "`WT_12_f'", size(*0.35) justification(right) placement(w)) ///
		text(13 0.22 "`_LABELS13'", size(*0.35) justification(left) placement(e)) ///
	text(13 0.39 "`total_exp_13'", size(*0.35) justification(right) placement(w)) ///
	text(13 3.9 "`_ES_13_f' (`_LCI_13_f' – `_UCI_13_f')", size(*0.35) justification(left) placement(e)) ///
	text(13 5.4 "`WT_13_f'", size(*0.35) justification(right) placement(w)) ///
		text(14 0.21 "`_LABELS14'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(14 3.9 "`_ES_14_f' (`_LCI_14_f' – `_UCI_14_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(14 5.4 "`WT_14_f'", size(*0.35) justification(right) placement(w)) ///
	text(16 0.21 "{bf:Escitalopram}", size(*0.35) justification(left) placement(e)) ///
		text(17 0.22 "`_LABELS17'", size(*0.35) justification(left) placement(e)) ///
	text(17 0.39 "`total_exp_17'", size(*0.35) justification(right) placement(w)) ///
	text(17 3.9 "`_ES_17_f' (`_LCI_17_f' – `_UCI_17_f')", size(*0.35) justification(left) placement(e)) ///
	text(17 5.4 "`WT_17_f'", size(*0.35) justification(right) placement(w)) ///
		text(18 0.22 "`_LABELS18'", size(*0.35) justification(left) placement(e)) ///
	text(18 0.39 "`total_exp_18'", size(*0.35) justification(right) placement(w)) ///
	text(18 3.9 "`_ES_18_f' (`_LCI_18_f' – `_UCI_18_f')", size(*0.35) justification(left) placement(e)) ///
	text(18 5.4 "`WT_18_f'", size(*0.35) justification(right) placement(w)) ///
		text(19 0.21 "`_LABELS19'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(19 3.9 "`_ES_19_f' (`_LCI_19_f' – `_UCI_19_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(19 5.4 "`WT_19_f'", size(*0.35) justification(right) placement(w)) ///
	text(21 0.21 "{bf:Venlafaxine}", size(*0.35) justification(left) placement(e)) ///
		text(22 0.22 "`_LABELS22'", size(*0.35) justification(left) placement(e)) ///
	text(22 0.39 "`total_exp_22'", size(*0.35) justification(right) placement(w)) ///
	text(22 5.4 "`WT_22_f'", size(*0.35) justification(right) placement(w)) ///
	text(22 3.9 "`_ES_22_f' (`_LCI_22_f' – `_UCI_22_f')", size(*0.35) justification(left) placement(e)) ///
		text(23 0.22 "`_LABELS23'", size(*0.35) justification(left) placement(e)) ///
	text(23 0.39 "`total_exp_23'", size(*0.35) justification(right) placement(w)) ///
	text(23 3.9 "`_ES_23_f' (`_LCI_23_f' – `_UCI_23_f')", size(*0.35) justification(left) placement(e)) ///
	text(23 5.4 "`WT_23_f'", size(*0.35) justification(right) placement(w)) ///
		text(24 0.21 "`_LABELS24'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(24 3.9 "`_ES_24_f' (`_LCI_24_f' – `_UCI_24_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(24 5.4 "`WT_24_f'", size(*0.35) justification(right) placement(w)) ///
	text(26 0.21 "{bf:Mirtazapine}", size(*0.35) justification(left) placement(e)) ///
		text(27 0.22 "`_LABELS27'", size(*0.35) justification(left) placement(e)) ///
	text(27 0.39 "`total_exp_27'", size(*0.35) justification(right) placement(w)) ///
	text(27 3.9 "`_ES_27_f' (`_LCI_27_f' – `_UCI_27_f')", size(*0.35) justification(left) placement(e)) ///
	text(27 5.4 "`WT_27_f'", size(*0.35) justification(right) placement(w)) ///
		text(28 0.22 "`_LABELS28'", size(*0.35) justification(left) placement(e)) ///
	text(28 0.39 "`total_exp_28'", size(*0.35) justification(right) placement(w)) ///
	text(28 3.9 "`_ES_28_f' (`_LCI_28_f' – `_UCI_28_f')", size(*0.35) justification(left) placement(e)) ///
	text(28 5.4 "`WT_28_f'", size(*0.35) justification(right) placement(w)) ///
		text(29 0.21 "`_LABELS29'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(29 3.9 "`_ES_29_f' (`_LCI_29_f' – `_UCI_29_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(29 5.4 "`WT_29_f'", size(*0.35) justification(right) placement(w)) ///
	text(31 0.21 "{bf:Amitriptyline}", size(*0.35) justification(left) placement(e)) ///
		text(32 0.22 "`_LABELS32'", size(*0.35) justification(left) placement(e)) ///
	text(32 0.39 "`total_exp_32'", size(*0.35) justification(right) placement(w)) ///
	text(32 3.9 "`_ES_32_f' (`_LCI_32_f' – `_UCI_32_f')", size(*0.35) justification(left) placement(e)) ///
	text(32 5.4 "`WT_32_f'", size(*0.35) justification(right) placement(w)) ///
		text(33 0.22 "`_LABELS33'", size(*0.35) justification(left) placement(e)) ///
	text(33 0.39 "`total_exp_33'", size(*0.35) justification(right) placement(w)) ///
	text(33 3.9 "`_ES_33_f' (`_LCI_33_f' – `_UCI_33_f')", size(*0.35) justification(left) placement(e)) ///
	text(33 5.4 "`WT_33_f'", size(*0.35) justification(right) placement(w)) ///
		text(34 0.21 "`_LABELS34'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(34 3.9 "`_ES_34_f' (`_LCI_34_f' – `_UCI_34_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(34 5.4 "`WT_34_f'", size(*0.35) justification(right) placement(w)) ///
	text(36 0.21 "{bf:Paroxetine}", size(*0.35) justification(left) placement(e)) ///
		text(37 0.22 "`_LABELS37'", size(*0.35) justification(left) placement(e)) ///
	text(37 0.39 "`total_exp_37'", size(*0.35) justification(right) placement(w)) ///
	text(37 3.9 "`_ES_37_f' (`_LCI_37_f' – `_UCI_37_f')", size(*0.35) justification(left) placement(e)) ///
	text(37 5.4 "`WT_37_f'", size(*0.35) justification(right) placement(w)) ///
		text(38 0.22 "`_LABELS38'", size(*0.35) justification(left) placement(e)) ///
	text(38 0.39 "`total_exp_38'", size(*0.35) justification(right) placement(w)) ///
	text(38 3.9 "`_ES_38_f' (`_LCI_38_f' – `_UCI_38_f')", size(*0.35) justification(left) placement(e)) ///
	text(38 5.4 "`WT_38_f'", size(*0.35) justification(right) placement(w)) ///
		text(39 0.21 "`_LABELS39'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(39 3.9 "`_ES_39_f' (`_LCI_39_f' – `_UCI_39_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(39 5.4 "`WT_39_f'", size(*0.35) justification(right) placement(w)) ///
	text(41 0.21 "{bf:Duloxetine}", size(*0.35) justification(left) placement(e)) ///
		text(42 0.22 "`_LABELS42'", size(*0.35) justification(left) placement(e)) ///
	text(42 0.39 "`total_exp_42'", size(*0.35) justification(right) placement(w)) ///
	text(42 3.9 "`_ES_42_f' (`_LCI_42_f' – `_UCI_42_f')", size(*0.35) justification(left) placement(e)) ///
	text(42 5.4 "`WT_42_f'", size(*0.35) justification(right) placement(w)) ///
		text(43 0.22 "`_LABELS43'", size(*0.35) justification(left) placement(e)) ///
	text(43 0.39 "`total_exp_43'", size(*0.35) justification(right) placement(w)) ///
	text(43 3.9 "`_ES_43_f' (`_LCI_43_f' – `_UCI_43_f')", size(*0.35) justification(left) placement(e)) ///
	text(43 5.4 "`WT_43_f'", size(*0.35) justification(right) placement(w)) ///
		text(44 0.21 "`_LABELS44'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(44 3.9 "`_ES_44_f' (`_LCI_44_f' – `_UCI_44_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(44 5.4 "`WT_44_f'", size(*0.35) justification(right) placement(w)) ///
	text(46 0.21 "{bf:Other}", size(*0.35) justification(left) placement(e)) ///
		text(47 0.22 "`_LABELS47'", size(*0.35) justification(left) placement(e)) ///
	text(47 0.39 "`total_exp_47'", size(*0.35) justification(right) placement(w)) ///
	text(47 3.9 "`_ES_47_f' (`_LCI_47_f' – `_UCI_47_f')", size(*0.35) justification(left) placement(e)) ///
	text(47 5.4 "`WT_47_f'", size(*0.35) justification(right) placement(w)) ///
		text(48 0.22 "`_LABELS48'", size(*0.35) justification(left) placement(e)) ///
	text(48 0.39 "`total_exp_48'", size(*0.35) justification(right) placement(w)) ///
	text(48 3.9 "`_ES_48_f' (`_LCI_48_f' – `_UCI_48_f')", size(*0.35) justification(left) placement(e)) ///
	text(48 5.4 "`WT_48_f'", size(*0.35) justification(right) placement(w)) ///
		text(49 0.21 "`_LABELS49'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(49 3.9 "`_ES_49_f' (`_LCI_49_f' – `_UCI_49_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(49 5.4 "`WT_49_f'", size(*0.35) justification(right) placement(w)) ///
	text(51 0.21 "{bf:Polytherapy}", size(*0.35) justification(left) placement(e)) ///
		text(52 0.22 "`_LABELS52'", size(*0.35) justification(left) placement(e)) ///
	text(52 0.39 "`total_exp_52'", size(*0.35) justification(right) placement(w)) ///
	text(52 3.9 "`_ES_52_f' (`_LCI_52_f' – `_UCI_52_f')", size(*0.35) justification(left) placement(e)) ///
	text(52 5.4 "`WT_52_f'", size(*0.35) justification(right) placement(w)) ///
		text(53 0.22 "`_LABELS53'", size(*0.35) justification(left) placement(e)) ///
	text(53 0.39 "`total_exp_53'", size(*0.35) justification(right) placement(w)) ///
	text(53 3.9 "`_ES_53_f' (`_LCI_53_f' – `_UCI_53_f')", size(*0.35) justification(left) placement(e)) ///
	text(53 5.4 "`WT_53_f'", size(*0.35) justification(right) placement(w)) ///
		text(54 0.21 "`_LABELS54'", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(54 3.9 "`_ES_54_f' (`_LCI_54_f' – `_UCI_54_f')", size(*0.35) justification(left) placement(e) color(cranberry)) ///
	text(54 5.4 "`WT_54_f'", size(*0.35) justification(right) placement(w)) ///
	text(60 1 "{bf:Odds ratio* (95% confidence interval)}" "from logistic regression", size(*0.45)) ///
	text(61.75 1 "from fixed effects meta-analysis", size(*0.45) color(cranberry)) ///
	text(61.5 0.21 "*Adjusted for year of birth, maternal age, previous stillbirth, parity," "antipsychotic and anti-seizure medication use before pregnancy, depression," "anxiety, practice-level IMD and ethnicity (UK), maternal educational attainment" "and country of birth (Norway and Sweden), household disposable income" "(Sweden), smoking during pregnancy (UK and Sweden), maternal BMI" "(Sweden), number of primary care consultations before pregnancy (UK and" "Norway)", size(*0.35) justification(left) placement(e)) ///
	name(apgar, replace)
	
	* Save graph
	
	graph export "C:\Users\ti19522\OneDrive - University of Bristol\Flo Martin Supervisory Team\Year 4\6_Birth outcomes\supplementary figures\apgar_drug_ma.pdf", replace

********************************************************************************

/* Use the data from metan to make make figure
	
	use preterm_ma, clear
	
	gen or_preterm=exp(_ES)
	gen lci_preterm=exp(_LCI)
	gen uci_preterm=exp(_UCI)
	
	keep _BY _USE _STUDY *_preterm
	
	merge 1:1 _BY _USE _STUDY using sga_ma, nogen
	
	gen or_sga=exp(_ES)
	gen lci_sga=exp(_LCI)
	gen uci_sga=exp(_UCI)
	
	keep _BY _USE _STUDY *_preterm *_sga
	
	merge 1:1 _BY _USE _STUDY using apgar_ma, nogen
	
	gen or_apgar=exp(_ES)
	gen lci_apgar=exp(_LCI)
	gen uci_apgar=exp(_UCI)
	
	keep if _USE==3 
	keep _BY _USE _STUDY *_preterm *_sga *_apgar
	
	egen row_sga = seq()
	gen row_preterm = row_sga-0.3
	gen row_apgar = row_sga+0.3
	
	gen x=2.2
	gen y=0
	
	gen drug=""
	replace drug="sertraline" if _BY==2
	replace drug="citalopram" if _BY==3
	replace drug="fluoxetine" if _BY==4
	replace drug="escitalopram" if _BY==5
	replace drug="venlafaxine" if _BY==6
	replace drug="mirtazapine" if _BY==7
	replace drug="amitriptyline" if _BY==8
	replace drug="paroxetine" if _BY==9
	replace drug="duloxetine" if _BY==10
	replace drug="other" if _BY==11
	replace drug="polypharmacy" if _BY==12
	
	save "$Graphdir\data\summary drug ests.dta", replace
	
* Create the forest plot chunks for the odds ratios and 95%CIs

* Preterm delivery
	
	* Load in the data
	use "$Graphdir\data\summary drug ests.dta", clear
	
	* Macros for the OR text
	foreach country in sertraline citalopram fluoxetine escitalopram venlafaxine mirtazapine amitriptyline paroxetine duloxetine other polypharmacy {
		foreach outcome in preterm sga apgar {
			
			sum or_`outcome' if drug=="`country'"
			local `outcome'_`country'_or = `r(mean)'
			sum uci_`outcome' if drug=="`country'"
			local `outcome'_`country'_uci = `r(mean)'
			
			local `outcome'_`country'_or_fmt: display %3.2f ``outcome'_`country'_or'
			
			if ``outcome'_`country'_uci'<1.3 & ``outcome'_`country'_uci'>=0.95 {
			
				local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.12
			
			}
			
			else if ``outcome'_`country'_uci'<0.95 {
			
				local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.09
			
			}
		
			else {
		
			local `outcome'_`country'_pos=``outcome'_`country'_uci'+0.25
			
			}
			
		}
	}
	
	* Keep necessary variables and values
	keep _USE _BY _STUDY *preterm
	
	* Generate variables for second axis (to make box around the graph using scatter)
	gen x=11.3
	gen y=0.7
	
	egen row=seq()
	
	* Macros to create the null line
	local t1=0.5
	local t2=11.5
	
	* Make the graph chunk
	twoway ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) ///
	(rcap lci_preterm uci_preterm row, horizontal lcolor(black)) /// code for_no 95% CI
	(scatter row or_preterm, ms(S) msize(small) mlcolor(black) mcolor("204 146 194") mlw(thin)) ///
	, yline(1, lwidth(9) lc(gs12*0.5)) yline(3, lwidth(9) lc(gs12*0.5)) yline(5, lwidth(9) lc(gs12*0.5)) yline(7, lwidth(9) lc(gs12*0.5)) yline(9, lwidth(9) lc(gs12*0.5)) yline(11, lwidth(9) lc(gs12*0.5)) /// 
	legend(row(1) order(3 "Summary effect estimate") pos(6) size(vsmall)) || /// 
	scatter y x, msymbol(i) yaxis(2) xaxis(2) ylab("", axis(2) notick nolab) xlab(, axis(2) notick nolab) ytitle("", axis(2)) xtitle("", axis(2)) /// box around the graph
	xscale(log range(0.5 3.2)) xlabel(0.5 0.7 1 1.4 1.8 2.4 3.2, format(%3.1fc) angle(0) labsize(vsmall) nogrid nogextend) xtitle("{bf:Adjusted pooled odds ratio (95% CI)}", size(vsmall) color(black)) /// x axis
	yscale(reverse range(0.7 11.3)) ylabel(1 "{bf}Sertraline" 2 "{bf}Citalopram" 3 "{bf}Fluoxetine" 4 "{bf}Escitalopram" 5 "{bf}Venlafaxine" 6 "{bf}Mirtazapine" 7 "{bf}Amitriptyline" 8 "{bf}Paroxetine" 9 "{bf}Duloxetine" 10 "{bf}Other" 11 "{bf}Polypharmacy", angle(0) notick labsize(vsmall) nogrid nogextend) ytitle("") /// y axis
	title("{bf}Preterm delivery" "UK, Norway & Sweden", color(black) size(vsmall)) /// title
	plotregion(margin(zero)) ///
	graphregion(color(white) lcolor(black)) /// overall look
	text(1 `preterm_sertraline_pos' "{bf}`preterm_sertraline_or_fmt'", size(vsmall)) /// OR text for sertraline
	text(2 `preterm_citalopram_pos' "{bf}`preterm_citalopram_or_fmt'", size(vsmall)) /// OR text for citalopram
	text(3 `preterm_fluoxetine_pos' "{bf}`preterm_fluoxetine_or_fmt'", size(vsmall)) /// OR text for fluoxetine
	text(4 `preterm_escitalopram_pos' "{bf}`preterm_escitalopram_or_fmt'", size(vsmall)) /// OR text for postterm delivery
	text(5 `preterm_venlafaxine_pos' "{bf}`preterm_venlafaxine_or_fmt'", size(vsmall)) /// OR text for SGA
	text(6 `preterm_mirtazapine_pos' "{bf}`preterm_mirtazapine_or_fmt'", size(vsmall)) /// OR text for LGA
	text(7 `preterm_amitriptyline_pos' "{bf}`preterm_amitriptyline_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(8 `preterm_paroxetine_pos' "{bf}`preterm_paroxetine_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(9 `preterm_duloxetine_pos' "{bf}`preterm_duloxetine_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(10 `preterm_other_pos' "{bf}`preterm_other_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(11 `preterm_polypharmacy_pos' "{bf}`preterm_polypharmacy_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	fxsize(86) fysize(100) name(preterm_drug, replace)
	
* Small for gestational age
	
	* Load in the data
	* Load in the data
	use "$Graphdir\data\summary drug ests.dta", clear
	
	* Keep necessary variables and values
	keep _USE _BY _STUDY *sga
	
	* Generate variables for second axis (to make box around the graph using scatter)
	gen x=11.3
	gen y=0.7
	
	egen row=seq()
	
	* Macros to create the null line
	local t1=0.5
	local t2=11.5
	
	* Make the graph chunk
	twoway ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) ///
	(rcap lci_sga uci_sga row, horizontal lcolor(black)) /// code for_no 95% CI
	(scatter row or_sga, ms(S) msize(small) mlcolor(black) mcolor("137 49 104") mlw(thin)) ///
	, yline(1, lwidth(9) lc(gs12*0.5)) yline(3, lwidth(9) lc(gs12*0.5)) yline(5, lwidth(9) lc(gs12*0.5)) yline(7, lwidth(9) lc(gs12*0.5)) yline(9, lwidth(9) lc(gs12*0.5)) yline(11, lwidth(9) lc(gs12*0.5)) /// 
	legend(row(1) order(3 "Summary effect estimate") pos(6) size(vsmall)) || /// 
	scatter y x, msymbol(i) yaxis(2) xaxis(2) ylab("", axis(2) notick nolab) xlab(, axis(2) notick nolab) ytitle("", axis(2)) xtitle("", axis(2)) /// box around the graph
	xscale(log range(0.5 3.2)) xlabel(0.5 0.7 1 1.4 1.8 2.4 3.2, format(%3.1fc) angle(0) labsize(vsmall) nogrid nogextend) xtitle("{bf:Adjusted pooled odds ratio (95% CI)}", size(vsmall) color(black)) /// x axis
	yscale(reverse range(0.7 11.3)) ylabel("", angle(0) notick labsize(vsmall) nogrid nogextend) ytitle("") /// y axis
	title("{bf}Small for gestational age" "UK, Norway & Sweden", color(black) size(vsmall)) /// title
	plotregion(margin(zero)) ///
	graphregion(color(white) lcolor(black)) /// overall look
	text(1 `sga_sertraline_pos' "{bf}`sga_sertraline_or_fmt'", size(vsmall)) /// OR text for sertraline
	text(2 `sga_citalopram_pos' "{bf}`sga_citalopram_or_fmt'", size(vsmall)) /// OR text for citalopram
	text(3 `sga_fluoxetine_pos' "{bf}`sga_fluoxetine_or_fmt'", size(vsmall)) /// OR text for fluoxetine
	text(4 `sga_escitalopram_pos' "{bf}`sga_escitalopram_or_fmt'", size(vsmall)) /// OR text for postterm delivery
	text(5 `sga_venlafaxine_pos' "{bf}`sga_venlafaxine_or_fmt'", size(vsmall)) /// OR text for SGA
	text(6 `sga_mirtazapine_pos' "{bf}`sga_mirtazapine_or_fmt'", size(vsmall)) /// OR text for LGA
	text(7 `sga_amitriptyline_pos' "{bf}`sga_amitriptyline_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(8 `sga_paroxetine_pos' "{bf}`sga_paroxetine_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(9 `sga_duloxetine_pos' "{bf}`sga_duloxetine_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(10 `sga_other_pos' "{bf}`sga_other_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(11 `sga_polypharmacy_pos' "{bf}`sga_polypharmacy_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	fxsize(65) fysize(100) name(sga_drug, replace)
	
* Apgar score
	
	* Load in the data
	* Load in the data
	use "$Graphdir\data\summary drug ests.dta", clear
	
	* Keep necessary variables and values
	keep _USE _BY _STUDY *apgar
	
	* Generate variables for second axis (to make box around the graph using scatter)
	gen x=11.3
	gen y=0.7
	
	egen row=seq()
	
	* Macros to create the null line
	local t1=0.5
	local t2=11.5
	
	* Make the graph chunk
	twoway ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) ///
	(rcap lci_apgar uci_apgar row, horizontal lcolor(black)) /// code for_no 95% CI
	(scatter row or_apgar, ms(S) msize(small) mlcolor(black) mcolor("196 100 135") mlw(thin)) ///
	, yline(1, lwidth(9) lc(gs12*0.5)) yline(3, lwidth(9) lc(gs12*0.5)) yline(5, lwidth(9) lc(gs12*0.5)) yline(7, lwidth(9) lc(gs12*0.5)) yline(9, lwidth(9) lc(gs12*0.5)) yline(11, lwidth(9) lc(gs12*0.5)) /// 
	legend(row(1) order(3 "Summary effect estimate (Norway & Sweden)") pos(6) size(vsmall)) || /// 
	scatter y x, msymbol(i) yaxis(2) xaxis(2) ylab("", axis(2) notick nolab) xlab(, axis(2) notick nolab) ytitle("", axis(2)) xtitle("", axis(2)) /// box around the graph
	xscale(log range(0.5 3.2)) xlabel(0.5 0.7 1 1.4 1.8 2.4 3.2, format(%3.1fc) angle(0) labsize(vsmall) nogrid nogextend) xtitle("{bf:Adjusted pooled odds ratio (95% CI)}", size(vsmall) color(black)) /// x axis
	yscale(reverse range(0.7 11.3)) ylabel("", angle(0) notick labsize(vsmall) nogrid nogextend) ytitle("") /// y axis
	title("{bf}Low Apgar score (5 minutes)" "Norway & Sweden", color(black) size(vsmall)) /// title
	plotregion(margin(zero)) ///  
	graphregion(color(white) lcolor(black)) /// overall look
	text(1 `apgar_sertraline_pos' "{bf}`apgar_sertraline_or_fmt'", size(vsmall)) /// OR text for sertraline
	text(2 `apgar_citalopram_pos' "{bf}`apgar_citalopram_or_fmt'", size(vsmall)) /// OR text for citalopram
	text(3 `apgar_fluoxetine_pos' "{bf}`apgar_fluoxetine_or_fmt'", size(vsmall)) /// OR text for fluoxetine
	text(4 `apgar_escitalopram_pos' "{bf}`apgar_escitalopram_or_fmt'", size(vsmall)) /// OR text for postterm delivery
	text(5 `apgar_venlafaxine_pos' "{bf}`apgar_venlafaxine_or_fmt'", size(vsmall)) /// OR text for SGA
	text(6 `apgar_mirtazapine_pos' "{bf}`apgar_mirtazapine_or_fmt'", size(vsmall)) /// OR text for LGA
	text(7 `apgar_amitriptyline_pos' "{bf}`apgar_amitriptyline_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(8 `apgar_paroxetine_pos' "{bf}`apgar_paroxetine_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(9 `apgar_duloxetine_pos' "{bf}`apgar_duloxetine_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(10 `apgar_other_pos' "{bf}`apgar_other_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	text(11 `apgar_polypharmacy_pos' "{bf}`apgar_polypharmacy_or_fmt'", size(vsmall)) /// OR text for low Apgar score
	fxsize(65) fysize(100) name(apgar_drug, replace)
	
	graph combine preterm_drug sga_drug apgar_drug, col(3) title("{bf}Antidepressant-specific meta-analysis of UK, Norway & Sweden", color(black) size(small)) name(drug_specific_all3, replace)
	
********************************************************************************/

/*	use preterm_ma, clear
	gen model=1
	drop if _USE==0 | _USE==6
	
	append using sga_ma
	replace model=2 if model==.
	drop if _USE==0 | _USE==6
	
	append using apgar_ma
	replace model=3 if model==.
	
	label define model_lb 1"preterm" 2"sga" 3"apgar"
	label values model model_lb
	
	split total_exp, parse(" /") gen(exp_y)
	rename exp_y1 exp_y
	rename exp_y2 exp_total
	
	/*split total_unexp, parse(" /") gen(unexp_y)
	rename unexp_y1 unexp_y
	rename unexp_y2 unexp_total*/
	
	foreach x in exp_y exp_total {
	
		replace `x' = subinstr(`x', ",", "", .)
		gen `x'_num=real(`x')
		drop `x'
		rename `x'_num `x'
	
	}
	
	foreach x in exp_y exp_total {
	
		bysort _BY model: egen sum_`x'=total(`x')
		format sum_`x' %9.0fc
		
	}
	
	forvalues x=2/12 {
		forvalues y=1/3 {
		
			sum sum_exp_y if _BY==`x' & model==`y'
			local sum_exp_y = `r(max)'
			local sum_exp_y_fc : display %6.0fc `sum_exp_y'
			
			sum sum_exp_total if _BY==`x' & model==`y'
			local sum_exp_total = `r(max)'
			local sum_exp_total_fc : display %7.0fc `sum_exp_total'
			
			replace total_exp = "`sum_exp_y_fc' / `sum_exp_total_fc'" if _BY==`x' & _USE==3  & model==`y'
		
		}
	}
	
	replace total_exp = subinstr(total_exp, " ", "", .)
	*replace total_unexp = subinstr(total_unexp, " ", "", .)
	
	replace total_exp = subinstr(total_exp, "/", " / ", .)
	*replace total_unexp = subinstr(total_unexp, "/", " / ", .)
	
	keep if _USE!=1 & _USE!=4 & _USE!=5
	drop _STUDY
	sort _BY _USE model
	
	bys _BY _USE: egen grp_wt = sum(_WT)
	gen pct_grp_wt = 100 * _WT / grp_wt
		
	drop _WT
	rename pct_grp_wt _WT
	format _WT %4.2fc
	
	replace _LABELS="Preterm delivery" if model==1 & _USE==3
	replace _LABELS="Small for gestational age" if model==2 & _USE==3
	replace _LABELS="Low Apgar score" if model==3 & _USE==3
	
	replace _LABELS = "Sertraline" if _LABELS=="b_sertraline"
	replace _LABELS = "Citalopram" if _LABELS=="c_citalopram"
	replace _LABELS = "Fluoxetine" if _LABELS=="d_fluoxetine"
	replace _LABELS = "Escitalopram" if _LABELS=="e_escitalopram"
	replace _LABELS = "Venlafaxine" if _LABELS=="f_venlafaxine"
	replace _LABELS = "Mirtazapine" if _LABELS=="g_mirtazapine"
	replace _LABELS = "Amitriptyline" if _LABELS=="h_amitriptyline"
	replace _LABELS = "Paroxetine" if _LABELS=="i_paroxetine"
	replace _LABELS = "Duloxetine" if _LABELS=="j_duloxetine"
	replace _LABELS = "Other" if _LABELS=="k_other"
	replace _LABELS = "Polytherapy" if _LABELS=="l_Polytherapy"
	
	*drop if _BY==1 & model==3 & _ES!=.
	
	replace _LABELS = `"{bf:"' + _LABELS + `"}"' if _USE==0
	label variable _LABELS `"`"{bf: Birth outcomes}"'"'
	label variable total_exp `"`"{bf:Pooled}"' `"{bf}exposed n/N"'"'
	*label variable total_unexp `"`"{bf:Pooled}"' `"{bf}unexposed n/N"'"'
	label variable _WT `"`"{bf: Weight}"' `"(%)"'"'
	
	replace _ES = exp(_ES)
	replace _LCI = exp(_LCI)
	replace _UCI = exp(_UCI)
	
	replace _ES=10 if _ES==.
	replace _LCI=10 if _LCI==.
	replace _UCI=10 if _UCI==.
	
	egen seq=seq()
	
	forvalues x=2/55 {
		foreach y in _ES _LCI _UCI {
		
			sum `y' if seq==`x'
			local `y'_`x' = `r(mean)'
			local `y'_`x'_f : display %4.2fc ``y'_`x'' 
			
		}		
	}
	
	replace _ES=. if _ES==10
	replace _LCI=. if _LCI==10
	replace _UCI=. if _UCI==10
	
	forvalues x=2/55 {
	
		local total_exp_`x' = total_exp[`x']
		di "`total_exp_`x''"
		
	}
	
	* Macros to create the null line
	local t1=0
	local t2=55

	twoway ///
	(scatteri `t1' 1 `t2' 1, recast(line) yaxis(1) lpatter(dash) lcolor(cranberry)) /// null line
	(rcap _LCI _UCI seq, horizontal lcolor(black) msize(*0.5)) /// code for NO 95% CI
	(scatter seq _ES if _LABELS=="Preterm delivery", mcolor("254 192 170") ms(d) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Small for gestational age", mcolor("236 78 32") ms(d) msize(small) mlcolor(black) mlw(thin)) ///
	(scatter seq _ES if _LABELS=="Low Apgar score", mcolor("132 115 43") ms(d) msize(small) mlcolor(black) mlw(thin)), yscale(reverse) yscale(range(-2.25 55)) ///
	ylab("", angle(0) labsize(*0.6) notick nogrid nogextend) ///
	yline(-3) yline(0) yline(5, lcolor(gray) lpattern(dot)) yline(10, lcolor(gray) lpattern(dot)) ///
	title("{bf}Pooled odds ratios for individual antidepressants during pregnancy" "{bf}and birth outcomes in the UK, Norway, & Sweden", size(*0.5)) /// /// 
	yline(15, lcolor(gray) lpattern(dot)) yline(20, lcolor(gray) lpattern(dot)) yline(25, lcolor(gray) lpattern(dot)) yline(30, lcolor(gray) lpattern(dot)) yline(35, lcolor(gray) lpattern(dot)) yline(40, lcolor(gray) lpattern(dot)) yline(45, lcolor(gray) lpattern(dot)) yline(50, lcolor(gray) lpattern(dot)) ///
	text(-1.5 2.9 "{bf}aOR* (95% CI)", size(*0.45) justification(left) placement(e)) ///
	text(-1.5 0.1 "{bf}Antidepressant" "Birth outcome", size(*0.45) justification(left) placement(e)) ///
	text(-1.5 0.39 "{bf}Pooled exposed" "{it:n} / N", size(*0.45) justification(right) placement(w)) ///
	text(59.5 1 "{bf:Pooled aOR* (95% CI)}" "from fixed effects meta-analysis", size(*0.4)) ///
	text(59.5 0.1 "*Adjusted for year of birth, maternal age, previous" "stillbirth, parity, antipsychotic and anti-seizure" "medication use before pregnancy, depression," "anxiety, practice-level IMD and ethnicity (UK)," "maternal educational attainment and country of birth" "(Norway and Sweden), household disposable income" "(Sweden), smoking during pregnancy (UK and Sweden)," "maternal BMI (Sweden), number of primary care" "consultations before pregnancy (UK and Norway)", size(*0.35) justification(left) placement(e)) ///
	text(64 0.1 "{sup:‡}Norway and Sweden only", size(*0.35) justification(left) placement(e)) ///
		text(1 0.1 "{bf:Sertraline}", size(*0.45) justification(left) placement(e)) ///
		text(2 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(2 0.39 "`total_exp_2'", size(*0.45) justification(right) placement(w)) ///
	text(2 3.8 "`_ES_2_f' (`_LCI_2_f' – `_UCI_2_f')", size(*0.45)) ///
		text(3 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(3 0.39 "`total_exp_3'", size(*0.45) justification(right) placement(w)) ///
	text(3 3.8 "`_ES_3_f' (`_LCI_3_f' – `_UCI_3_f')", size(*0.45)) ///
		text(4 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(4 0.39 "`total_exp_4'", size(*0.45) justification(right) placement(w)) ///
	text(4 3.8 "`_ES_4_f' (`_LCI_4_f' – `_UCI_4_f')", size(*0.45)) ///
		text(6 0.1 "{bf:Citalopram}", size(*0.45) justification(left) placement(e)) ///
		text(7 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(7 0.39 "`total_exp_7'", size(*0.45) justification(right) placement(w)) ///
	text(7 3.8 "`_ES_7_f' (`_LCI_7_f' – `_UCI_7_f')", size(*0.45)) ///
		text(8 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(8 0.39 "`total_exp_8'", size(*0.45) justification(right) placement(w)) ///
	text(8 3.8 "`_ES_8_f' (`_LCI_8_f' – `_UCI_8_f')", size(*0.45)) ///
		text(9 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(9 0.39 "`total_exp_9'", size(*0.45) justification(right) placement(w)) ///
	text(9 3.8 "`_ES_9_f' (`_LCI_9_f' – `_UCI_9_f')", size(*0.45)) ///
		text(11 0.1 "{bf:Fluoxetine}", size(*0.45) justification(left) placement(e)) ///
		text(12 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(12 0.39 "`total_exp_12'", size(*0.45) justification(right) placement(w)) ///
	text(12 3.8 "`_ES_12_f' (`_LCI_12_f' – `_UCI_12_f')", size(*0.45)) ///
		text(13 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(13 0.39 "`total_exp_13'", size(*0.45) justification(right) placement(w)) ///
	text(13 3.8 "`_ES_13_f' (`_LCI_13_f' – `_UCI_13_f')", size(*0.45)) ///
		text(14 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(14 0.39 "`total_exp_14'", size(*0.45) justification(right) placement(w)) ///
	text(14 3.8 "`_ES_14_f' (`_LCI_14_f' – `_UCI_14_f')", size(*0.45)) ///
		text(16 0.1 "{bf:Escitalopram}", size(*0.45) justification(left) placement(e)) ///
		text(17 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(17 0.39 "`total_exp_17'", size(*0.45) justification(right) placement(w)) ///
	text(17 3.8 "`_ES_17_f' (`_LCI_17_f' – `_UCI_17_f')", size(*0.45)) ///
		text(18 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(18 0.39 "`total_exp_18'", size(*0.45) justification(right) placement(w)) ///
	text(18 3.8 "`_ES_18_f' (`_LCI_18_f' – `_UCI_18_f')", size(*0.45)) ///
		text(19 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(19 0.39 "`total_exp_19'", size(*0.45) justification(right) placement(w)) ///
	text(19 3.8 "`_ES_19_f' (`_LCI_19_f' – `_UCI_19_f')", size(*0.45)) ///
		text(21 0.1 "{bf:Venlafaxine}", size(*0.45) justification(left) placement(e)) ///
		text(22 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(22 0.39 "`total_exp_22'", size(*0.45) justification(right) placement(w)) ///
	text(22 3.8 "`_ES_22_f' (`_LCI_22_f' – `_UCI_22_f')", size(*0.45)) ///
		text(23 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(23 0.39 "`total_exp_23'", size(*0.45) justification(right) placement(w)) ///
	text(23 3.8 "`_ES_23_f' (`_LCI_23_f' – `_UCI_23_f')", size(*0.45)) ///
		text(24 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(24 0.39 "`total_exp_24'", size(*0.45) justification(right) placement(w)) ///
	text(24 3.8 "`_ES_24_f' (`_LCI_24_f' – `_UCI_24_f')", size(*0.45)) ///
		text(26 0.1 "{bf:Mirtazapine}", size(*0.45) justification(left) placement(e)) ///
		text(27 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(27 0.39 "`total_exp_27'", size(*0.45) justification(right) placement(w)) ///
	text(27 3.8 "`_ES_27_f' (`_LCI_27_f' – `_UCI_27_f')", size(*0.45)) ///
		text(28 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(28 0.39 "`total_exp_28'", size(*0.45) justification(right) placement(w)) ///
	text(28 3.8 "`_ES_28_f' (`_LCI_28_f' – `_UCI_28_f')", size(*0.45)) ///
		text(29 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(29 0.39 "`total_exp_29'", size(*0.45) justification(right) placement(w)) ///
	text(29 3.8 "`_ES_29_f' (`_LCI_29_f' – `_UCI_29_f')", size(*0.45)) ///
		text(31 0.1 "{bf:Amitriptyline}", size(*0.45) justification(left) placement(e)) ///
		text(32 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(32 0.39 "`total_exp_32'", size(*0.45) justification(right) placement(w)) ///
	text(32 3.8 "`_ES_32_f' (`_LCI_32_f' – `_UCI_32_f')", size(*0.45)) ///
		text(33 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(33 0.39 "`total_exp_33'", size(*0.45) justification(right) placement(w)) ///
	text(33 3.8 "`_ES_33_f' (`_LCI_33_f' – `_UCI_33_f')", size(*0.45)) ///
		text(34 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(34 0.39 "`total_exp_34'", size(*0.45) justification(right) placement(w)) ///
	text(34 3.8 "`_ES_34_f' (`_LCI_34_f' – `_UCI_34_f')", size(*0.45)) ///
	text(36 0.1 "{bf:Paroxetine}", size(*0.45) justification(left) placement(e)) ///
		text(37 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(37 0.39 "`total_exp_37'", size(*0.45) justification(right) placement(w)) ///
	text(37 3.8 "`_ES_37_f' (`_LCI_37_f' – `_UCI_37_f')", size(*0.45)) ///
		text(38 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(38 0.39 "`total_exp_38'", size(*0.45) justification(right) placement(w)) ///
	text(38 3.8 "`_ES_38_f' (`_LCI_38_f' – `_UCI_38_f')", size(*0.45)) ///
		text(39 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(39 0.39 "`total_exp_39'", size(*0.45) justification(right) placement(w)) ///
	text(39 3.8 "`_ES_39_f' (`_LCI_39_f' – `_UCI_39_f')", size(*0.45)) ///
	text(41 0.1 "{bf:Duloxetine}", size(*0.45) justification(left) placement(e)) ///
		text(42 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(42 0.39 "`total_exp_42'", size(*0.45) justification(right) placement(w)) ///
	text(42 3.8 "`_ES_42_f' (`_LCI_42_f' – `_UCI_42_f')", size(*0.45)) ///
		text(43 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(43 0.39 "`total_exp_43'", size(*0.45) justification(right) placement(w)) ///
	text(43 3.8 "`_ES_43_f' (`_LCI_43_f' – `_UCI_43_f')", size(*0.45)) ///
		text(44 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(44 0.39 "`total_exp_44'", size(*0.45) justification(right) placement(w)) ///
	text(44 3.8 "`_ES_44_f' (`_LCI_44_f' – `_UCI_44_f')", size(*0.45)) ///
	text(46 0.1 "{bf:Other}", size(*0.45) justification(left) placement(e)) ///
		text(47 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(47 0.39 "`total_exp_47'", size(*0.45) justification(right) placement(w)) ///
	text(47 3.8 "`_ES_47_f' (`_LCI_47_f' – `_UCI_47_f')", size(*0.45)) ///
		text(48 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(48 0.39 "`total_exp_48'", size(*0.45) justification(right) placement(w)) ///
	text(48 3.8 "`_ES_48_f' (`_LCI_48_f' – `_UCI_48_f')", size(*0.45)) ///
		text(49 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(49 0.39 "`total_exp_49'", size(*0.45) justification(right) placement(w)) ///
	text(49 3.8 "`_ES_49_f' (`_LCI_49_f' – `_UCI_49_f')", size(*0.45)) ///
	text(51 0.1 "{bf:Polytherapy}", size(*0.45) justification(left) placement(e)) ///
		text(52 0.1 "Preterm delivery", size(*0.45) justification(left) placement(e)) ///
	text(52 0.39 "`total_exp_52'", size(*0.45) justification(right) placement(w)) ///
	text(52 3.8 "`_ES_52_f' (`_LCI_52_f' – `_UCI_52_f')", size(*0.45)) ///
		text(53 0.1 "Small for gestational age", size(*0.45) justification(left) placement(e)) ///
	text(53 0.39 "`total_exp_53'", size(*0.45) justification(right) placement(w)) ///
	text(53 3.8 "`_ES_53_f' (`_LCI_53_f' – `_UCI_53_f')", size(*0.45)) ///
		text(54 0.1 "Low Apgar score{sup:‡}", size(*0.45) justification(left) placement(e)) ///
	text(54 0.39 "`total_exp_54'", size(*0.45) justification(right) placement(w)) ///
	text(54 3.8 "`_ES_54_f' (`_LCI_54_f' – `_UCI_54_f')", size(*0.45)) ///
	xscale(range(0.1 5) log) xlab(0.4(0.2)2.8, labsize(*0.4) format(%3.1fc) angle(45)) xscale(range(0.15 4.8)) plotregion(margin(1 1 0 1)) yscale(noline) xsize(90) ysize(100) ///
	graphregion(color(white) fcolor(white) ifcolor(white) lcolor(white)) legend(order(3 "Preterm delivery" 4 "SGA" 5 "Low Apgar score") size(*0.6) pos(5) col(1) region(lcolor(black))) /// 
	name(prim, replace) 
	
	*graph export "C:\Users\ti19522\OneDrive - University of Bristol\Flo Martin Supervisory Team\Year 4\6_Birth outcomes\ch6_drug_spec_fig.pdf", replace

/********************************************************************************

* Set working directory for saving graphs and save as PDF
	
	cd "$Graphdir"
	graph export drug_specific_all3.pdf, replace

********************************************************************************

* Erase unnecessary datasets

	erase "$Graphdir\preterm_ma.dta"
	erase "$Graphdir\sga_ma.dta"
	erase "$Graphdir\apgar_ma.dta"

* Stop logging, translate .smcl into .pdf and erase .smcl

	log close meta_analysis_drug_fig_all_3
	
	translate "$Logdir\3_figures\4c_meta analysis drug fig all 3.smcl" "$Logdir\3_figures\4c_meta analysis drug fig all 3.pdf", replace
	
	erase "$Logdir\3_figures\4c_meta analysis drug fig all 3.smcl"
	
********************************************************************************