
/*******************************************************************************

	Combine the data and counts from 

	Author: Flo Martin

	Date: 27/11/2023

	Table generated by this script
	
		- $Graphdir\data\family analyses data_all3.dta drug-specific analyses results in Norway
		
*******************************************************************************/

* Start logging

	log using "$Logdir\3_figures\5b_combining add adjust data", name(combining_add_adjust_data) replace
	
*******************************************************************************	

* Norway
* Maternal model counts

	import delimited using "$NOTabledir\august 24\add adjust bmi data_no.txt", varnames(1) clear
	
	replace outcome="sga" if outcome=="sga_pct"
	replace outcome="lga" if outcome=="lga_pct"
	
	save "$Graphdir\data\no_counts_addadjust.dta", replace
	
********************************************************************************	
* Sweden
* Maternal model counts

	import delimited using "$SETabledir\data for figures\add adjust analyses data se.txt", varnames(1) clear
	
	replace outcome="sga" if outcome=="sga_pct"
	replace outcome="lga" if outcome=="lga_pct"
	
	replace total = subinstr(total, ",", "", .)
	gen total_num=real(total)
	drop total
	rename total_num total
	
	drop model
	
	save "$Graphdir\data\se_counts_addadjust.dta", replace
	
********************************************************************************

* Combining the summary level data from the three countries

	use "$Graphdir\data\no_counts_addadjust.dta", clear
	append using "$Graphdir\data\uk_counts_addadjust.dta"
	append using "$Graphdir\data\se_counts_addadjust.dta"
	
	replace total_exp = subinstr(total_exp, " ", "", .)
	replace total_unexp = subinstr(total_unexp, " ", "", .)
	
	replace total_exp = subinstr(total_exp, "/", " / ", .)
	replace total_unexp = subinstr(total_unexp, "/", " / ", .)
	
	replace outcome= "a_stillborn" if outcome=="stillborn"
	replace outcome= "b_neonatal_death" if outcome=="neonatal_death"
	replace outcome= "c_preterm" if outcome=="preterm"
	replace outcome= "d_postterm" if outcome=="postterm"
	replace outcome= "e_sga" if outcome=="sga"
	replace outcome= "f_lga" if outcome=="lga"
	replace outcome= "g_apar5_bin" if outcome=="apgar5_bin"
	
	gen seq=1 if country=="uk"
	replace seq=2 if country=="no"
	replace seq=3 if country=="se"
	
	sort outcome seq
	
	save "$Graphdir\data\add adjust analyses data_all3.dta", replace
	
********************************************************************************

* Stop logging, translate .smcl into .pdf and erase .smcl

	log close combining_add_adjust_data
	
	translate "$Logdir\3_figures\5b_combining add adjust data.smcl" "$Logdir\3_figures\5b_combining add adjust data.pdf", replace
	
	erase "$Logdir\3_figures\5b_combining add adjust data.smcl"
	
********************************************************************************