
/*******************************************************************************

	Combine the data and counts from UK, Norway, and Sweden

	Author: Flo Martin

	Date: 27/11/2023

	Table generated by this script
	
		- $Graphdir\data\family analyses data_all3.dta drug-specific analyses results in Norway
		
*******************************************************************************/

* Start logging

	log using "$Logdir\meta analysis\6b_combining indic sample data", name(combining_indic_sample_data) replace
	
********************************************************************************

* Norway
* Maternal model counts

	import delimited using "$NOTabledir\indic sample data_no.txt", varnames(1) clear
	
	replace outcome="sga" if outcome=="sga_pct"
	replace outcome="lga" if outcome=="lga_pct"
	
	save "$Graphdir\data\no_counts_indicsample.dta", replace
	
********************************************************************************
	
* Sweden
* Maternal model counts

	import delimited using "$SETabledir\data for figures\indic sample data se.txt", varnames(1) clear
	
	replace outcome="sga" if outcome=="sga_pct"
	replace outcome="lga" if outcome=="lga_pct"
	
	replace total = subinstr(total, ",", "", .)
	gen total_num=real(total)
	drop total
	rename total_num total
	
	drop model
	
	save "$Graphdir\data\se_counts_indicsample.dta", replace
	
********************************************************************************

* Combining the summary level data from the three countries

	use "$Graphdir\data\no_counts_indicsample.dta", clear
	append using "$Graphdir\data\uk_counts_indicsample.dta"
	append using "$Graphdir\data\se_counts_indicsample.dta"
	
	replace total_exp = subinstr(total_exp, " ", "", .)
	replace total_unexp = subinstr(total_unexp, " ", "", .)
	
	replace total_exp = subinstr(total_exp, "/", " / ", .)
	replace total_unexp = subinstr(total_unexp, "/", " / ", .)
	
	replace outcome= "a_stillborn" if outcome=="stillborn"
	replace outcome= "b_neonatal_death" if outcome=="neonatal_death"
	replace outcome= "c_preterm" if outcome=="preterm"
	replace outcome= "d_postterm" if outcome=="postterm"
	replace outcome= "e_sga" if outcome=="sga"
	replace outcome= "f_lga" if outcome=="lga"
	replace outcome= "g_apar5_bin" if outcome=="apgar5_bin"
	
	gen seq=1 if country=="uk"
	replace seq=2 if country=="no"
	replace seq=3 if country=="se"
	
	sort outcome seq
	
	save "$Graphdir\data\indic sample analyses data_all3.dta", replace
	
********************************************************************************

* Stop logging, translate .smcl into .pdf and erase .smcl

	log close combining_indic_sample_data
	
	translate "$Logdir\meta analysis\6b_combining indic sample data.smcl" "$Logdir\meta analysis\6b_combining indic sample data.pdf", replace
	
	erase "$Logdir\meta analysis\6b_combining indic sample data.smcl"
	
********************************************************************************
