
/*******************************************************************************

	Combine the data and counts from the UK, Norway, and Sweden

	Author: Flo Martin

	Date: 27/11/2023

	Table generated by this script
	
		- $Graphdir\data\family analyses data_all3.dta drug-specific analyses results in Norway
		
*******************************************************************************/

* Start logging

	log using "$Logdir\meta analysis\7b_combining preterm type data", name(combining_preterm_type_data) replace
	
********************************************************************************	

* Norway
* Maternal model counts

	import delimited using "$NOTabledir\stratified preterm data_no.txt", varnames(1) clear
	
	save "$Graphdir\data\no_counts_stratpreterm.dta", replace
	
********************************************************************************	
* Sweden
* Maternal model counts

	import delimited using "$SETabledir\data for figures\strat preterm data se.txt", varnames(1) clear
	
	replace total = subinstr(total, ",", "", .)
	gen total_num=real(total)
	drop total
	rename total_num total
	
	drop model
	
	save "$Graphdir\data\se_counts_stratpreterm.dta", replace
	
********************************************************************************

* Combining the summary level data from the three countries

	use "$Graphdir\data\no_counts_stratpreterm.dta", clear
	append using "$Graphdir\data\uk_counts_stratpreterm.dta"
	append using "$Graphdir\data\se_counts_stratpreterm.dta"
	
	replace total_exp = subinstr(total_exp, " ", "", .)
	replace total_unexp = subinstr(total_unexp, " ", "", .)
	
	replace total_exp = subinstr(total_exp, "/", " / ", .)
	replace total_unexp = subinstr(total_unexp, "/", " / ", .)
	
	replace outcome= "a_modpreterm" if outcome=="modpreterm"
	replace outcome= "b_verypreterm" if outcome=="verypreterm"
	replace outcome= "c_expreterm" if outcome=="expreterm"
	
	gen seq=1 if country=="uk"
	replace seq=2 if country=="no"
	replace seq=3 if country=="se"
	
	sort outcome seq
	
	save "$Graphdir\data\strat preterm analyses data_all3.dta", replace
	
********************************************************************************

* Stop logging, translate .smcl into .pdf and erase .smcl

	log close combining_preterm_type_data
	
	translate "$Logdir\meta analysis\7b_combining preterm type data.smcl" "$Logdir\meta analysis\7b_combining preterm type data.pdf", replace
	
	erase "$Logdir\meta analysis\7b_combining preterm type data.smcl"
	
********************************************************************************
