
/*******************************************************************************

	Generate table 2 showing the prevalence of each outcome in the analysis stratified by antidepressant use during pregnancy

	Author: Flo Martin

	Date: 22/09/2023

	Table generated by this script
	
		- table 2.txt prevalences of the outcomes between exposed and unexposed
		
*******************************************************************************/

* Start logging

	log using "$Logdir\2_analysis\4_prevalence_of_outcomes_table", name(prevalence_of_outcomes_table) replace
	
********************************************************************************	
	
	* Generic code to output one row of table
	cap prog drop generaterow

	program define generaterow
		
		syntax, variable(varname) condition(string) outcome(string)
	
		* Put the varname and condition to left so that alignment can be checked vs shell
		file write tablecontent ("") _tab
		
		cou
		local overalldenom=r(N)
		
		cou if `variable' `condition'
		local rowdenom = r(N)
		local colpct = 100*(r(N)/`overalldenom')
		file write tablecontent %11.0fc (`rowdenom')  (" (") %4.1f (`colpct') (")") _tab

		cou if any_preg==1 
		local coldenom = r(N)
		cou if any_preg==1 & `variable' `condition'
		local pct = 100*(r(N)/`coldenom')
		file write tablecontent %11.0fc (r(N)) (" (") %4.1f (`pct') (")") _tab

		cou if any_preg==0 
		local coldenom = r(N)
		cou if any_preg==0 & `variable' `condition'
		local pct = 100*(r(N)/`coldenom')
		file write tablecontent %11.0fc (r(N)) (" (") %4.1f (`pct') (")") _n
	
	end
	
	* Generic code to output one row of table specifically for size (different denominator)
	cap prog drop generatesizerow

	program define generatesizerow
		
		syntax, variable(varname) condition(string) outcome(string)
	
		* Put the varname and condition to left so that alignment can be checked vs shell
		file write tablecontent ("") _tab
		
		cou if aga_pct!=.
		local overalldenom=r(N)
		
		cou if `variable' `condition'
		local rowdenom = r(N)
		local colpct = 100*(r(N)/`overalldenom')
		file write tablecontent %11.0fc (`rowdenom')  (" (") %4.1f (`colpct') (")") _tab

		cou if any_preg==1 
		local coldenom = r(N)
		cou if any_preg==1 & `variable' `condition'
		local pct = 100*(r(N)/`coldenom')
		file write tablecontent %11.0fc (r(N)) (" (") %4.1f (`pct') (")") _tab

		cou if any_preg==0 
		local coldenom = r(N)
		cou if any_preg==0 & `variable' `condition'
		local pct = 100*(r(N)/`coldenom')
		file write tablecontent %11.0fc (r(N)) (" (") %4.1f (`pct') (")") _n
	
	end
	
		* Generic code to output one preterm delivery row of table
	cap prog drop generateptrow

	program define generateptrow
		
		syntax, variable(varname) condition(string) outcome(string)
	
		* Put the varname and condition to left so that alignment can be checked vs shell
		file write tablecontent ("") _tab
		
		cou if term_cat==0
		local overalldenom=r(N)
		
		cou if `variable' `condition' & term_cat==0
		local rowdenom = r(N)
		local colpct = 100*(r(N)/`overalldenom')
		file write tablecontent %11.0fc (`rowdenom')  (" (") %4.1f (`colpct') (")") _tab

		cou if any_preg==1 & term_cat==0
		local coldenom = r(N)
		cou if any_preg==1 & `variable' `condition'
		local pct = 100*(r(N)/`coldenom')
		file write tablecontent %11.0fc (r(N)) (" (") %4.1f (`pct') (")") _tab

		cou if any_preg==0 & term_cat==0
		local coldenom = r(N)
		cou if any_preg==0 & `variable' `condition'
		local pct = 100*(r(N)/`coldenom')
		file write tablecontent %11.0fc (r(N)) (" (") %4.1f (`pct') (")") _n
	
	end
	
		* Generic code to output one preterm delivery row of table
	cap prog drop generatesizerow

	program define generatesizerow
		
		syntax, variable(varname) condition(string) outcome(string)
	
		* Put the varname and condition to left so that alignment can be checked vs shell
		file write tablecontent ("") _tab
		
		cou if weit_pct!=.
		local overalldenom=r(N)
		
		cou if `variable' `condition' 
		local rowdenom = r(N)
		local colpct = 100*(r(N)/`overalldenom')
		file write tablecontent %11.0fc (`rowdenom')  (" (") %4.1f (`colpct') (")") _tab

		cou if any_preg==1 & weit_pct!=.
		local coldenom = r(N)
		cou if any_preg==1 & `variable' `condition'
		local pct = 100*(r(N)/`coldenom')
		file write tablecontent %11.0fc (r(N)) (" (") %4.1f (`pct') (")") _tab

		cou if any_preg==0 & weit_pct!=.
		local coldenom = r(N)
		cou if any_preg==0 & `variable' `condition'
		local pct = 100*(r(N)/`coldenom')
		file write tablecontent %11.0fc (r(N)) (" (") %4.1f (`pct') (")") _n
	
	end

********************************************************************************

* Generic code to output one section (varible) within table (calls above)

	cap prog drop tabulatevariable
	prog define tabulatevariable
		
		syntax, variable(varname) start(real) end(real) outcome(string)

		foreach varlevel of numlist `start'/`end'{ 
		
			generaterow, variable(`variable') condition("==`varlevel'") outcome(any_preg)
	
		}

	end
	
	cap prog drop tabulateptvariable
	prog define tabulateptvariable
		
		syntax, variable(varname) start(real) end(real) outcome(string)

		foreach varlevel of numlist `start'/`end'{ 
		
			generateptrow, variable(`variable') condition("==`varlevel'") outcome(any_preg)
	
		}

	end
	
	cap prog drop tabulatesizevariable
	prog define tabulatesizevariable
		
		syntax, variable(varname) start(real) end(real) outcome(string)

		foreach varlevel of numlist `start'/`end'{ 
		
			generatesizerow, variable(`variable') condition("==`varlevel'") outcome(any_preg)
	
		}

	end

********************************************************************************

* Set up output file

		*use "$Deriveddir\maternal_analysis_dataset.dta", clear

********************************************************************************
* 2 - Prepare formats for data for output
********************************************************************************

		*gen aga_pct = 1 if sga_pct==0 & lga_pct==0
		
		*gen aga_ex_intergrowth = 1 if sga_ex_intergrowth==0 & lga_ex_intergrowth==0
		*gen aga_ex_swedish = 1 if sga_ex_swedish==0 & lga_ex_swedish==0

		*gen weit_pct = 0 if sga_pct==1
		replace weit_pct = 1 if aga_pct==1
		replace weit_pct = 2 if lga_pct

		tab weit_pct, m

		cap file close tablecontent
		file open tablecontent using "$Tabledir\prevalence of outcomes.txt", write text replace

		file write tablecontent "Variable" _tab "Total" _tab "Exposed to antidepressants during pregnancy" _tab "Unexposed to antidepressants during pregnancy" _n
		
	*gen byte total=1
		
		file write tablecontent "Total"
		tabulatevariable, variable(total) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Birth outcome" _n
		
		file write tablecontent "Stillborn"
		tabulatevariable, variable(stillborn) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Neonatal death" 
		tabulatevariable, variable(neonatal_death) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Apgar score < 7 at 5 mins" 
		tabulatevariable, variable(apgar5_bin) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Gestational age" _n
		
		file write tablecontent "Preterm delivery (<37 weeks')"
		tabulatevariable, variable(term_cat) start(0) end(0) outcome(any_preg)
		
		file write tablecontent "Moderate-to-late preterm (32-37 weeks')"
		tabulateptvariable, variable(preterm_class) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Very preterm (28-32 weeks')"
		tabulateptvariable, variable(preterm_class) start(2) end(2) outcome(any_preg)
		
		file write tablecontent "Extremely preterm (<28 weeks')"
		tabulateptvariable, variable(preterm_class) start(3) end(3) outcome(any_preg)
		
		file write tablecontent "Term delivery (37-42 weeks')"
		tabulatevariable, variable(term_cat) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Post-term delivery (>42 weeks')"
		tabulatevariable, variable(term_cat) start(2) end(2) outcome(any_preg)
		
	*gen byte total_pct=1 if weit_pct!=.
		
		file write tablecontent "Total with birthweight & sex"
		tabulatevariable, variable(total_pct) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Size for gestational age (based on the percentile distribution)" _n
		
		file write tablecontent "Small for gestational age (SGA, <10th percentile)"
		tabulatesizevariable, variable(sga_pct) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Adequate for gestational age (AGA, 10-90th percentile)"
		tabulatesizevariable, variable(aga_pct) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Large for gestational age (LGA, >90th percentile)"
		tabulatesizevariable, variable(lga_pct) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "Size for gestational age (based on INTERGROWTH-21)" _n
		
		file write tablecontent "SGA"
		tabulatesizevariable, variable(sga_ex_intergrowth) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "AGA"
		tabulatesizevariable, variable(aga_ex_intergrowth) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "LGA"
		tabulatesizevariable, variable(lga_ex_intergrowth) start(1) end(1) outcome(any_preg)

		file write tablecontent "Size for gestational age (based on new Swedish standard)" _n
		
		file write tablecontent "SGA"
		tabulatesizevariable, variable(sga_ex_swedish) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "AGA"
		tabulatesizevariable, variable(aga_ex_swedish) start(1) end(1) outcome(any_preg)
		
		file write tablecontent "LGA"
		tabulatesizevariable, variable(lga_ex_swedish) start(1) end(1) outcome(any_preg)
		
		file close tablecontent
		
********************************************************************************

* Stop logging, translate .smcl into .pdf and erase .smcl

	log close prevalence_of_outcomes_table
	
	translate "$Logdir\2_analysis\4_prevalence_of_outcomes_table.smcl" "$Logdir\2_analysis\4_prevalence_of_outcomes_table.pdf", replace
	
	erase "$Logdir\2_analysis\4_prevalence_of_outcomes_table.smcl"
	
********************************************************************************/